In [1]:
import polars as pl

In [2]:
integrative_scores = pl.read_csv(
    "../3_outputs/all_assay_gene_variant_summary_all_cols.tsv",
    separator="\t",
    infer_schema_length=100000)
integrative_scores

shape: (1_430, 1_031)
┌─────────┬────────────┬───────────┬────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ symbol  ┆ ensembl_ge ┆ orf_id    ┆ mut_id ┆ … ┆ img_misloc ┆ img_pheno_ ┆ dualipa_hi ┆ imaging_h │
│ ---     ┆ ne_id      ┆ ---       ┆ ---    ┆   ┆ _hit       ┆ hit_strict ┆ t          ┆ it        │
│ str     ┆ ---        ┆ i64       ┆ i64    ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│         ┆ str        ┆           ┆        ┆   ┆ bool       ┆ bool       ┆ bool       ┆ bool      │
╞═════════╪════════════╪═══════════╪════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ ABCD1   ┆ ENSG000001 ┆ 100008637 ┆ 209127 ┆ … ┆ false      ┆ false      ┆ false      ┆ false     │
│         ┆ 01986      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ ABCD1   ┆ ENSG000001 ┆ 100008637 ┆ 209132 ┆ … ┆ false      ┆ false      ┆ false      ┆ false     │
│         ┆ 01986      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ ACSF3   ┆ ENSG000001 ┆ 71337     ┆ 3940   ┆ … ┆ null       ┆ null       ┆ false      ┆ false     │
│         ┆ 76715      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ ACSF3   ┆ ENSG000001 ┆ 71337     ┆ 3943   ┆ … ┆ null       ┆ null       ┆ false      ┆ false     │
│         ┆ 76715      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ ACSF3   ┆ ENSG000001 ┆ 71337     ┆ 3960   ┆ … ┆ null       ┆ null       ┆ false      ┆ false     │
│         ┆ 76715      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ …       ┆ …          ┆ …         ┆ …      ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ ZC4H2   ┆ ENSG000001 ┆ 4320      ┆ 215107 ┆ … ┆ false      ┆ false      ┆ false      ┆ false     │
│         ┆ 26970      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ ZC4H2   ┆ ENSG000001 ┆ 4320      ┆ 215106 ┆ … ┆ false      ┆ false      ┆ false      ┆ false     │
│         ┆ 26970      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ ZMYND10 ┆ ENSG000000 ┆ 9866      ┆ 298    ┆ … ┆ false      ┆ false      ┆ false      ┆ false     │
│         ┆ 04838      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ ZMYND10 ┆ ENSG000000 ┆ 9866      ┆ 216928 ┆ … ┆ null       ┆ null       ┆ false      ┆ false     │
│         ┆ 04838      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ ZMYND10 ┆ ENSG000000 ┆ 9866      ┆ 216927 ┆ … ┆ null       ┆ null       ┆ false      ┆ false     │
│         ┆ 04838      ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
└─────────┴────────────┴───────────┴────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [15]:
ppi_detailed_analyses

shape: (2_945, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ ad_orf_id ┆ db_orf_id ┆ db_mut_id ┆ normalize ┆ … ┆ ratio    ┆ perturbed ┆ perturbat ┆ perturbat │
│ ---       ┆ ---       ┆ ---       ┆ d_score   ┆   ┆ ---      ┆ ---       ┆ ion_class ┆ ion_class │
│ i64       ┆ i64       ┆ i64       ┆ ---       ┆   ┆ f64      ┆ bool      ┆ es        ┆ es_2      │
│           ┆           ┆           ┆ f64       ┆   ┆          ┆           ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 100015161 ┆ 3980      ┆ 201376    ┆ 0.3125    ┆ … ┆ 0.833333 ┆ false     ┆ similar   ┆ slightly  │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ perturbed │
│ 3013      ┆ 7323      ┆ 216371    ┆ 0.1875    ┆ … ┆ 0.5      ┆ false     ┆ perturbed ┆ perturbed │
│ 56215     ┆ 52920     ┆ 2670      ┆ 0.6875    ┆ … ┆ 0.733333 ┆ false     ┆ slightly  ┆ slightly  │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ perturbed ┆ perturbed │
│ 6644      ┆ 5723      ┆ 201967    ┆ 0.6875    ┆ … ┆ 1.375    ┆ false     ┆ increased ┆ increased │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ edge      ┆ edge      │
│ 100069191 ┆ 54308     ┆ 3069      ┆ 0.0       ┆ … ┆ 0.0      ┆ true      ┆ edge lost ┆ edge lost │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 52866     ┆ 7323      ┆ 216371    ┆ 0.5625    ┆ … ┆ 3.0      ┆ false     ┆ increased ┆ increased │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ edge      ┆ edge      │
│ 54855     ┆ 3980      ┆ 201374    ┆ 0.125     ┆ … ┆ 0.5      ┆ false     ┆ perturbed ┆ perturbed │
│ 5723      ┆ 5723      ┆ 201964    ┆ 0.5625    ┆ … ┆ 0.9      ┆ false     ┆ similar   ┆ slightly  │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ perturbed │
│ 2522      ┆ 7652      ┆ 1799      ┆ 0.3125    ┆ … ┆ 0.357143 ┆ true      ┆ highly    ┆ perturbed │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ perturbed ┆           │
│ 100066360 ┆ 4870      ┆ 215281    ┆ 1.0       ┆ … ┆ 1.0      ┆ false     ┆ WT-like   ┆ WT-like   │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [16]:
imaging_detailed_analyses = pl.read_csv("../../2_individual_assay_results/imaging/3_outputs/pheno_var_clustering_results.csv")
imaging_detailed_analyses_mlh1 = imaging_detailed_analyses.filter(
    pl.col("Metadata_gene_allele").str.contains("MLH1")
)
ppi_detailed_analyses = pl.read_csv("../../2_individual_assay_results/ppi/3_outputs/sqY2H/7_edge_perturbation_categorical.csv", infer_schema_length=100000)

ppi_detailed_analyses_mlh1 = ppi_detailed_analyses.join(
    integrative_scores.filter(
        pl.col("symbol")=="MLH1",
    ),
    left_on=["db_orf_id","db_mut_id"],
    right_on=["orf_id", "mut_id"],
    how="inner"
)