In [2]:
# Adapted file from Luke Lambourne

TODO

- sort out the date appended issue
- move to a .py file
- make a softlink of the dropbox folder to data/internal
- add columns to df, that are: 
    - has been tried (yes/no)
    - is confident (yes/no)
    - number of contacts (yes/no)
    - is interface residue (yes/no)
    - number of a.a. from closest interface residue?
    - number of angstrom from closest interface residue
- get the interface residues and look for overlap with tested variants

In [40]:
from pathlib import Path

import pandas as pd

import sys

sys.path.append('../../../2_individual_assay_results')

from alphafold_multimer_utils import *

In [9]:
output_dir = '../3_outputs/sqY2H'

In [8]:
# AF3 dimer structures stored locally

rrc = load_probable_residue_contacts('/Users/user_42/Partners HealthCare Dropbox/Maxime Tixhon/VarChamp/predicted_structures')

In [10]:
rrc['pair'].nunique()

154

In [11]:
(rrc.groupby('pair').size() >= 5).sum()

143

In [12]:
with open(f'{output_dir}/pairs_with_confident_af3_structure.txt', 'w') as f:
    f.write(
'\n'.join(rrc.groupby('pair').size()
          .loc[(rrc.groupby('pair').size() >= 5)]
          .index.map(lambda x: x.upper()))
    )

In [27]:
# filter rrc to only these pairs

confident_pairs = pd.read_csv(f'{output_dir}/pairs_with_confident_af3_structure.txt', header=None, names=['pair'])['pair'].tolist()
rrc_confident = rrc[rrc['pair'].isin([p.lower() for p in confident_pairs])]
rrc_confident

,Residue_index_X,Residue_index_Y,pair,contact_probability,gene_name_a,gene_name_b
817,169,160,o43790_q6a163,0.96,o43790,q6a163
879,176,167,o43790_q6a163,0.96,o43790,q6a163
941,183,174,o43790_q6a163,0.97,o43790,q6a163
942,183,178,o43790_q6a163,0.96,o43790,q6a163
970,186,178,o43790_q6a163,0.96,o43790,q6a163
...,...,...,...,...,...,...
1736,171,102,q14376_q14376,0.99,q14376,q14376
1764,174,98,q14376_q14376,0.97,q14376,q14376
1765,174,99,q14376_q14376,0.98,q14376,q14376
1766,174,100,q14376_q14376,0.97,q14376,q14376
1767,174,101,q14376_q14376,0.97,q14376,q14376

In [35]:
# local file from georges

af_mapping = pd.read_csv('/Users/user_42/Downloads/CCSB_allele_collection_AF_mapped.tsv', sep='\t')
af_mapping['uniprot_id'] = af_mapping['AF_id'].str.split('_').str[0]
af_mapping

,symbol,ccsb_mut_id,aa_change,AF_id,mapped_AF_pos,mapped_AF_aa,matching_expected_mut_pos,matching_expected_mut_aa,alignment_score,n_gap_ccsb_aligned,n_gap_AF_aligned,n_mismatch,uniprot_id
0,GBA,CCSBVarC000001,Val54Leu,P04062_F1,54,Val,True,True,0.994403,0,0,1,P04062
1,GBA,CCSBVarC000002,Leu224Phe,P04062_F1,224,Leu,True,True,0.994403,0,0,1,P04062
2,GBA,CCSBVarC000003,Arg296Gln,P04062_F1,296,Arg,True,True,0.994403,0,0,1,P04062
3,GBA,CCSBVarC000004,Leu483Pro,P04062_F1,483,Leu,True,True,0.994403,0,0,1,P04062
4,SLC9A3R1,CCSBVarC000005,Leu110Val,O14745_F1,110,Leu,True,True,0.991620,0,0,1,O14745
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8097,TTR,CCSBVarC008481,Asp119Asn,P02766_F1,119,Asp,True,True,0.979592,0,0,1,P02766
8098,PMP22,CCSBVarC008466,His51Arg,Q01453_F1,51,His,True,True,0.981250,0,0,1,Q01453
8099,CLN6,CCSBVarC008436,Gly30Ala,Q9NWW5_F1,30,Gly,True,True,0.990354,0,0,1,Q9NWW5
8100,PMP22,CCSBVarC008467,Ala135Thr,Q01453_F1,135,Ala,True,True,0.981250,0,0,1,Q01453
8101,NR0B1,CCSBVarC008465,Val126Met,P51843_F1,126,Val,True,True,0.993617,0,0,1,P51843

In [36]:
mlh1_af = af_mapping.loc[af_mapping['symbol'] == 'MLH1']
mlh1_af

,symbol,ccsb_mut_id,aa_change,AF_id,mapped_AF_pos,mapped_AF_aa,matching_expected_mut_pos,matching_expected_mut_aa,alignment_score,n_gap_ccsb_aligned,n_gap_AF_aligned,n_mismatch,uniprot_id
292,MLH1,CCSBVarC000316,Ser44Phe,P40692_F1,44,Ser,True,True,0.996032,0,0,1,P40692
293,MLH1,CCSBVarC000317,Gly244Asp,P40692_F1,244,Gly,True,True,0.996032,0,0,1,P40692
294,MLH1,CCSBVarC000318,Arg472Ile,P40692_F1,472,Arg,True,True,0.996032,0,0,1,P40692
295,MLH1,CCSBVarC000319,Ala586Asp,P40692_F1,586,Ala,True,True,0.996032,0,0,1,P40692
3031,MLH1,CCSBVarC003190,Ile36Asn,P40692_F1,36,Ile,True,True,0.996032,0,0,1,P40692
3032,MLH1,CCSBVarC003191,Asn38Asp,P40692_F1,38,Asn,True,True,0.996032,0,0,1,P40692
3033,MLH1,CCSBVarC003192,Asp41His,P40692_F1,41,Asp,True,True,0.996032,0,0,1,P40692
3034,MLH1,CCSBVarC003193,Leu73Pro,P40692_F1,73,Leu,True,True,0.996032,0,0,1,P40692
3035,MLH1,CCSBVarC003194,Leu73Arg,P40692_F1,73,Leu,True,True,0.996032,0,0,1,P40692
3036,MLH1,CCSBVarC003195,Ser93Gly,P40692_F1,93,Ser,True,True,0.996032,0,0,1,P40692
3037,MLH1,CCSBVarC003196,Ser106Arg,P40692_F1,106,Ser,True,True,0.996032,0,0,1,P40692
3038,MLH1,CCSBVarC003197,Tyr126Asn,P40692_F1,126,Tyr,True,True,0.996032,0,0,1,P40692
3039,MLH1,CCSBVarC003198,Gly147Arg,P40692_F1,147,Gly,True,True,0.996032,0,0,1,P40692
3040,MLH1,CCSBVarC003199,Ala160Val,P40692_F1,160,Ala,True,True,0.996032,0,0,1,P40692
3041,MLH1,CCSBVarC003200,Val185Gly,P40692_F1,185,Val,True,True,0.996032,0,0,1,P40692
3042,MLH1,CCSBVarC003201,Glu234Gly,P40692_F1,234,Glu,True,True,0.996032,0,0,1,P40692
3043,MLH1,CCSBVarC003202,Ser295Thr,P40692_F1,295,Ser,True,True,0.996032,0,0,1,P40692
3044,MLH1,CCSBVarC003203,Asp304Gly,P40692_F1,304,Asp,True,True,0.996032,0,0,1,P40692
3045,MLH1,CCSBVarC003204,Arg385Pro,P40692_F1,385,Arg,True,True,0.996032,0,0,1,P40692
3046,MLH1,CCSBVarC003205,Arg474Gln,P40692_F1,474,Arg,True,True,0.996032,0,0,1,P40692
3047,MLH1,CCSBVarC003206,Asp485Glu,P40692_F1,485,Asp,True,True,0.996032,0,0,1,P40692
3048,MLH1,CCSBVarC003207,Phe568Ile,P40692_F1,568,Phe,True,True,0.996032,0,0,1,P40692
3049,MLH1,CCSBVarC003208,Pro640Ser,P40692_F1,640,Pro,True,True,0.996032,0,0,1,P40692
3050,MLH1,CCSBVarC003209,Lys751Arg,P40692_F1,751,Lys,True,True,0.996032,0,0,1,P40692
6984,MLH1,CCSBVarC007370,Pro28Leu,P40692_F1,28,Pro,True,True,0.996032,0,0,1,P40692
6985,MLH1,CCSBVarC007371,Ala29Gly,P40692_F1,29,Ala,True,True,0.996032,0,0,1,P40692
6986,MLH1,CCSBVarC007372,Ala31Gly,P40692_F1,31,Ala,True,True,0.996032,0,0,1,P40692
6987,MLH1,CCSBVarC007373,Ile36Met,P40692_F1,36,Ile,True,True,0.996032,0,0,1,P40692
6988,MLH1,CCSBVarC007374,Asn38His,P40692_F1,38,Asn,True,True,0.996032,0,0,1,P40692
6989,MLH1,CCSBVarC007375,Asn38Lys,P40692_F1,38,Asn,True,True,0.996032,0,0,1,P40692
6990,MLH1,CCSBVarC007376,Cys39Tyr,P40692_F1,39,Cys,True,True,0.996032,0,0,1,P40692
6991,MLH1,CCSBVarC007377,Cys39Phe,P40692_F1,39,Cys,True,True,0.996032,0,0,1,P40692
6992,MLH1,CCSBVarC007378,Ser295Gly,P40692_F1,295,Ser,True,True,0.996032,0,0,1,P40692
6993,MLH1,CCSBVarC007379,His318Gln,P40692_F1,318,His,True,True,0.996032,0,0,1,P40692
6994,MLH1,CCSBVarC007380,Ser508Arg,P40692_F1,508,Ser,True,True,0.996032,0,0,1,P40692
6995,MLH1,CCSBVarC007381,Leu559Pro,P40692_F1,559,Leu,True,True,0.996032,0,0,1,P40692
6996,MLH1,CCSBVarC007382,Leu582Val,P40692_F1,582,Leu,True,True,0.996032,0,0,1,P40692
6997,MLH1,CCSBVarC007383,Ala586Pro,P40692_F1,586,Ala,True,True,0.996032,0,0,1,P40692
6998,MLH1,CCSBVarC007384,Ala608Asp,P40692_F1,608,Ala,True,True,0.996032,0,0,1,P40692
6999,MLH1,CCSBVarC007385,Glu613Asp,P40692_F1,613,Glu,True,True,0.996032,0,0,1,P40692
7000,MLH1,CCSBVarC007386,Lys618Arg,P40692_F1,618,Lys,True,True,0.996032,0,0,1,P40692
7001,MLH1,CCSBVarC007387,Ala619Pro,P40692_F1,619,Ala,True,True,0.996032,0,0,1,P40692
7002,MLH1,CCSBVarC007388,Leu622Pro,P40692_F1,622,Leu,True,True,0.996032,0,0,1,P40692
7003,MLH1,CCSBVarC007389,Gly634Val,P40692_F1,634,Gly,True,True,0.996032,0,0,1,P40692
7004,MLH1,CCSBVarC007390,Leu653Pro,P40692_F1,653,Leu,True,True,0.996032,0,0,1,P40692
7005,MLH1,CCSBVarC007391,Pro654Leu,P40692_F1,654,Pro,True,True,0.996032,0,0,1,P40692
7006,MLH1,CCSBVarC007392,Glu663Gly,P40692_F1,663,Glu,True,True,0.996032,0,0,1,P40692
7007,MLH1,CCSBVarC007393,Glu663Asp,P40692_F1,663,Glu,True,True,0.996032,0,0,1,P40692
7008,MLH1,CCSBVarC007394,Lys670Arg,P40692_F1,670,Lys,True,True,0.996032,0,0,1,P40692
7009,MLH1,CCSBVarC007395,Cys680Arg,P40692_F1,680,Cys,True,True,0.996032,0,0,1,P40692
7010,MLH1,CCSBVarC007396,Cys680Gly,P40692_F1,680,Cys,True,True,0.996032,0,0,1,P40692
7011,MLH1,CCSBVarC007397,Ala681Thr,P40692_F1,681,Ala,True,True,0.996032,0,0,1,P40692
7012,MLH1,CCSBVarC007398,Ala681Val,P40692_F1,681,Ala,True,True,0.996032,0,0,1,P40692
7013,MLH1,CCSBVarC007399,Met682Thr,P40692_F1,682,Met,True,True,0.996032,0,0,1,P40692
7014,MLH1,CCSBVarC007400,Gln701His,P40692_F1,701,Gln,True,True,0.996032,0,0,1,P40692
7015,MLH1,CCSBVarC007401,Val716Met,P40692_F1,716,Val,True,True,0.996032,0,0,1,P40692
7016,MLH1,CCSBVarC007402,Pro747Ser,P40692_F1,747,Pro,True,True,0.996032,0,0,1,P40692

In [37]:
rrc_confident[rrc_confident['pair'].str.contains('p40692')]

Empty DataFrame
Columns: [Residue_index_X, Residue_index_Y, pair, contact_probability, gene_name_a, gene_name_b]
Index: []

In [38]:
# no MLH1 interactions with confident AF3 structures, lets look for any AF3 structures with MLH1 and check confidence scores

def load_probable_residue_contacts(in_dir, cutoff=0.95):
    in_dir = Path(in_dir)
    rrc = []
    for fpath in in_dir.glob("*/*_confidences.json"):
        if fpath.stem.endswith("summary_confidences"):
            continue
        pair = fpath.parents[0].stem
        len_a, len_b = get_lengths_from_PDB_file(_find_pdb_file_path(fpath.parent))
        with open(fpath, "r") as f:
            conf = json.load(f)
        cp = np.array(conf["contact_probs"])
        pairs = pd.DataFrame(
            data=np.array(np.where(cp > cutoff)).T,
            columns=["Residue_index_X", "Residue_index_Y"],
        )
        pairs["pair"] = pair
        pairs["contact_probability"] = pairs.apply(
            lambda row: cp[row["Residue_index_X"], row["Residue_index_Y"]], axis=1
        )
        pairs = pairs.loc[
            (pairs["Residue_index_X"] < len_a) & (pairs["Residue_index_Y"] >= len_a), :
        ]
        pairs["Residue_index_X"] = pairs["Residue_index_X"] + 1
        pairs["Residue_index_Y"] = (pairs["Residue_index_Y"] - len_a) + 1
        rrc.append(pairs.copy())
    rrc = pd.concat(rrc)
    rrc["gene_name_a"] = rrc["pair"].apply(lambda x: x.split("_")[0])
    rrc["gene_name_b"] = rrc["pair"].apply(lambda x: x.split("_")[1])
    return rrc

In [57]:
in_dir = '/Users/user_42/Partners HealthCare Dropbox/Maxime Tixhon/VarChamp/predicted_structures'
gene_filter = 'p40692'  # MLH1 UniProt ID
cutoff = 0.1

in_dir = Path(in_dir)
rrc = []

for fpath in in_dir.glob("*/*_confidences.json"):
    if fpath.stem.endswith("summary_confidences"):
        continue
    
    pair = fpath.parents[0].stem
    
    # Filter for MLH1-containing pairs
    if gene_filter.lower() not in pair.lower():
        continue
    
    len_a, len_b = get_lengths_from_PDB_file(_find_pdb_file_path(fpath.parent))
    
    with open(fpath, "r") as f:
        conf = json.load(f)
    
    cp = np.array(conf["contact_probs"])
    
    pairs = pd.DataFrame(
        data=np.array(np.where(cp > cutoff)).T,
        columns=["Residue_index_X", "Residue_index_Y"],
    )
    
    
    
    if len(pairs) == 0:
        continue
        
    pairs["pair"] = pair
    pairs["contact_probability"] = pairs.apply(
        lambda row: cp[row["Residue_index_X"], row["Residue_index_Y"]], axis=1
    )
    
    
    # Filter for inter-chain contacts only
    pairs = pairs.loc[
        (pairs["Residue_index_X"] < len_a) & (pairs["Residue_index_Y"] >= len_a), :
    ]
    
    if len(pairs) == 0:
        continue
    

    
    # Adjust indices to 1-based
    pairs["Residue_index_X"] = pairs["Residue_index_X"] + 1
    pairs["Residue_index_Y"] = (pairs["Residue_index_Y"] - len_a) + 1
    
    rrc.append(pairs.copy())

if len(rrc) == 0:
    print(f"No contacts found for {gene_filter} above cutoff {cutoff}")
    # return pd.DataFrame()

rrc = pd.concat(rrc)
rrc["gene_name_a"] = rrc["pair"].apply(lambda x: x.split("_")[0])
rrc["gene_name_b"] = rrc["pair"].apply(lambda x: x.split("_")[1])


rrc
# return rrc

# # # Usage:
# # mlh1_contacts = load_probable_residue_contacts_mlh1(
# # '/Users/user_42/Partners HealthCare Dropbox/Maxime Tixhon/VarChamp/predicted_structures',
# # cutoff=0.95,
# # gene_filter='p40692'  # MLH1 UniProt ID
# # )

# # print(f"Found {len(mlh1_contacts)} contacts for MLH1")
# # print(f"Number of unique MLH1 interaction pairs: {mlh1_contacts['pair'].nunique()}")
# # print("\nMLH1 interaction partners:")
# # print(mlh1_contacts.groupby('pair').size().sort_values(ascending=False))

,Residue_index_X,Residue_index_Y,pair,contact_probability,gene_name_a,gene_name_b
6,1,596,p26045_p40692,0.12,p26045,p40692
37,5,601,p26045_p40692,0.13,p26045,p40692
66,8,607,p26045_p40692,0.11,p26045,p40692
67,8,610,p26045_p40692,0.12,p26045,p40692
1073,112,460,o15131_p40692,0.12,o15131,p40692
...,...,...,...,...,...,...
8778,752,164,p40692_p43361,0.11,p40692,p43361
8787,753,164,p40692_p43361,0.12,p40692,p43361
8788,753,231,p40692_p43361,0.11,p40692,p43361
1587,167,741,o95926_p40692,0.11,o95926,p40692
1844,164,201,o00746_p40692,0.11,o00746,p40692