# Create edgotype profiles

In this step, we make one edgotype profile per gene of interactors by alleles. Later, we will explore metrics that summarize overall perturbation for each allele (quantitative score like imaging / abundance)

In [48]:
import polars as pl

In [49]:
inputs_dir = "../1_inputs/sqY2H"
outputs_dir = "../3_outputs/sqY2H"

In [50]:
scores = pl.read_csv(f"{outputs_dir}/4_normalized_consensus_scores.csv")
scores

shape: (4_064, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ad_orf_id ┆ db_orf_id ┆ db_mut_id ┆ retest_ba ┆ … ┆ clinvar_c ┆ gnomad_af ┆ StarStatu ┆ allele_0 │
│ ---       ┆ ---       ┆ ---       ┆ tch       ┆   ┆ lnsig_cle ┆ ---       ┆ s         ┆ ---      │
│ i64       ┆ i64       ┆ i64       ┆ ---       ┆   ┆ an        ┆ f64       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆ ---       ┆           ┆ f64       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 53964     ┆ 2713      ┆ 449       ┆ VUSAPWT1B ┆ … ┆ 1_Pathoge ┆ 6.8405e-7 ┆ 3.0       ┆ MLH1_Pro │
│           ┆           ┆           ┆ 1         ┆   ┆ nic       ┆           ┆           ┆ 28Leu    │
│ 71393     ┆ 71191     ┆ 205704    ┆ VUSAPWT2B ┆ … ┆ 4_VUS     ┆ 0.000042  ┆ 1.0       ┆ SUOX_Ala │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆ 265Asp   │
│ 2522      ┆ 7652      ┆ 1818      ┆ VUSAPWT1B ┆ … ┆ 4_VUS     ┆ 6.8406e-7 ┆ 1.0       ┆ STXBP1_L │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆ ys333Glu │
│ 3095      ┆ 71001     ┆ 205675    ┆ VUSAPWT2B ┆ … ┆ 1_Pathoge ┆ null      ┆ 1.0       ┆ UBQLN2_P │
│           ┆           ┆           ┆ 1         ┆   ┆ nic       ┆           ┆           ┆ ro506Thr │
│ 6490      ┆ 2920      ┆ 214424    ┆ VUSAPWT2B ┆ … ┆ 5_Others  ┆ null      ┆ null      ┆ GFAP_Lys │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆ 236Thr   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 6811      ┆ 4723      ┆ 201740    ┆ VUSAPWT1B ┆ … ┆ 4_VUS     ┆ 0.000003  ┆ 2.0       ┆ TPM1_Ile │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆ 172Thr   │
│ 11132     ┆ 52920     ┆ 2689      ┆ VUSAPWT1B ┆ … ┆ 3_Conflic ┆ null      ┆ 1.0       ┆ LITAF_Se │
│           ┆           ┆           ┆ 1         ┆   ┆ ting      ┆           ┆           ┆ r15Leu   │
│ 1969      ┆ 513       ┆ 213753    ┆ VUSAPWT6B ┆ … ┆ 3_Conflic ┆ null      ┆ 1.0       ┆ FA2H_Arg │
│           ┆           ┆           ┆ 1         ┆   ┆ ting      ┆           ┆           ┆ 143Cys   │
│ 54668     ┆ 71337     ┆ 3957      ┆ VUSAPWT1B ┆ … ┆ 4_VUS     ┆ 0.000047  ┆ 2.0       ┆ ACSF3_As │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆ p457Asn  │
│ 100016069 ┆ 100016069 ┆ 2646      ┆ VUSAPWT1B ┆ … ┆ 1_Pathoge ┆ null      ┆ null      ┆ KCNJ2_Va │
│           ┆           ┆           ┆ 1         ┆   ┆ nic       ┆           ┆           ┆ l302Met  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [51]:
scores_pd = scores.to_pandas()
scores_pd[
    (scores_pd.ad_orf_id == '12626.0') &
    (scores_pd.db_orf_id == '9905.0') #&
    # (scores_pd.db_mut_id == 215290)
    ]

Empty DataFrame
Columns: [ad_orf_id, db_orf_id, db_mut_id, retest_batch, normalized_score, assay_id, seq_ad, seq_db, db_sequenced, db_sequence_confirmation_class, ad_symbol, symbol, aa_change, nt_change, ensembl_gene_id, collection, clinvar_clnsig_clean, gnomad_af, StarStatus, allele_0]
Index: []

In [52]:
scores = pl.read_csv(f"{outputs_dir}/4_normalized_consensus_scores.csv")

# keep only scores where there is at least one matched reference-variant set
orfs_with_alleles = scores.filter(pl.col("db_mut_id") != 0).select("db_orf_id").unique().to_series().to_list()
orfs = scores.filter(pl.col("db_mut_id") == 0).select("db_orf_id").unique().to_series().to_list()

complete_orf_pairs = [i for i in orfs if i in orfs_with_alleles]
scores = scores.filter(pl.col("db_orf_id").is_in(complete_orf_pairs))
genes = scores.select("db_orf_id").to_series().unique().to_list()

# print(scores)

In [53]:
# Create profiles for each profiled gene

profiles = {}
shape_summary = []
for gene in genes:
    gene_scores = scores.filter(pl.col("db_orf_id") == gene)
    profile = gene_scores.pivot(
                values="normalized_score",
                index="ad_orf_id",
                on="db_mut_id"
            )
    profiles[gene] = profile

    shape_summary.append({
        "gene": gene,
        "n_interactors": profile.height,
        "n_alleles": profile.width
    })

    profile.write_csv(f"{outputs_dir}/edgotype_profiles/manual/orf_id_{gene}.csv")

shape_summary = pl.DataFrame(shape_summary)

In [54]:
## Add a perturbation category for each edge to use for the N2H validation

# Extract WT scores
wt_scores = scores.filter(pl.col("db_mut_id") == 0).select(["db_orf_id", "ad_orf_id", "normalized_score"])

# Merge WT scores back onto the main df
scores_with_wt = scores.join(wt_scores, on=["db_orf_id", "ad_orf_id"], how="left", suffix="_wt")

# Compute allele/WT ratio
scores_with_wt = scores_with_wt.with_columns(
    (pl.col("normalized_score") / pl.col("normalized_score_wt")).alias("ratio")
)

# Determine if the allele is perturbed - binary output
threshold = 0.5
scores_with_wt = scores_with_wt.with_columns(
    ((pl.col("db_mut_id") != 0) & (pl.col("ratio") < threshold)).alias("perturbed")
)

# Build perturbation_classes expression
bins = [
    (1.0, float("inf"), "increased edge"),
    (0.8, 1.0, "similar"),
    (0.6, 0.8, "slightly perturbed"),
    (0.4, 0.6, "perturbed"),
    (0.2, 0.4, "highly perturbed"),
    (0.0, 0.2, "very highly perturbed"),
]

perturbation_expr = pl.when(pl.col("db_mut_id") == 0).then(pl.lit("WT"))

perturbation_expr = perturbation_expr.when(pl.col("normalized_score_wt") == 0.0).then(pl.lit("WT edge lost"))

perturbation_expr = perturbation_expr.when(pl.col("ratio") == 0.0).then(pl.lit("edge lost"))

perturbation_expr = perturbation_expr.when(pl.col("ratio") == 1.0).then(pl.lit("WT-like"))

for lower, upper, label in bins:
    perturbation_expr = perturbation_expr.when((pl.col("ratio") > lower) & (pl.col("ratio") <= upper)).then(pl.lit(label))


perturbation_expr = perturbation_expr.otherwise(pl.lit("unclassified"))




scores_with_wt = scores_with_wt.with_columns(
    perturbation_expr.alias("perturbation_classes")
)

scores_with_perturbed = scores_with_wt.select("*")


pert2 = (pl.when(pl.col("db_mut_id") == 0).then(pl.lit('WT')))

pert2 = pert2.when(pl.col("normalized_score_wt") == 0.0).then(pl.lit("WT edge lost"))

pert2 = pert2.when(pl.col("ratio") == 0.0).then(pl.lit("edge lost"))

pert2 = pert2.when(pl.col("ratio") == 1.0).then(pl.lit("WT-like"))

bins_2 = [
    (float("inf"), 1.0, "increased edge"),
    (1, 0.7, 'slightly perturbed'),
    (0.7, 0.3, 'perturbed'),
    (0.3, 0, 'highly perturbed')
]

for upper, lower, label in bins_2:
    pert2 = pert2.when(
        (pl.col("ratio") <= upper) &
        (pl.col("ratio") >  lower)
    ).then(pl.lit(label))

pert2 = pert2.otherwise(pl.lit("unclassified"))

scores_with_perturbed = scores_with_wt.with_columns(
    perturbation_classes_2 = pert2.alias("perturbation_classes_2")
)



cols_to_keep = ['ad_orf_id',
 'db_orf_id',
 'db_mut_id',
 'normalized_score',
 'ad_symbol',
 'symbol',
 'clinvar_clnsig_clean',
 'normalized_score_wt',
 'ratio',
 'perturbed',
 'perturbation_classes',
 "perturbation_classes_2"]

scores_with_perturbed = scores_with_perturbed.select(cols_to_keep)

scores_with_perturbed.write_csv(f"{outputs_dir}/7_edge_perturbation_categorical.csv")

## Examine profile characteristics

In [55]:
# Number of profiled alleles with more than 5 interactors
hq_orfs = shape_summary.filter(pl.col("n_interactors") >= 5)
num_orfs = hq_orfs.shape[0]
print(num_orfs)

print(hq_orfs.select(pl.col("n_alleles")).sum() - num_orfs)

25
shape: (1, 1)
┌───────────┐
│ n_alleles │
│ ---       │
│ i64       │
╞═══════════╡
│ 255       │
└───────────┘

In [56]:
# Total number of profiled alleles
prof_genes = shape_summary.shape[0]
print(prof_genes)

print(shape_summary.select(pl.col("n_alleles")).sum() - prof_genes)

84
shape: (1, 1)
┌───────────┐
│ n_alleles │
│ ---       │
│ i64       │
╞═══════════╡
│ 659       │
└───────────┘

# Automated

In [57]:
scores = pl.read_csv(f"{outputs_dir}/4_automated_normalized_consensus_scores.csv")
scores = scores.drop_nulls(subset=["normalized_score"])

# keep only scores where there is at least one matched reference-variant set
orfs_with_alleles = scores.filter(pl.col("db_mut_id") != 0).select("db_orf_id").unique().to_series().to_list()
orfs = scores.filter(pl.col("db_mut_id") == 0).select("db_orf_id").unique().to_series().to_list()

complete_orf_pairs = [i for i in orfs if i in orfs_with_alleles]
scores = scores.filter(pl.col("db_orf_id").is_in(complete_orf_pairs))
genes = scores.select("db_orf_id").to_series().unique().to_list()

scores

shape: (2_729, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ad_orf_id ┆ db_orf_id ┆ db_mut_id ┆ retest_ba ┆ … ┆ clinvar_c ┆ gnomad_af ┆ StarStatu ┆ allele_0 │
│ ---       ┆ ---       ┆ ---       ┆ tch       ┆   ┆ lnsig_cle ┆ ---       ┆ s         ┆ ---      │
│ i64       ┆ i64       ┆ i64       ┆ ---       ┆   ┆ an        ┆ f64       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆ ---       ┆           ┆ f64       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4761      ┆ 2713      ┆ 0         ┆ VUSAPWT1B ┆ … ┆ null      ┆ null      ┆ null      ┆ MLH1     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 100009072 ┆ 70368     ┆ 205543    ┆ VUSAPWT1B ┆ … ┆ 1_Pathoge ┆ null      ┆ null      ┆ KCTD7_As │
│           ┆           ┆           ┆ 2         ┆   ┆ nic       ┆           ┆           ┆ p115Tyr  │
│ 71001     ┆ 52920     ┆ 2677      ┆ VUSAPWT1B ┆ … ┆ 1_Pathoge ┆ null      ┆ 2.0       ┆ LITAF_Gl │
│           ┆           ┆           ┆ 1         ┆   ┆ nic       ┆           ┆           ┆ y112Ser  │
│ 10064     ┆ 52920     ┆ 2677      ┆ VUSAPWT2B ┆ … ┆ 1_Pathoge ┆ null      ┆ 2.0       ┆ LITAF_Gl │
│           ┆           ┆           ┆ 1         ┆   ┆ nic       ┆           ┆           ┆ y112Ser  │
│ 100016069 ┆ 100016069 ┆ 2630      ┆ VUSAPWT1B ┆ … ┆ 1_Pathoge ┆ null      ┆ null      ┆ KCNJ2_As │
│           ┆           ┆           ┆ 1         ┆   ┆ nic       ┆           ┆           ┆ n216His  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 4519      ┆ 3449      ┆ 0         ┆ VUSAPWT1B ┆ … ┆ null      ┆ null      ┆ null      ┆ GMPPB    │
│           ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 11830     ┆ 7675      ┆ 202588    ┆ VUSAPWT2B ┆ … ┆ 1_Pathoge ┆ null      ┆ null      ┆ NMNAT1_A │
│           ┆           ┆           ┆ 1         ┆   ┆ nic       ┆           ┆           ┆ rg237Leu │
│ 100070143 ┆ 3535      ┆ 6159      ┆ VUSAPWT1B ┆ … ┆ 1_Pathoge ┆ 9.1558e-7 ┆ 1.0       ┆ EMD_Ser5 │
│           ┆           ┆           ┆ 1         ┆   ┆ nic       ┆           ┆           ┆ 4Phe     │
│ 8186      ┆ 4062      ┆ 201430    ┆ VUSAPWT2B ┆ … ┆ 1_Pathoge ┆ 0.0       ┆ 1.0       ┆ PLP1_Cys │
│           ┆           ┆           ┆ 1         ┆   ┆ nic       ┆           ┆           ┆ 193Tyr   │
│ 10471     ┆ 5442      ┆ 215414    ┆ VUSAPWT1B ┆ … ┆ 5_Others  ┆ null      ┆ null      ┆ SIX1_Val │
│           ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆ 106Gly   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [58]:
# Create profiles for each profiled gene

profiles = {}
shape_summary = []
for gene in genes:
    gene_scores = scores.filter(pl.col("db_orf_id") == gene)
    profile = gene_scores.pivot(
                values="normalized_score",
                index="ad_orf_id",
                on="db_mut_id"
            )
    profiles[gene] = profile

    shape_summary.append({
        "gene": gene,
        "n_interactors": profile.height,
        "n_alleles": profile.width
    })

    profile.write_csv(f"{outputs_dir}/edgotype_profiles/auto_norm/orf_id_{gene}_auto_normalized.csv")

shape_summary = pl.DataFrame(shape_summary)

In [59]:
# Create profiles for each profiled gene

profiles = {}
shape_summary = []
for gene in genes:
    gene_scores = scores.filter(pl.col("db_orf_id") == gene)
    profile = gene_scores.pivot(
                values="adjusted_score",
                index="ad_orf_id",
                on="db_mut_id"
            )
    profiles[gene] = profile

    shape_summary.append({
        "gene": gene,
        "n_interactors": profile.height,
        "n_alleles": profile.width
    })

    profile.write_csv(f"{outputs_dir}/edgotype_profiles/auto_summed/orf_id_{gene}_auto_summed.csv")

shape_summary = pl.DataFrame(shape_summary)