# Create files mapping FACS well and plate to basic allele metadata

This script takes cherry picking and allele info files as input and produces a table relating FACS well and plate IDs to allele IDs and symbols.

In [1]:
import pandas as pd
import polars as pl
import numpy as np
import os

In [2]:
dualipa_inputs = "../1_inputs"
dualipa_outputs = "../3_outputs"
allele_collection_inputs = "../../../1_allele_collection/1_inputs/seq_confirmation_results"
allele_collection_outputs = "../../../1_allele_collection/3_outputs"

## 1. Loading the pdest layout data frame

Vidal lab ran experiment once and analyzed the data. Some alleles didn't pass the qa/qc thresholds or got no data. Batch5 is is a re-run for all alleles that failed in the first set of batches. Here, we process everything together from scratch. An allele should always be compared to the wt on the same batch and plate. The summary stats can then be compared across batches.

In [3]:
# Read in cherry picking files for both the initial batches and the second round
cp_col = ['orf_id', 'mut_id', 'node_type','dest_pla_id', 'dest_pla', 'dest_well']

pdest_layout_initial_batches_df = pd.read_csv(f'{dualipa_inputs}/cherry_picking_files/summary_CP_VUSDUALXP.csv', index_col=0)[cp_col]
pdest_layout_b5_df = pd.read_csv(f'{dualipa_inputs}/cherry_picking_files/summary_CP_VUSDUALXP_batch5.csv', index_col=0)[cp_col]

pdest_layout_df = pd.concat([pdest_layout_b5_df, pdest_layout_initial_batches_df])
pdest_layout_df = pl.DataFrame(pdest_layout_df)
pdest_layout_df = pdest_layout_df.with_columns(
    pl.col("orf_id").cast(pl.Int64).alias("orf_id"),
    pl.col("mut_id").cast(pl.Int64).alias("mut_id")
)
pdest_layout_df
### This doesn't have well A01

shape: (2_311, 6)
┌────────┬────────┬─────────────┬─────────────┬──────────────┬───────────┐
│ orf_id ┆ mut_id ┆ node_type   ┆ dest_pla_id ┆ dest_pla     ┆ dest_well │
│ ---    ┆ ---    ┆ ---         ┆ ---         ┆ ---          ┆ ---       │
│ i64    ┆ i64    ┆ str         ┆ i64         ┆ str          ┆ str       │
╞════════╪════════╪═════════════╪═════════════╪══════════════╪═══════════╡
│ 56360  ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ A12       │
│ 56360  ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ B12       │
│ 56360  ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ C12       │
│ 56360  ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ D12       │
│ 9905   ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ F02       │
│ …      ┆ …      ┆ …           ┆ …           ┆ …            ┆ …         │
│ null   ┆ null   ┆ pdest_empty ┆ 20          ┆ VUSDUALXP_20 ┆ A08       │
│ null   ┆ null   ┆ pdest_empty ┆ 21          ┆ VUSDUALXP_21 ┆ A07       │
│ null   ┆ null   ┆ pdest_empty ┆ 21          ┆ VUSDUALXP_21 ┆ A08       │
│ null   ┆ null   ┆ pdest_empty ┆ 22          ┆ VUSDUALXP_22 ┆ A07       │
│ null   ┆ null   ┆ pdest_empty ┆ 22          ┆ VUSDUALXP_22 ┆ A08       │
└────────┴────────┴─────────────┴─────────────┴──────────────┴───────────┘

In [4]:
pdest_layout_df.filter((pl.col("dest_pla_id")==18)&(pl.col("dest_well")=="E11"))

shape: (1, 6)
┌────────┬────────┬───────────┬─────────────┬──────────────┬───────────┐
│ orf_id ┆ mut_id ┆ node_type ┆ dest_pla_id ┆ dest_pla     ┆ dest_well │
│ ---    ┆ ---    ┆ ---       ┆ ---         ┆ ---          ┆ ---       │
│ i64    ┆ i64    ┆ str       ┆ i64         ┆ str          ┆ str       │
╞════════╪════════╪═══════════╪═════════════╪══════════════╪═══════════╡
│ 3438   ┆ 201180 ┆ allele    ┆ 18          ┆ VUSDUALXP_18 ┆ E11       │
└────────┴────────┴───────────┴─────────────┴──────────────┴───────────┘

## 2. Loading the sequence confirmed results

In [5]:
seq_confirm_code_df = pd.read_table(f"{allele_collection_inputs}/sequence_confirmation_class_code.tsv")
with pd.option_context('display.max_columns', None):
    display(seq_confirm_code_df)

   code                                      description
0     1                              perfectly validated
1     2             partially validated, >= 50% coverage
2     3                                        wild type
3     4               partial wild type, >= 50% coverage
4     5  target and off-target mutation, >= 50% coverage
5     6             off-target mutation, >= 50% coverage
6     7                        truncated, < 50% coverage
7    99                                         no reads

In [8]:
seq_confirm_res_df = pl.read_parquet(
    f"{allele_collection_outputs}/VarChAMP_Allele_Collection_1Perc_ClinVar_dbNSFP_pLDDT_RSA_G2P_OMIM_MOI.parquet"
).with_columns(
    pl.col("mut_id").cast(pl.Int64).alias("mut_id")
)

with pl.Config(set_tbl_cols=100):
    display(seq_confirm_res_df)

shape: (9_599, 1_005)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬───┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sym ┆ ens ┆ orf ┆ mut ┆ ccs ┆ ccs ┆ spd ┆ nt_ ┆ aa_ ┆ seq ┆ seq ┆ col ┆ ent ┆ ent ┆ ent ┆ ent ┆ ent ┆ db_ ┆ db_ ┆ n2h ┆ n2h ┆ dua ┆ dua ┆ mis ┆ mis ┆ ent ┆ ent ┆ db_ ┆ db_ ┆ n2h ┆ n2h ┆ n2h ┆ dua ┆ dua ┆ dua ┆ mis ┆ mis ┆ mis ┆ chr ┆ nuc ┆ ref ┆ alt ┆ Chr ┆ ent ┆ db_ ┆ n2h ┆ dua ┆ mis ┆ gen ┆ #Al ┆ … ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ g2p ┆ OMI ┆ inh ┆ inh ┆ dis ┆ dis ┆ OMI │
│ bol ┆ emb ┆ _id ┆ _id ┆ b_m ┆ b_a ┆ i   ┆ cha ┆ cha ┆ --- ┆ _aa ┆ lec ┆ ry_ ┆ ry_ ┆ ry_ ┆ ry_ ┆ ry_ ┆ pla ┆ wel ┆ _pl ┆ _we ┆ lip ┆ lip ┆ loc ┆ loc ┆ ry_ ┆ ry_ ┆ seq ┆ seq ┆ _se ┆ _se ┆ _re ┆ lip ┆ lip ┆ lip ┆ loc ┆ loc ┆ loc ┆ _nu ┆ _lo ┆ _al ┆ _al ┆ om  ┆ ry_ ┆ seq ┆ _se ┆ lip ┆ loc ┆ e_v ┆ lel ┆   ┆ _In ┆ _In ┆ _In ┆ _In ┆ _In ┆ _In ┆ _In ┆ _In ┆ _In ┆ _Li ┆ _Me ┆ _Mo ┆ _Mo ┆ _Mo ┆ _Mu ┆ _No ┆ _No ┆ _No ┆ _O- ┆ _O- ┆ _Pe ┆ _Ph ┆ _Ph ┆ _Po ┆ _Pr ┆ _Ps ┆ _Re ┆ _Re ┆ _Re ┆ _SN ┆ _SU ┆ _Se ┆ _Se ┆ _Se ┆ _Se ┆ _Se ┆ _Si ┆ _Si ┆ _Su ┆ _To ┆ _Tr ┆ _Tr ┆ _Ub ┆ _Zi ┆ M_I ┆ eri ┆ eri ┆ eas ┆ eas ┆ M_d │
│ --- ┆ l_g ┆ --- ┆ --- ┆ uta ┆ lle ┆ --- ┆ nge ┆ nge ┆ str ┆ --- ┆ tio ┆ pla ┆ wel ┆ pla ┆ wel ┆ seq ┆ te  ┆ l   ┆ ate ┆ ll  ┆ _pl ┆ _we ┆ ali ┆ ali ┆ seq ┆ seq ┆ uen ┆ uen ┆ que ┆ que ┆ f_s ┆ _se ┆ _se ┆ _re ┆ ali ┆ ali ┆ ali ┆ m   ┆ c   ┆ lel ┆ lel ┆ --- ┆ seq ┆ _fi ┆ q_f ┆ _se ┆ ali ┆ ari ┆ eID ┆   ┆ tra ┆ tra ┆ tra ┆ tra ┆ tra ┆ tra ┆ tra ┆ tra ┆ tra ┆ pid ┆ thy ┆ dif ┆ lar ┆ tif ┆ tag ┆ n-a ┆ n-s ┆ n-t ┆ Gal ┆ Glc ┆ pti ┆ i   ┆ osp ┆ cke ┆ ope ┆ i   ┆ gio ┆ gul ┆ pea ┆ P-a ┆ MOy ┆ con ┆ con ┆ con ┆ que ┆ que ┆ gna ┆ te  ┆ bst ┆ pol ┆ ans ┆ ans ┆ iqu ┆ nc  ┆ Ds  ┆ tan ┆ tan ┆ e_m ┆ e_m ┆ ise │
│ str ┆ ene ┆ i64 ┆ i64 ┆ tio ┆ le_ ┆ str ┆ --- ┆ --- ┆     ┆ str ┆ n   ┆ te_ ┆ l_o ┆ te_ ┆ l_c ┆ _po ┆ --- ┆ --- ┆ --- ┆ --- ┆ ate ┆ ll  ┆ zat ┆ zat ┆ uen ┆ uen ┆ ced ┆ ce_ ┆ nce ┆ nce ┆ equ ┆ que ┆ que ┆ f_s ┆ zat ┆ zat ┆ zat ┆ --- ┆ --- ┆ e   ┆ e   ┆ str ┆ _fi ┆ nal ┆ ina ┆ q_f ┆ zat ┆ ant ┆ --- ┆   ┆ -ch ┆ -ch ┆ -ch ┆ -ch ┆ -ch ┆ -ch ┆ -ch ┆ -ch ┆ mem ┆ ati ┆ lat ┆ ied ┆ mas ┆ (Un ┆ ene ┆ dja ┆ tan ┆ erm ┆ NAc ┆ NAc ┆ de  ┆ ang ┆ hor ┆ t   ┆ pti ┆ ang ┆ n   ┆ ato ┆ t   ┆ sso ┆ lat ┆ dar ┆ dar ┆ dar ┆ nce ┆ nce ┆ l   ┆ (Un ┆ rat ┆ ogi ┆ it  ┆ mem ┆ iti ┆ fin ┆ --- ┆ ce_ ┆ ce_ ┆ odu ┆ odu ┆ ase │
│     ┆ _id ┆     ┆     ┆ n_i ┆ id  ┆     ┆ str ┆ str ┆     ┆     ┆ --- ┆ ori ┆ rig ┆ con ┆ ons ┆ ol  ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ ion ┆ ion ┆ ced ┆ ce_ ┆ --- ┆ con ┆ d   ┆ _co ┆ enc ┆ nce ┆ nce ┆ equ ┆ ion ┆ ion ┆ ion ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆ nal ┆ --- ┆ l   ┆ ina ┆ ion ┆ --- ┆ f64 ┆   ┆ ain ┆ ain ┆ ain ┆ ain ┆ ain ┆ ain ┆ ain ┆ ain ┆ bra ┆ on  ┆ ion ┆ res ┆ s   ┆ iPr ┆ sis ┆ cen ┆ dar ┆ ina ┆ --- ┆ --- ┆ (Un ┆ le  ┆ yla ┆ num ┆ de  ┆ le  ┆ (Un ┆ ry  ┆ (Un ┆ cia ┆ ion ┆ y   ┆ y   ┆ y   ┆ con ┆ unc ┆ (Un ┆ iPr ┆ e   ┆ cal ┆ pep ┆ bra ┆ nat ┆ ger ┆ lis ┆ pat ┆ sou ┆ les ┆ le_ ┆ _na │
│     ┆ --- ┆     ┆     ┆ d   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ g   ┆ --- ┆ so  ┆ o   ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ _pl ┆ _we ┆ --- ┆ con ┆ f64 ┆ fir ┆ --- ┆ nfi ┆ e_c ┆ d   ┆ _co ┆ enc ┆ _se ┆ _se ┆ _re ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆ --- ┆ l   ┆ _se ┆ str ┆     ┆   ┆ Dis ┆ Dis ┆ Hyd ┆ Hyd ┆ Non ┆ Non ┆ Sal ┆ Sal ┆ ne  ┆ (Un ┆ --- ┆ idu ┆ (g/ ┆ ot) ┆ (Un ┆ t   ┆ d   ┆ l   ┆ str ┆ str ┆ iPr ┆ (de ┆ tio ┆ ber ┆ (Un ┆ (de ┆ iPr ┆ sit ┆ iPr ┆ ted ┆ --- ┆ str ┆ str ┆ str ┆ fli ┆ ert ┆ iPr ┆ ot) ┆ gen ┆ dom ┆ tid ┆ ne  ┆ ion ┆ (Un ┆ t[s ┆ ter ┆ rce ┆ --- ┆ cou ┆ mes │
│     ┆ str ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ --- ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆ ll  ┆ f64 ┆ fir ┆     ┆ mat ┆ f64 ┆ rma ┆ onf ┆ --- ┆ nfi ┆ e_c ┆ que ┆ que ┆ f_s ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ --- ┆ q_f ┆     ┆     ┆   ┆ ulf ┆ ulf ┆ rog ┆ rog ┆ -bo ┆ -bo ┆ t   ┆ t   ┆ (Un ┆ iPr ┆ str ┆ e   ┆ mol ┆ --- ┆ iPr ┆ res ┆ res ┆ res ┆     ┆     ┆ ot) ┆ gre ┆ n   ┆ (fp ┆ iPr ┆ gre ┆ ot) ┆ es  ┆ ot) ┆ PTM ┆ str ┆ uct ┆ uct ┆ uct ┆ ct  ┆ ain ┆ ot) ┆ --- ┆ es  ┆ ain ┆ e   ┆ (Un ┆ --- ┆ iPr ┆ tr] ┆ n   ┆ --- ┆ str ┆ nt  ┆ --- │
│     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ mat ┆     ┆ ion ┆     ┆ tio ┆ irm ┆ f64 ┆ rma ┆ onf ┆ nce ┆ nce ┆ equ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ ina ┆     ┆     ┆   ┆ ide ┆ ide ┆ en  ┆ en  ┆ nde ┆ nde ┆ bri ┆ bri ┆ iPr ┆ ot) ┆     ┆ (Un ┆ )   ┆ str ┆ ot) ┆ idu ┆ idu ┆ idu ┆     ┆     ┆ --- ┆ es) ┆ --- ┆ ock ┆ ot) ┆ es) ┆ --- ┆ --- ┆ --- ┆ s   ┆     ┆ ure ┆ ure ┆ ure ┆ (Un ┆ ty  ┆ --- ┆ str ┆ --- ┆ (Un ┆ (Un ┆ iPr ┆ str ┆ ot) ┆     ┆ --- ┆ str ┆     ┆ --- ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ion ┆     ┆ _cl ┆     ┆ n_c ┆ ati ┆     ┆ tio ┆ irm ┆ d   ┆ _co ┆ enc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆   ┆ bon ┆ bon ┆ bon ┆ bon ┆ d   ┆ d   ┆ dge ┆ dge ┆ ot) ┆ --- ┆     ┆ iPr ┆ --- ┆     ┆ --- ┆ es  ┆ e   ┆ e   ┆     ┆     ┆ str ┆ *   ┆ str ┆ et) ┆ --- ┆ *   ┆ str ┆ str ┆ str ┆ --- ┆     ┆ (DS ┆ (DS ┆ (PD ┆ iPr ┆ (Un ┆ str ┆     ┆ str ┆ iPr ┆ iPr ┆ ot) ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ i64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _cl ┆     ┆ ass ┆     ┆ las ┆ on_ ┆     ┆ n_c ┆ ati ┆ --- ┆ nfi ┆ e_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆   ┆ d…  ┆ d…  ┆ d … ┆ d … ┆ int ┆ int ┆ (A… ┆ (P… ┆ --- ┆ str ┆     ┆ ot) ┆ str ┆     ┆ str ┆ (Un ┆ (Un ┆ (Un ┆     ┆     ┆     ┆ --- ┆     ┆ *   ┆ str ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆ SP  ┆ SP  ┆ Be/ ┆ ot… ┆ iP… ┆     ┆     ┆     ┆ o…  ┆ ot) ┆ --- ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ --- ┆     ┆ …   ┆ …   ┆     ┆ …   ┆ …   ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆   ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ --- ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ i…  ┆ iP… ┆ iP… ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═══╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ GBA ┆ ENS ┆ 2   ┆ 6   ┆ CCS ┆ ALE ┆ NC_ ┆ 160 ┆ Val ┆ ATG ┆ MEF ┆ RC4 ┆ RC4 ┆ H01 ┆ GDE ┆ F12 ┆ 2   ┆ RC4 ┆ H01 ┆ NUL ┆ NUL ┆ NUL ┆ NUL ┆ NUL ┆ NUL ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 2.0 ┆ 0.0 ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 1.0 ┆ 1.5 ┆ C   ┆ G   ┆ 1   ┆ Y   ┆ Y   ┆ N   ┆ N   ┆ N   ┆ GBA ┆ nul ┆ … ┆     ┆     ┆ V54 ┆ V54 ┆ V54 ┆ V54 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -86 ┆     ┆     ┆     ┆ 160 ┆     ┆     ┆     ┆     ┆     ┆ B   ┆ E   ┆ Bet ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0   ┆ nul │
│ 1   ┆ G00 ┆     ┆     ┆ BVa ┆ 000 ┆ 000 ┆ G>C ┆ 54L ┆ GAG ┆ SSP ┆     ┆ _Mu ┆     ┆ hDi ┆     ┆     ┆ _Mu ┆     ┆ L   ┆ L   ┆ L   ┆ L   ┆ L   ┆ L   ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     ┆ 524 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_V ┆ l   ┆   ┆     ┆     ┆ -K4 ┆ -K4 ┆ -G3 ┆ -K4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .4  ┆     ┆     ┆     ┆ .1  ┆     ┆     ┆     ┆     ┆     ┆ (un ┆ (pa ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   │
│     ┆ 000 ┆     ┆     ┆ rC0 ┆ 058 ┆ 001 ┆     ┆ eu  ┆ TTT ┆ SRE ┆     ┆ t_G ┆     ┆ sVC ┆     ┆     ┆ t_G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 003 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al5 ┆     ┆   ┆     ┆     ┆ 6   ┆ 6   ┆ 94  ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ def ┆ ral ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 177 ┆     ┆     ┆ 000 ┆ 4   ┆ .11 ┆     ┆     ┆ TCA ┆ ECP ┆     ┆ DEh ┆     ┆ h_4 ┆     ┆     ┆ DDh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3e8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4Le ┆     ┆   ┆     ┆     ┆ (PA ┆ (PD ┆ (PA ┆ (PD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ine ┆ lel ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 628 ┆     ┆     ┆ 01  ┆     ┆ :15 ┆     ┆     ┆ AGT ┆ KPL ┆     ┆ 102 ┆     ┆ 005 ┆     ┆     ┆ 102 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆   ┆     ┆     ┆ E:  ┆ Bs: ┆ E:  ┆ Bs: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d)  ┆ she ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 524 ┆     ┆     ┆ CCT ┆ SRV ┆     ┆ 6   ┆     ┆ 4   ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆ 1.0 ┆ 1OG ┆ 1.0 ┆ 1OG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ets ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 003 ┆     ┆     ┆ TCC ┆ SIM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆ )   ┆ S,  ┆ ),  ┆ S,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 3:C ┆     ┆     ┆ AGA ┆ AGS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆ 2J2 ┆ V54 ┆ 2J2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ :G  ┆     ┆     ┆ GAG ┆ LTG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆ 5,  ┆ -K4 ┆ 5,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GAA ┆ LLL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆ 2NS ┆ 6…  ┆ 2NS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ GBA ┆ ENS ┆ 2   ┆ 73  ┆ CCS ┆ ALE ┆ NC_ ┆ 670 ┆ Leu ┆ ATG ┆ MEF ┆ RC4 ┆ RC4 ┆ E01 ┆ GDE ┆ C12 ┆ 2   ┆ RC4 ┆ E01 ┆ NUL ┆ NUL ┆ NUL ┆ NUL ┆ NUL ┆ NUL ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 1.0 ┆ 1.5 ┆ G   ┆ A   ┆ 1   ┆ Y   ┆ Y   ┆ N   ┆ N   ┆ N   ┆ GBA ┆ nul ┆ … ┆     ┆     ┆ L22 ┆ L22 ┆ L22 ┆ L22 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 131 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -79 ┆     ┆     ┆     ┆ -11 ┆     ┆     ┆     ┆     ┆     ┆ H   ┆ G   ┆ Hel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0   ┆ nul │
│ 1   ┆ G00 ┆     ┆     ┆ BVa ┆ 000 ┆ 000 ┆ C>T ┆ 224 ┆ GAG ┆ SSP ┆     ┆ _Mu ┆     ┆ hDi ┆     ┆     ┆ _Mu ┆     ┆ L   ┆ L   ┆ L   ┆ L   ┆ L   ┆ L   ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     ┆ 523 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_L ┆ l   ┆   ┆     ┆     ┆ 4-K ┆ 4-K ┆ 4-K ┆ 4-K ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .7  ┆     ┆     ┆     ┆ .9  ┆     ┆     ┆     ┆     ┆     ┆ (he ┆ (3₁ ┆ ix  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   │
│     ┆ 000 ┆     ┆     ┆ rC0 ┆ 000 ┆ 001 ┆     ┆ Phe ┆ TTT ┆ SRE ┆     ┆ t_G ┆     ┆ sVC ┆     ┆     ┆ t_G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 822 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eu2 ┆     ┆   ┆     ┆     ┆ 237 ┆ 237 ┆ 237 ┆ 237 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lix ┆ ₀-h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 177 ┆     ┆     ┆ 000 ┆ 02  ┆ .11 ┆     ┆     ┆ TCA ┆ ECP ┆     ┆ DEh ┆     ┆ h_4 ┆     ┆     ┆ DDh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5e8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 24P ┆     ┆   ┆     ┆     ┆ (PA ┆ (PD ┆ (PA ┆ (PD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆ eli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 628 ┆     ┆     ┆ 02  ┆     ┆ :15 ┆     ┆     ┆ AGT ┆ KPL ┆     ┆ 102 ┆     ┆ 005 ┆     ┆     ┆ 102 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ he  ┆     ┆   ┆     ┆     ┆ E:  ┆ Bs: ┆ E:  ┆ Bs: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ x)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 523 ┆     ┆     ┆ CCT ┆ SRV ┆     ┆ 6   ┆     ┆ 4   ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆ 1.0 ┆ 1OG ┆ 1.0 ┆ 1OG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

## 3. Map the pdest mutation to meta mutation information

In [9]:
# seq_confirm_res_df.filter(pl.col("mut_id")==0)

## map orf_id to symbol and ensembl_gene_id
orfid_2_symbol_mapping = dict(zip(
    seq_confirm_res_df.filter(pl.col("symbol").is_not_null())["orf_id"].to_list(),
    seq_confirm_res_df.filter(pl.col("symbol").is_not_null())["symbol"].to_list()
))

orfid_2_geneid_mapping = dict(zip(
    seq_confirm_res_df.filter(pl.col("ensembl_gene_id").is_not_null())["orf_id"].to_list(),
    seq_confirm_res_df.filter(pl.col("ensembl_gene_id").is_not_null())["ensembl_gene_id"].to_list()
))

In [10]:
## join the pdest variant with mut meta info by "INNER" JOIN;
## some alleles were filtered out during the allele collection stage due to their poor seq quality
## SHOULD REMOVE them from DUAL-IPA assay
pdest_layout_seq_conf_mut_df = pdest_layout_df.filter(
    pl.col("mut_id")!=0
).join(
    seq_confirm_res_df, 
    on=["orf_id", "mut_id"],
    how="inner"
)

## need to add wt data here as well
pdest_layout_seq_conf_wt_df = pdest_layout_df.filter(
    pl.col("mut_id")==0
).join(
    seq_confirm_res_df, 
    on=["orf_id", "mut_id"],
    how="left"
).with_columns(
    pl.col("aa_change").fill_null("WT"),
    pl.col("nt_change").fill_null("WT"),
    pl.col("orf_id").map_elements(lambda x: orfid_2_symbol_mapping[x] if x in orfid_2_symbol_mapping else pl.Null, return_dtype=pl.String).alias("symbol"),
    pl.col("orf_id").map_elements(lambda x: orfid_2_geneid_mapping[x] if x in orfid_2_geneid_mapping else pl.Null, return_dtype=pl.String).alias("ensembl_gene_id")
)

## need to add the pdest_empty wells as well
pdest_layout_seq_conf_empty_df = pdest_layout_df.filter(
    pl.col("mut_id").is_null()
).join(
    seq_confirm_res_df, 
    on=["orf_id", "mut_id"],
    how="left"
)

## concat var and wt and empty
pdest_layout_seq_conf_df = pl.concat([
    pdest_layout_seq_conf_mut_df, pdest_layout_seq_conf_wt_df, pdest_layout_seq_conf_empty_df
])
print(pdest_layout_seq_conf_df["dualip_sequence_confirmation_class"].unique())

shape: (9,)
Series: 'dualip_sequence_confirmation_class' [f64]
[
	null
	1.0
	2.0
	3.0
	4.0
	5.0
	6.0
	7.0
	99.0
]

In [11]:
pdest_layout_seq_conf_df.unique(subset="dualip_seq_final")["dualip_seq_final"]

shape: (3,)
Series: 'dualip_seq_final' [str]
[
	null
	"Y"
	"N"
]

In [13]:
pdest_layout_seq_conf_df

shape: (2_621, 1_009)
┌────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ orf_id ┆ mut_id ┆ node_type  ┆ dest_pla_i ┆ … ┆ inheritanc ┆ disease_mo ┆ disease_mo ┆ OMIM_dise │
│ ---    ┆ ---    ┆ ---        ┆ d          ┆   ┆ e_source   ┆ dules      ┆ dule_count ┆ ase_names │
│ i64    ┆ i64    ┆ str        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│        ┆        ┆            ┆ i64        ┆   ┆ str        ┆ str        ┆ i64        ┆ str       │
╞════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 281    ┆ 1      ┆ allele     ┆ 22         ┆ … ┆ OMIM       ┆ Rare       ┆ 6          ┆ HYPER-IgD │
│        ┆        ┆            ┆            ┆   ┆            ┆ genetic    ┆            ┆ SYNDROME; │
│        ┆        ┆            ┆            ┆   ┆            ┆ systemic   ┆            ┆ MEVALONIC │
│        ┆        ┆            ┆            ┆   ┆            ┆ or rheum…  ┆            ┆ …         │
│ 281    ┆ 3      ┆ allele     ┆ 22         ┆ … ┆ OMIM       ┆ Rare       ┆ 6          ┆ HYPER-IgD │
│        ┆        ┆            ┆            ┆   ┆            ┆ genetic    ┆            ┆ SYNDROME; │
│        ┆        ┆            ┆            ┆   ┆            ┆ systemic   ┆            ┆ MEVALONIC │
│        ┆        ┆            ┆            ┆   ┆            ┆ or rheum…  ┆            ┆ …         │
│ 281    ┆ 4      ┆ allele     ┆ 22         ┆ … ┆ OMIM       ┆ Rare       ┆ 6          ┆ POROKERAT │
│        ┆        ┆            ┆            ┆   ┆            ┆ genetic    ┆            ┆ OSIS 3,   │
│        ┆        ┆            ┆            ┆   ┆            ┆ systemic   ┆            ┆ MULTIPLE  │
│        ┆        ┆            ┆            ┆   ┆            ┆ or rheum…  ┆            ┆ TYPE…     │
│ 281    ┆ 5      ┆ allele     ┆ 22         ┆ … ┆ OMIM       ┆ Rare       ┆ 6          ┆ MEVALONIC │
│        ┆        ┆            ┆            ┆   ┆            ┆ genetic    ┆            ┆ ACIDURIA; │
│        ┆        ┆            ┆            ┆   ┆            ┆ systemic   ┆            ┆ HYPER-IgD │
│        ┆        ┆            ┆            ┆   ┆            ┆ or rheum…  ┆            ┆ …         │
│ 281    ┆ 6      ┆ allele     ┆ 22         ┆ … ┆ OMIM       ┆ Rare       ┆ 6          ┆ HYPER-IgD │
│        ┆        ┆            ┆            ┆   ┆            ┆ genetic    ┆            ┆ SYNDROME; │
│        ┆        ┆            ┆            ┆   ┆            ┆ systemic   ┆            ┆ MEVALONIC │
│        ┆        ┆            ┆            ┆   ┆            ┆ or rheum…  ┆            ┆ …         │
│ …      ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ null   ┆ null   ┆ pdest_empt ┆ 20         ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│        ┆        ┆ y          ┆            ┆   ┆            ┆            ┆            ┆           │
│ null   ┆ null   ┆ pdest_empt ┆ 21         ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│        ┆        ┆ y          ┆            ┆   ┆            ┆            ┆            ┆           │
│ null   ┆ null   ┆ pdest_empt ┆ 21         ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│        ┆        ┆ y          ┆            ┆   ┆            ┆            ┆            ┆           │
│ null   ┆ null   ┆ pdest_empt ┆ 22         ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│        ┆        ┆ y          ┆            ┆   ┆            ┆            ┆            ┆           │
│ null   ┆ null   ┆ pdest_empt ┆ 22         ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│        ┆        ┆ y          ┆            ┆   ┆            ┆            ┆            ┆           │
└────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [16]:
pdest_layout_seq_conf_df.write_parquet(f'{dualipa_outputs}/dualipa_experimental_layout.parquet')