# Create files mapping FACS well and plate to basic allele metadata

This script takes cherry picking and allele info files as input and produces a table relating FACS well and plate IDs to allele IDs and symbols.

In [1]:
import pandas as pd
import polars as pl
import numpy as np
import os

In [2]:
dualipa_inputs = "../1_inputs"
dualipa_outputs = "../3_outputs"
allele_collection_inputs = "../../../1_allele_collection/1_inputs/seq_confirmation_results"
allele_collection_outputs = "../../../1_allele_collection/3_outputs"

## 1. Loading the pdest layout data frame

Vidal lab ran experiment once and analyzed the data. Some alleles didn't pass the qa/qc thresholds or got no data. Batch5 is is a re-run for all alleles that failed in the first set of batches. Here, we process everything together from scratch. An allele should always be compared to the wt on the same batch and plate. The summary stats can then be compared across batches.

In [3]:
# Read in cherry picking files for both the initial batches and the second round
cp_col = ['orf_id', 'mut_id', 'node_type','dest_pla_id', 'dest_pla', 'dest_well']

pdest_layout_initial_batches_df = pd.read_csv(f'{dualipa_inputs}/cherry_picking_files/summary_CP_VUSDUALXP.csv', index_col=0)[cp_col]
pdest_layout_b5_df = pd.read_csv(f'{dualipa_inputs}/cherry_picking_files/summary_CP_VUSDUALXP_batch5.csv', index_col=0)[cp_col]

pdest_layout_df = pd.concat([pdest_layout_b5_df, pdest_layout_initial_batches_df])
pdest_layout_df = pl.DataFrame(pdest_layout_df)
pdest_layout_df = pdest_layout_df.with_columns(
    pl.col("orf_id").cast(pl.Int64).alias("orf_id"),
    pl.col("mut_id").cast(pl.Int64).alias("mut_id")
)
pdest_layout_df
### This doesn't have well A01

shape: (2_311, 6)
┌────────┬────────┬─────────────┬─────────────┬──────────────┬───────────┐
│ orf_id ┆ mut_id ┆ node_type   ┆ dest_pla_id ┆ dest_pla     ┆ dest_well │
│ ---    ┆ ---    ┆ ---         ┆ ---         ┆ ---          ┆ ---       │
│ i64    ┆ i64    ┆ str         ┆ i64         ┆ str          ┆ str       │
╞════════╪════════╪═════════════╪═════════════╪══════════════╪═══════════╡
│ 56360  ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ A12       │
│ 56360  ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ B12       │
│ 56360  ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ C12       │
│ 56360  ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ D12       │
│ 9905   ┆ 0      ┆ wt          ┆ 23          ┆ VUSDUALXP_23 ┆ F02       │
│ …      ┆ …      ┆ …           ┆ …           ┆ …            ┆ …         │
│ null   ┆ null   ┆ pdest_empty ┆ 20          ┆ VUSDUALXP_20 ┆ A08       │
│ null   ┆ null   ┆ pdest_empty ┆ 21          ┆ VUSDUALXP_21 ┆ A07       │
│ null   ┆ null   ┆ pdest_empty ┆ 21          ┆ VUSDUALXP_21 ┆ A08       │
│ null   ┆ null   ┆ pdest_empty ┆ 22          ┆ VUSDUALXP_22 ┆ A07       │
│ null   ┆ null   ┆ pdest_empty ┆ 22          ┆ VUSDUALXP_22 ┆ A08       │
└────────┴────────┴─────────────┴─────────────┴──────────────┴───────────┘

In [4]:
pdest_layout_df.filter((pl.col("dest_pla_id")==18)&(pl.col("dest_well")=="E11"))

shape: (1, 6)
┌────────┬────────┬───────────┬─────────────┬──────────────┬───────────┐
│ orf_id ┆ mut_id ┆ node_type ┆ dest_pla_id ┆ dest_pla     ┆ dest_well │
│ ---    ┆ ---    ┆ ---       ┆ ---         ┆ ---          ┆ ---       │
│ i64    ┆ i64    ┆ str       ┆ i64         ┆ str          ┆ str       │
╞════════╪════════╪═══════════╪═════════════╪══════════════╪═══════════╡
│ 3438   ┆ 201180 ┆ allele    ┆ 18          ┆ VUSDUALXP_18 ┆ E11       │
└────────┴────────┴───────────┴─────────────┴──────────────┴───────────┘

## 2. Loading the sequence confirmed results

In [5]:
seq_confirm_code_df = pd.read_table(f"{allele_collection_inputs}/sequence_confirmation_class_code.tsv")
with pd.option_context('display.max_columns', None):
    display(seq_confirm_code_df)

   code                                      description
0     1                              perfectly validated
1     2             partially validated, >= 50% coverage
2     3                                        wild type
3     4               partial wild type, >= 50% coverage
4     5  target and off-target mutation, >= 50% coverage
5     6             off-target mutation, >= 50% coverage
6     7                        truncated, < 50% coverage
7    99                                         no reads

In [6]:
seq_confirm_res_df = pd.read_table(f"{allele_collection_outputs}/varchamp_seq_confirm_alleles_clinvar_gnomad_dbnsfp_struc_scores_OMIM_MOI_disease_modules.tsv", low_memory=False)
seq_confirm_res_df = pl.DataFrame(
    seq_confirm_res_df
).with_columns(
    pl.col("mut_id").cast(pl.Int64).alias("mut_id")
)
with pl.Config(set_tbl_cols=100):
    display(seq_confirm_res_df)

shape: (9_153, 530)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬───┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sym ┆ ens ┆ orf ┆ mut ┆ ccs ┆ ccs ┆ spd ┆ nt_ ┆ aa_ ┆ col ┆ ent ┆ ent ┆ ent ┆ ent ┆ ent ┆ db_ ┆ db_ ┆ n2h ┆ n2h ┆ dua ┆ dua ┆ mis ┆ mis ┆ ent ┆ ent ┆ db_ ┆ db_ ┆ n2h ┆ n2h ┆ n2h ┆ dua ┆ dua ┆ dua ┆ mis ┆ mis ┆ mis ┆ gen ┆ chr ┆ nuc ┆ ref ┆ alt ┆ Chr ┆ ent ┆ db_ ┆ n2h ┆ dua ┆ mis ┆ var ┆ #Al ┆ Typ ┆ … ┆ Gen ┆ Gen ┆ HGN ┆ Cli ┆ Cli ┆ Las ┆ RS# ┆ nsv ┆ RCV ┆ Phe ┆ Phe ┆ Ori ┆ Ori ┆ Ass ┆ Chr ┆ Chr ┆ Sta ┆ Sto ┆ Cyt ┆ Rev ┆ Num ┆ Gui ┆ Tes ┆ Oth ┆ Sub ┆ Var ┆ Pos ┆ Ref ┆ Alt ┆ Som ┆ Som ┆ Rev ┆ Onc ┆ Onc ┆ Rev ┆ SCV ┆ SCV ┆ SCV ┆ cli ┆ cli ┆ Ref ┆ Sta ┆ cli ┆ pld ┆ rsa ┆ OMI ┆ inh ┆ dis ┆ dis ┆ OMI │
│ bol ┆ emb ┆ _id ┆ _id ┆ b_m ┆ b_a ┆ i   ┆ cha ┆ cha ┆ lec ┆ ry_ ┆ ry_ ┆ ry_ ┆ ry_ ┆ ry_ ┆ pla ┆ wel ┆ _pl ┆ _we ┆ lip ┆ lip ┆ loc ┆ loc ┆ ry_ ┆ ry_ ┆ seq ┆ seq ┆ _se ┆ _se ┆ _re ┆ lip ┆ lip ┆ lip ┆ loc ┆ loc ┆ loc ┆ e_v ┆ _nu ┆ _lo ┆ _al ┆ _al ┆ om  ┆ ry_ ┆ seq ┆ _se ┆ lip ┆ loc ┆ id  ┆ lel ┆ e   ┆   ┆ eID ┆ eSy ┆ C_I ┆ nic ┆ nSi ┆ tEv ┆ (db ┆ /es ┆ acc ┆ not ┆ not ┆ gin ┆ gin ┆ emb ┆ omo ┆ omo ┆ rt_ ┆ p_d ┆ oge ┆ iew ┆ ber ┆ del ┆ ted ┆ erI ┆ mit ┆ iat ┆ iti ┆ ere ┆ ern ┆ ati ┆ ati ┆ iew ┆ oge ┆ oge ┆ iew ┆ sFo ┆ sFo ┆ sFo ┆ nva ┆ nva ┆ Seq ┆ rSt ┆ nva ┆ dt  ┆ --- ┆ M_I ┆ eri ┆ eas ┆ eas ┆ M_d │
│ --- ┆ l_g ┆ --- ┆ --- ┆ uta ┆ lle ┆ --- ┆ nge ┆ nge ┆ tio ┆ pla ┆ wel ┆ pla ┆ wel ┆ seq ┆ te  ┆ l   ┆ ate ┆ ll  ┆ _pl ┆ _we ┆ ali ┆ ali ┆ seq ┆ seq ┆ uen ┆ uen ┆ que ┆ que ┆ f_s ┆ _se ┆ _se ┆ _re ┆ ali ┆ ali ┆ ali ┆ ari ┆ m   ┆ c   ┆ lel ┆ lel ┆ --- ┆ seq ┆ _fi ┆ q_f ┆ _se ┆ ali ┆ --- ┆ eID ┆ --- ┆   ┆ _db ┆ mbo ┆ D_d ┆ alS ┆ gSi ┆ alu ┆ SNP ┆ v   ┆ ess ┆ ype ┆ ype ┆ _db ┆ Sim ┆ ly_ ┆ som ┆ som ┆ dbn ┆ bns ┆ net ┆ Sta ┆ Sub ┆ ine ┆ InG ┆ Ds_ ┆ ter ┆ ion ┆ onV ┆ nce ┆ ate ┆ cCl ┆ cCl ┆ Sta ┆ nic ┆ nic ┆ Sta ┆ rAg ┆ rAg ┆ rAg ┆ r_n ┆ r_a ┆ _mR ┆ atu ┆ r_c ┆ --- ┆ f64 ┆ Ds  ┆ tan ┆ e_m ┆ e_m ┆ ise │
│ str ┆ ene ┆ i64 ┆ i64 ┆ tio ┆ le_ ┆ str ┆ --- ┆ --- ┆ n   ┆ te_ ┆ l_o ┆ te_ ┆ l_c ┆ _po ┆ --- ┆ --- ┆ --- ┆ --- ┆ ate ┆ ll  ┆ zat ┆ zat ┆ uen ┆ uen ┆ ced ┆ ce_ ┆ nce ┆ nce ┆ equ ┆ que ┆ que ┆ f_s ┆ zat ┆ zat ┆ zat ┆ ant ┆ --- ┆ --- ┆ e   ┆ e   ┆ str ┆ _fi ┆ nal ┆ ina ┆ q_f ┆ zat ┆ str ┆ --- ┆ str ┆   ┆ nsf ┆ l_d ┆ bns ┆ ign ┆ mpl ┆ ate ┆ )_d ┆ (db ┆ ion ┆ IDS ┆ Lis ┆ nsf ┆ ple ┆ dbn ┆ eAc ┆ e_d ┆ sfp ┆ fp  ┆ ic_ ┆ tus ┆ mit ┆ s_d ┆ TR_ ┆ dbn ┆ Cat ┆ ID_ ┆ CF_ ┆ All ┆ All ┆ ini ┆ ini ┆ tus ┆ ity ┆ ity ┆ tus ┆ gre ┆ gre ┆ gre ┆ t_c ┆ a_c ┆ NA_ ┆ s_d ┆ lns ┆ f64 ┆     ┆ --- ┆ ce_ ┆ odu ┆ odu ┆ ase │
│     ┆ _id ┆     ┆     ┆ n_i ┆ id  ┆     ┆ str ┆ str ┆ --- ┆ ori ┆ rig ┆ con ┆ ons ┆ ol  ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ ion ┆ ion ┆ ced ┆ ce_ ┆ --- ┆ con ┆ d   ┆ _co ┆ enc ┆ nce ┆ nce ┆ equ ┆ ion ┆ ion ┆ ion ┆ --- ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆ nal ┆ --- ┆ l   ┆ ina ┆ ion ┆     ┆ f64 ┆     ┆   ┆ p   ┆ bns ┆ fp  ┆ ifi ┆ e_d ┆ d_d ┆ bns ┆ Var ┆ _db ┆ _db ┆ t_d ┆ p   ┆ _db ┆ sfp ┆ ces ┆ bns ┆ --- ┆ --- ┆ dbn ┆ _db ┆ ter ┆ bns ┆ dbn ┆ sfp ┆ ego ┆ dbn ┆ dbn ┆ ele ┆ ele ┆ cal ┆ cal ┆ Cli ┆ _db ┆ Las ┆ Onc ┆ gat ┆ gat ┆ gat ┆ han ┆ han ┆ dbn ┆ bns ┆ ig_ ┆     ┆     ┆ str ┆ pat ┆ les ┆ le_ ┆ _na │
│     ┆ --- ┆     ┆     ┆ d   ┆ --- ┆     ┆     ┆     ┆ str ┆ g   ┆ --- ┆ so  ┆ o   ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ _pl ┆ _we ┆ --- ┆ con ┆ f64 ┆ fir ┆ --- ┆ nfi ┆ e_c ┆ d   ┆ _co ┆ enc ┆ _se ┆ _se ┆ _re ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆ --- ┆ l   ┆ _se ┆     ┆     ┆     ┆   ┆ --- ┆ fp  ┆ --- ┆ can ┆ bns ┆ bns ┆ fp  ┆ )_d ┆ nsf ┆ nsf ┆ bns ┆ --- ┆ nsf ┆ --- ┆ sio ┆ fp  ┆ f64 ┆ f64 ┆ sfp ┆ nsf ┆ s_d ┆ fp  ┆ sfp ┆ --- ┆ rie ┆ sfp ┆ sfp ┆ VCF ┆ VCF ┆ Imp ┆ Imp ┆ nic ┆ nsf ┆ tEv ┆ oge ┆ eGe ┆ eSo ┆ eOn ┆ ge_ ┆ ge_ ┆ sfp ┆ fp  ┆ cle ┆     ┆     ┆     ┆ ter ┆ --- ┆ cou ┆ mes │
│     ┆ str ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ --- ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆ ll  ┆ f64 ┆ fir ┆     ┆ mat ┆ f64 ┆ rma ┆ onf ┆ --- ┆ nfi ┆ e_c ┆ que ┆ que ┆ f_s ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ --- ┆ q_f ┆     ┆     ┆     ┆   ┆ f64 ┆ --- ┆ str ┆ ce_ ┆ fp  ┆ fp  ┆ --- ┆ bns ┆ p   ┆ p   ┆ fp  ┆ str ┆ p   ┆ str ┆ n_d ┆ --- ┆     ┆     ┆ --- ┆ p   ┆ bns ┆ --- ┆ --- ┆ str ┆ s_d ┆ --- ┆ --- ┆ _db ┆ _db ┆ act ┆ act ┆ alI ┆ p   ┆ alu ┆ nic ┆ rml ┆ mat ┆ cog ┆ dbn ┆ dbn ┆ --- ┆ --- ┆ an_ ┆     ┆     ┆     ┆ n   ┆ str ┆ nt  ┆ --- │
│     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ mat ┆     ┆ ion ┆     ┆ tio ┆ irm ┆ f64 ┆ rma ┆ onf ┆ nce ┆ nce ┆ equ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ ina ┆     ┆     ┆     ┆   ┆     ┆ str ┆     ┆ dbn ┆ --- ┆ --- ┆ f64 ┆ fp  ┆ --- ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ bns ┆ str ┆     ┆     ┆ str ┆ --- ┆ fp  ┆ str ┆ str ┆     ┆ bns ┆ f64 ┆ f64 ┆ nsf ┆ nsf ┆ _db ┆ Las ┆ mpa ┆ --- ┆ ate ┆ ity ┆ ine ┆ icC ┆ eni ┆ sfp ┆ sfp ┆ str ┆ f64 ┆ dbn ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ion ┆     ┆ _cl ┆     ┆ n_c ┆ ati ┆     ┆ tio ┆ irm ┆ d   ┆ _co ┆ enc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆ sfp ┆ f64 ┆ str ┆     ┆ --- ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ fp  ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆ fp  ┆     ┆     ┆ p   ┆ p   ┆ nsf ┆ tEv ┆ ct_ ┆ str ┆ d_d ┆ _db ┆ Cla ┆ lin ┆ cit ┆ --- ┆ --- ┆     ┆     ┆ sfp ┆     ┆     ┆     ┆ str ┆     ┆ i64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _cl ┆     ┆ ass ┆     ┆ las ┆ on_ ┆     ┆ n_c ┆ ati ┆ --- ┆ nfi ┆ e_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ p   ┆ alu ┆ dbn ┆     ┆ bns ┆ nsf ┆ ssi ┆ ica ┆ yCl ┆ str ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ --- ┆     ┆ …   ┆ …   ┆     ┆ …   ┆ …   ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ str ┆ str ┆ --- ┆ …   ┆ …   ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ str ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═══╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ GBA ┆ ENS ┆ 2   ┆ 6   ┆ CCS ┆ ALE ┆ NC_ ┆ 160 ┆ Val ┆ RC4 ┆ RC4 ┆ H01 ┆ GDE ┆ F12 ┆ 2.0 ┆ RC4 ┆ H01 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 2.0 ┆ 0.0 ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ GBA ┆ 1.0 ┆ 1.5 ┆ C   ┆ G   ┆ 1   ┆ Y   ┆ Y   ┆ N   ┆ N   ┆ N   ┆ 1-1 ┆ nul ┆ nul ┆ … ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0   ┆ nul │
│ 1   ┆ G00 ┆     ┆     ┆ BVa ┆ 000 ┆ 000 ┆ G>C ┆ 54L ┆     ┆ _Mu ┆     ┆ hDi ┆     ┆     ┆ _Mu ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 1_V ┆     ┆ 524 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 552 ┆ l   ┆ l   ┆   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   │
│     ┆ 000 ┆     ┆     ┆ rC0 ┆ 058 ┆ 001 ┆     ┆ eu  ┆     ┆ t_G ┆     ┆ sVC ┆     ┆     ┆ t_G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al5 ┆     ┆ 003 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 400 ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 177 ┆     ┆     ┆ 000 ┆ 4   ┆ .11 ┆     ┆     ┆     ┆ DEh ┆     ┆ h_4 ┆     ┆     ┆ DDh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4Le ┆     ┆ 3e8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 33- ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 628 ┆     ┆     ┆ 01  ┆     ┆ :15 ┆     ┆     ┆     ┆ 102 ┆     ┆ 005 ┆     ┆     ┆ 102 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C-G ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 524 ┆     ┆     ┆     ┆ 6   ┆     ┆ 4   ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 003 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 3:C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ :G  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ GBA ┆ ENS ┆ 2   ┆ 73  ┆ CCS ┆ ALE ┆ NC_ ┆ 670 ┆ Leu ┆ RC4 ┆ RC4 ┆ E01 ┆ GDE ┆ C12 ┆ 2.0 ┆ RC4 ┆ E01 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ GBA ┆ 1.0 ┆ 1.5 ┆ G   ┆ A   ┆ 1   ┆ Y   ┆ Y   ┆ N   ┆ N   ┆ N   ┆ 1-1 ┆ nul ┆ nul ┆ … ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0   ┆ nul │
│ 1   ┆ G00 ┆     ┆     ┆ BVa ┆ 000 ┆ 000 ┆ C>T ┆ 224 ┆     ┆ _Mu ┆     ┆ hDi ┆     ┆     ┆ _Mu ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 1_L ┆     ┆ 523 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 552 ┆ l   ┆ l   ┆   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   │
│     ┆ 000 ┆     ┆     ┆ rC0 ┆ 000 ┆ 001 ┆     ┆ Phe ┆     ┆ t_G ┆     ┆ sVC ┆     ┆     ┆ t_G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eu2 ┆     ┆ 822 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 382 ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 177 ┆     ┆     ┆ 000 ┆ 02  ┆ .11 ┆     ┆     ┆     ┆ DEh ┆     ┆ h_4 ┆     ┆     ┆ DDh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 24P ┆     ┆ 5e8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 25- ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 628 ┆     ┆     ┆ 02  ┆     ┆ :15 ┆     ┆     ┆     ┆ 102 ┆     ┆ 005 ┆     ┆     ┆ 102 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ he  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ G-A ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 523 ┆     ┆     ┆     ┆ 6   ┆     ┆ 4   ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 822 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 5:G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

## 3. Map the pdest mutation to meta mutation information

In [7]:
# seq_confirm_res_df.filter(pl.col("mut_id")==0)

## map orf_id to symbol and ensembl_gene_id
orfid_2_symbol_mapping = dict(zip(
    seq_confirm_res_df.filter(pl.col("symbol").is_not_null())["orf_id"].to_list(),
    seq_confirm_res_df.filter(pl.col("symbol").is_not_null())["symbol"].to_list()
))

orfid_2_geneid_mapping = dict(zip(
    seq_confirm_res_df.filter(pl.col("ensembl_gene_id").is_not_null())["orf_id"].to_list(),
    seq_confirm_res_df.filter(pl.col("ensembl_gene_id").is_not_null())["ensembl_gene_id"].to_list()
))

In [8]:
## join the pdest variant with mut meta info by "INNER" JOIN;
## some alleles were filtered out during the allele collection stage due to their poor seq quality
## SHOULD REMOVE them from DUAL-IPA assay
pdest_layout_seq_conf_mut_df = pdest_layout_df.filter(
    pl.col("mut_id")!=0
).join(
    seq_confirm_res_df, 
    on=["orf_id", "mut_id"],
    how="inner"
)

## need to add wt data here as well
pdest_layout_seq_conf_wt_df = pdest_layout_df.filter(
    pl.col("mut_id")==0
).join(
    seq_confirm_res_df, 
    on=["orf_id", "mut_id"],
    how="left"
).with_columns(
    pl.col("aa_change").fill_null("WT"),
    pl.col("nt_change").fill_null("WT"),
    pl.col("orf_id").map_elements(lambda x: orfid_2_symbol_mapping[x] if x in orfid_2_symbol_mapping else pl.Null, return_dtype=pl.String).alias("symbol"),
    pl.col("orf_id").map_elements(lambda x: orfid_2_geneid_mapping[x] if x in orfid_2_geneid_mapping else pl.Null, return_dtype=pl.String).alias("ensembl_gene_id")
)

## need to add the pdest_empty wells as well
pdest_layout_seq_conf_empty_df = pdest_layout_df.filter(
    pl.col("mut_id").is_null()
).join(
    seq_confirm_res_df, 
    on=["orf_id", "mut_id"],
    how="left"
)

## concat var and wt and empty
pdest_layout_seq_conf_df = pl.concat([
    pdest_layout_seq_conf_mut_df, pdest_layout_seq_conf_wt_df, pdest_layout_seq_conf_empty_df
])
print(pdest_layout_seq_conf_df["dualip_sequence_confirmation_class"].unique())

shape: (9,)
Series: 'dualip_sequence_confirmation_class' [f64]
[
	null
	1.0
	2.0
	3.0
	4.0
	5.0
	6.0
	7.0
	99.0
]

In [9]:
pdest_layout_seq_conf_df.unique(subset="dualip_seq_final")["dualip_seq_final"]

shape: (3,)
Series: 'dualip_seq_final' [str]
[
	"Y"
	"N"
	null
]

In [10]:
pdest_layout_seq_conf_df.write_csv(f'{dualipa_outputs}/dualipa_experimental_layout.csv')