# Protein abundance change

In [4]:
# imports
import os
import polars as pl
import numpy as np
from tqdm import tqdm
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    average_precision_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    roc_auc_score,
)

## Disable truncation globally
pl.Config.set_tbl_rows(20)  # Show all rows
pl.Config.set_tbl_cols(40)  # Show all columns

## define control types
TC = ["EGFP"]
NC = ["RHEB", "MAPK9", "PRKACB", "SLIRP"]
PC = ["ALK", "ALK_Arg1275Gln", "PTK2B"]
cNC = ["Renilla"]
cPC = ["KRAS", "PTK2B", "GHSR", "ABL1", "BRD4", "OPRM1", "RB1", "ADA", "WT PMP22", "LYN", "TNF", 
       "CYP2A6", "CSK", "PAK1", "ALDH2", "CHRM3", "KCNQ2", "ALK T1151M", "PRKCE", "LPAR1", "PLP1"]

%matplotlib inline

thresh = 3
min_class_num = 2

In [28]:
# Paths
metrics_dir = "../1_snakemake_pipeline/2025_varchamp_snakemake/snakemake_pipeline/outputs/analyses/{}/profiles_tcdropped_filtered_var_mad_outlier_featselect"
batches = ["2024_01_23_Batch_7", "2024_02_06_Batch_8"]

metrics_df, metrics_wtvar = pl.DataFrame(), pl.DataFrame()
for batch in batches:
    met_dir = metrics_dir.format(batch)
    metrics_df_batch = pl.read_csv(f"{met_dir}/metrics.csv")
    metrics_wtvar_batch = pl.read_csv(f"{met_dir}/metrics_summary.csv")

    metrics_df = pl.concat([metrics_df, metrics_df_batch])
    metrics_wtvar = pl.concat([metrics_wtvar, metrics_wtvar_batch])

In [ ]:
metrics_wtvar

shape: (2_252, 11)
┌─────────┬────────┬────────┬───────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Classif ┆ allele ┆ Allele ┆ Batch ┆ AUROC_ ┆ AUROC_ ┆ trains ┆ testsi ┆ trains ┆ testsi ┆ Traini │
│ ier_typ ┆ _0     ┆ _set   ┆ ---   ┆ thresh ┆ mean   ┆ ize_0_ ┆ ze_0_m ┆ ize_1_ ┆ ze_1_m ┆ ng_imb │
│ e       ┆ ---    ┆ ---    ┆ str   ┆ ---    ┆ ---    ┆ mean   ┆ ean    ┆ mean   ┆ ean    ┆ alance │
│ ---     ┆ str    ┆ str    ┆       ┆ f64    ┆ f64    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ _mean  │
│ str     ┆        ┆        ┆       ┆        ┆        ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ ---    │
│         ┆        ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆ f64    │
╞═════════╪════════╪════════╪═══════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ morphol ┆ NEXN_T ┆ A1P3   ┆ B7    ┆ 0.9973 ┆ 0.6554 ┆ 970.5  ┆ 323.5  ┆ 963.75 ┆ 321.25 ┆ 1.0667 │
│ ogy     ┆ yr544C ┆        ┆       ┆ 15     ┆ 26     ┆        ┆        ┆        ┆        ┆ 52     │
│         ┆ ys     ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ morphol ┆ DES_Le ┆ A1P1   ┆ B7    ┆ 0.9973 ┆ 0.9093 ┆ 611.25 ┆ 203.75 ┆ 717.0  ┆ 239.0  ┆ 1.1787 │
│ ogy     ┆ u274Pr ┆        ┆       ┆ 15     ┆ 91     ┆        ┆        ┆        ┆        ┆ 83     │
│         ┆ o      ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ morphol ┆ PMP22_ ┆ A1P3   ┆ B7    ┆ 0.9973 ┆ 0.8224 ┆ 1362.7 ┆ 454.25 ┆ 1194.7 ┆ 398.25 ┆ 1.1495 │
│ ogy     ┆ Arg157 ┆        ┆       ┆ 15     ┆ 57     ┆ 5      ┆        ┆ 5      ┆        ┆ 95     │
│         ┆ Trp    ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ PYGL_A ┆ A1P3   ┆ B7    ┆ 0.7141 ┆ 0.8367 ┆ 614.25 ┆ 204.75 ┆ 814.5  ┆ 271.5  ┆ 1.3247 │
│ ation   ┆ sn632I ┆        ┆       ┆ 8      ┆ 91     ┆        ┆        ┆        ┆        ┆ 51     │
│         ┆ le     ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ KRT86_ ┆ A1P2   ┆ B7    ┆ 0.7141 ┆ 0.6767 ┆ 697.5  ┆ 232.5  ┆ 948.75 ┆ 316.25 ┆ 1.3743 │
│ ation   ┆ Ala118 ┆        ┆       ┆ 8      ┆ 01     ┆        ┆        ┆        ┆        ┆ 13     │
│         ┆ Glu    ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ KRT6A_ ┆ A1P2   ┆ B7    ┆ 0.7141 ┆ 0.9057 ┆ 710.25 ┆ 236.75 ┆ 837.0  ┆ 279.0  ┆ 1.1841 │
│ ation   ┆ Leu468 ┆        ┆       ┆ 8      ┆ 17     ┆        ┆        ┆        ┆        ┆ 4      │
│         ┆ Pro    ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ AGXT_A ┆ A1P1   ┆ B7    ┆ 0.7141 ┆ 0.6418 ┆ 1403.2 ┆ 467.75 ┆ 1590.7 ┆ 530.25 ┆ 1.1321 │
│ ation   ┆ sn22Se ┆        ┆       ┆ 8      ┆ 6      ┆ 5      ┆        ┆ 5      ┆        ┆ 69     │
│         ┆ r      ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ morphol ┆ POMT1_ ┆ A1P3   ┆ B7    ┆ 0.9973 ┆ 0.6013 ┆ 647.25 ┆ 215.75 ┆ 645.0  ┆ 215.0  ┆ 1.0777 │
│ ogy     ┆ Ser515 ┆        ┆       ┆ 15     ┆ 11     ┆        ┆        ┆        ┆        ┆ 82     │
│         ┆ Arg    ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ AGXT_A ┆ A1P1   ┆ B7    ┆ 0.7141 ┆ 0.5422 ┆ 1352.2 ┆ 450.75 ┆ 1590.7 ┆ 530.25 ┆ 1.1771 │
│ ation   ┆ rg381L ┆        ┆       ┆ 8      ┆ 41     ┆ 5      ┆        ┆ 5      ┆        ┆ 53     │
│         ┆ ys     ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ morphol ┆ MVK_Hi ┆ A1P3   ┆ B7    ┆ 0.9973 ┆ 0.5373 ┆ 1181.2 ┆ 393.75 ┆ 977.25 ┆ 325.75 ┆ 1.2186 │
│ ogy     ┆ s20Gln ┆        ┆       ┆ 15     ┆ 47     ┆ 5      ┆        ┆        ┆        ┆ 48     │
│ …       ┆ …      ┆ …      ┆ …     ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ morphol ┆ DES_Ar ┆ A1P1   ┆ B8    ┆ 0.9980 ┆ 0.5014 ┆ 214.5  ┆ 71.5   ┆ 318.75 ┆ 106.25 ┆ 1.4848 │
│ ogy     ┆ g355Pr ┆        ┆       ┆ 7      ┆ 89     ┆        ┆        ┆        ┆        ┆ 92     │
│         ┆ o      ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ PKP2_I ┆ A1P3   ┆ B8    ┆ 0.8613 ┆ 0.4173 ┆ 92.0   ┆ 30.0   ┆ 78.666 ┆ 39.333 ┆ 1.3145 │
│ ation   ┆ le487S ┆        ┆       ┆ 92     ┆ 5      ┆        ┆        ┆ 667    ┆ 333    ┆ 83     │
│         ┆ er     ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ PMP22_ ┆ A1P3   ┆ B8    ┆ 0.8613 ┆ 1.0    ┆ 158.0  ┆ 79.0   ┆ 275.33 ┆ 137.66 ┆ 1.8405 │
│ ation   ┆ Asp37V ┆        ┆       ┆ 92     ┆        ┆        ┆        ┆ 3333   ┆ 6667   ┆ 53     │
│         ┆ al     ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ morphol ┆ RP2_Cy ┆ A1P3   ┆ B8    ┆ 0.9980 ┆ 0.8115 ┆ 178.66 ┆ 89.333 ┆ 397.33 ┆ 198.66 ┆ 2.2147 │
│ ogy     ┆ s86Tyr ┆        ┆       ┆ 7      ┆ 09     ┆ 6667   ┆ 333    ┆ 3333   ┆ 6667   ┆ 71     │
│ localiz ┆ CHN1_G ┆ A1P1   ┆ B8    ┆ 0.8613 ┆ 0.7772 ┆ 493.5  ┆ 164.5  ┆ 512.25 ┆ 170.75 ┆ 1.1131 │
│ ation   ┆ lu313L ┆        ┆       ┆ 92     ┆ 95     ┆        ┆        ┆        ┆        ┆ 39     │
│         ┆ ys     ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ PKP2_L ┆ A1P3   ┆ B8    ┆ 0.8613 ┆ 0.5197 ┆ 70.0   ┆ 35.0   ┆ 78.666 ┆ 39.333 ┆ 1.1618 │
│ ation   ┆ ys472A ┆        ┆       ┆ 92     ┆ 97     ┆        ┆        ┆ 667    ┆ 333    ┆ 64     │
│         ┆ rg     ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ IL2RG_ ┆ A1P2   ┆ B8    ┆ 0.8613 ┆ 0.9650 ┆ 792.75 ┆ 264.25 ┆ 831.0  ┆ 277.0  ┆ 1.0478 │
│ ation   ┆ Trp237 ┆        ┆       ┆ 92     ┆ 08     ┆        ┆        ┆        ┆        ┆ 08     │
│         ┆ Arg    ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ localiz ┆ DES_Ar ┆ A1P1   ┆ B8    ┆ 0.8613 ┆ 0.6690 ┆ 292.5  ┆ 97.5   ┆ 318.75 ┆ 106.25 ┆ 1.1099 │
│ ation   ┆ g150Gl ┆        ┆       ┆ 92     ┆ 79     ┆        ┆        ┆        ┆        ┆ 6      │
│         ┆ n      ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ morphol ┆ AGXT_I ┆ A1P1   ┆ B8    ┆ 0.9980 ┆ 0.6263 ┆ 990.75 ┆ 330.25 ┆ 440.25 ┆ 146.75 ┆ 2.2529 │
│ ogy     ┆ le340M ┆        ┆       ┆ 7      ┆ 53     ┆        ┆        ┆        ┆        ┆ 62     │
│         ┆ et     ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
│ morphol ┆ PKP2_L ┆ A1P3   ┆ B8    ┆ 0.9980 ┆ 0.8192 ┆ 70.0   ┆ 35.0   ┆ 78.666 ┆ 39.333 ┆ 1.1618 │
│ ogy     ┆ ys472A ┆        ┆       ┆ 7      ┆ 72     ┆        ┆        ┆ 667    ┆ 333    ┆ 64     │
│         ┆ rg     ┆        ┆       ┆        ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴────────┴────────┴───────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [38]:
## get the localization metrics
local_wtvar = metrics_wtvar.filter(pl.col("Classifier_type") == "localization")

## select alleles mislocalized in both batches
local_wtvar = local_wtvar.with_columns(
    pl.when(pl.col("AUROC_mean") > pl.col("AUROC_thresh"))
    .then(1)
    .otherwise(0)
    .alias("mislocalized")
).unique()

local_wtvar = (
    local_wtvar.pivot(
        index=["allele_0", "Allele_set"],
        on="Batch",
        values="mislocalized",
    )
    .with_columns(
        ((pl.col("B7") == 1) & (pl.col("B8") == 1)).alias(
            "mislocalized_both_batches"
        )
    )
    .rename({"B7": "mislocalized_batch7", "B8": "mislocalized_batch8"})
)

misloc_alleles = (
    local_wtvar
    # .filter(pl.col("Mislocalized_both_batches"))
    .select("allele_0")
    .to_series()
    .to_list()
)

misloc_wt = (
    local_wtvar
    # .filter(pl.col("Mislocalized_both_batches"))
    .with_columns(pl.col("allele_0").str.replace("_.*", "").alias("wt"))
    .select("wt")
    .to_series()
    .unique()
    .to_list()
)

all_alleles = misloc_alleles + misloc_wt

# Get individual classifiers
ind_class = metrics_df.filter(
    (pl.col("Metadata_Control")!="true")
    & (pl.col("Training_imbalance") < thresh)
    & (
        (pl.col("Full_Classifier_ID").str.contains("true"))
        & pl.col("allele_0").is_in(misloc_alleles)
    )
)

In [39]:
ind_class

shape: (4_251, 23)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ AUR ┆ AUP ┆ AUB ┆ Mac ┆ Sen ┆ Spe ┆ Bal ┆ Cla ┆ Ful ┆ Pla ┆ tra ┆ tes ┆ wel ┆ all ┆ tra ┆ tes ┆ wel ┆ all ┆ Met ┆ tra ┆ tes ┆ Tra ┆ Tes │
│ OC  ┆ RC  ┆ PRC ┆ ro_ ┆ sit ┆ cif ┆ anc ┆ ssi ┆ l_C ┆ te  ┆ ins ┆ tsi ┆ l_0 ┆ ele ┆ ins ┆ tsi ┆ l_1 ┆ ele ┆ ada ┆ in_ ┆ t_p ┆ ini ┆ tin │
│ --- ┆ --- ┆ --- ┆ F1  ┆ ivi ┆ ici ┆ ed_ ┆ fie ┆ las ┆ --- ┆ ize ┆ ze_ ┆ --- ┆ _0  ┆ ize ┆ ze_ ┆ --- ┆ _1  ┆ ta_ ┆ pro ┆ rob ┆ ng_ ┆ g_i │
│ f64 ┆ f64 ┆ f64 ┆ --- ┆ ty  ┆ ty  ┆ Acc ┆ r_I ┆ sif ┆ str ┆ _0  ┆ 0   ┆ str ┆ --- ┆ _1  ┆ 1   ┆ str ┆ --- ┆ Con ┆ b_1 ┆ _1  ┆ imb ┆ mba │
│     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ ura ┆ D   ┆ ier ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆ tro ┆ --- ┆ --- ┆ ala ┆ lan │
│     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ cy  ┆ --- ┆ _ID ┆     ┆ i64 ┆ i64 ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆ l   ┆ f64 ┆ f64 ┆ nce ┆ ce  │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ boo ┆     ┆     ┆ f64 ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0.6 ┆ 0.7 ┆ 0.5 ┆ 0.5 ┆ 0.4 ┆ 0.6 ┆ 0.5 ┆ 202 ┆ 202 ┆ 202 ┆ 115 ┆ 203 ┆ H09 ┆ TTP ┆ 107 ┆ 373 ┆ F09 ┆ TTP ┆ fal ┆ 0.4 ┆ 0.6 ┆ 1.0 ┆ 1.8 │
│ 002 ┆ 236 ┆ 875 ┆ 233 ┆ 638 ┆ 403 ┆ 521 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆ 3   ┆     ┆     ┆ A_A ┆ 0   ┆     ┆     ┆ A   ┆ se  ┆ 813 ┆ 475 ┆ 775 ┆ 374 │
│ 19  ┆ 02  ┆ 94  ┆ 85  ┆ 07  ┆ 94  ┆ 01  ┆ 1_2 ┆ 1_2 ┆ 1_2 ┆     ┆     ┆     ┆ sp6 ┆     ┆     ┆     ┆     ┆     ┆ 32  ┆ 69  ┆ 7   ┆ 38  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_B ┆ 2_B ┆ 2_B ┆     ┆     ┆     ┆ 4Gl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P4T ┆ P4T ┆ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4_H ┆ 4_H ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 09_ ┆ 09_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ F09 ┆ F09 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.7 ┆ 0.7 ┆ 0.7 ┆ 0.6 ┆ 0.4 ┆ 0.8 ┆ 0.6 ┆ 202 ┆ 202 ┆ 202 ┆ 702 ┆ 272 ┆ M02 ┆ AMP ┆ 579 ┆ 239 ┆ K02 ┆ AMP ┆ fal ┆ 0.4 ┆ 0.4 ┆ 1.2 ┆ 1.1 │
│ 079 ┆ 234 ┆ 485 ┆ 544 ┆ 937 ┆ 235 ┆ 586 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆     ┆     ┆     ┆ D2_ ┆     ┆     ┆     ┆ D2  ┆ se  ┆ 519 ┆ 677 ┆ 124 ┆ 380 │
│ 59  ┆ 45  ┆ 61  ┆ 05  ┆ 24  ┆ 29  ┆ 27  ┆ 1_1 ┆ 1_1 ┆ 1_1 ┆     ┆     ┆     ┆ Glu ┆     ┆     ┆     ┆     ┆     ┆ 91  ┆ 1   ┆ 35  ┆ 75  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_B ┆ 7_B ┆ 7_B ┆     ┆     ┆     ┆ 697 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆ Asp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P1T ┆ P1T ┆ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_M ┆ 3_M ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 02_ ┆ 02_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ K02 ┆ K02 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.8 ┆ 0.8 ┆ 0.8 ┆ 0.7 ┆ 0.8 ┆ 0.6 ┆ 0.7 ┆ 202 ┆ 202 ┆ 202 ┆ 670 ┆ 359 ┆ C08 ┆ GSS ┆ 107 ┆ 414 ┆ M06 ┆ GSS ┆ fal ┆ 0.6 ┆ 0.5 ┆ 1.6 ┆ 1.1 │
│ 373 ┆ 700 ┆ 531 ┆ 514 ┆ 429 ┆ 573 ┆ 501 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆     ┆     ┆     ┆ _Ar ┆ 4   ┆     ┆     ┆     ┆ se  ┆ 158 ┆ 355 ┆ 029 ┆ 532 │
│ 9   ┆ 89  ┆ 1   ┆ 81  ┆ 95  ┆ 82  ┆ 88  ┆ 1_1 ┆ 1_1 ┆ 1_1 ┆     ┆     ┆     ┆ g28 ┆     ┆     ┆     ┆     ┆     ┆ 26  ┆ 76  ┆ 85  ┆ 03  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_B ┆ 7_B ┆ 7_B ┆     ┆     ┆     ┆ 3Cy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P2T ┆ P2T ┆ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4_C ┆ 4_C ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 08_ ┆ 08_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M06 ┆ M06 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.6 ┆ 0.4 ┆ 0.6 ┆ 0.5 ┆ 0.3 ┆ 0.7 ┆ 0.5 ┆ 202 ┆ 202 ┆ 202 ┆ 178 ┆ 616 ┆ D20 ┆ SDC ┆ 117 ┆ 302 ┆ P18 ┆ SDC ┆ fal ┆ 0.3 ┆ 0.3 ┆ 1.5 ┆ 2.0 │
│ 281 ┆ 374 ┆ 133 ┆ 732 ┆ 576 ┆ 857 ┆ 716 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆ 2   ┆     ┆     ┆ 3_V ┆ 0   ┆     ┆     ┆ 3   ┆ se  ┆ 963 ┆ 289 ┆ 230 ┆ 397 │
│ 88  ┆ 54  ┆ 27  ┆ 96  ┆ 16  ┆ 14  ┆ 65  ┆ 1_1 ┆ 1_1 ┆ 1_1 ┆     ┆     ┆     ┆ al1 ┆     ┆     ┆     ┆     ┆     ┆ 41  ┆ 76  ┆ 77  ┆ 35  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9_B ┆ 9_B ┆ 9_B ┆     ┆     ┆     ┆ 36I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆ le  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P3T ┆ P3T ┆ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4_D ┆ 4_D ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 20_ ┆ 20_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P18 ┆ P18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.7 ┆ 0.6 ┆ 0.8 ┆ 0.6 ┆ 0.5 ┆ 0.8 ┆ 0.6 ┆ 202 ┆ 202 ┆ 202 ┆ 149 ┆ 623 ┆ B12 ┆ DES ┆ 661 ┆ 295 ┆ J21 ┆ DES ┆ fal ┆ 0.3 ┆ 0.3 ┆ 2.2 ┆ 2.1 │
│ 669 ┆ 602 ┆ 040 ┆ 898 ┆ 220 ┆ 443 ┆ 831 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆ 4   ┆     ┆     ┆ _Pr ┆     ┆     ┆     ┆     ┆ se  ┆ 067 ┆ 213 ┆ 602 ┆ 118 │
│ 78  ┆ 6   ┆ 85  ┆ 03  ┆ 34  ┆ 02  ┆ 68  ┆ 1_1 ┆ 1_1 ┆ 1_1 ┆     ┆     ┆     ┆ o41 ┆     ┆     ┆     ┆     ┆     ┆ 29  ┆ 51  ┆ 12  ┆ 64  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_B ┆ 7_B ┆ 7_B ┆     ┆     ┆     ┆ 9Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P1T ┆ P1T ┆ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_B ┆ 3_B ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12_ ┆ 12_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ J21 ┆ J21 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.7 ┆ 0.8 ┆ 0.8 ┆ 0.7 ┆ 0.6 ┆ 0.7 ┆ 0.7 ┆ 202 ┆ 202 ┆ 202 ┆ 152 ┆ 343 ┆ E11 ┆ AGX ┆ 167 ┆ 443 ┆ E07 ┆ AGX ┆ fal ┆ 0.5 ┆ 0.5 ┆ 1.1 ┆ 1.2 │
│ 961 ┆ 498 ┆ 141 ┆ 098 ┆ 433 ┆ 959 ┆ 196 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆ 2   ┆     ┆     ┆ T_G ┆ 8   ┆     ┆     ┆ T   ┆ se  ┆ 243 ┆ 636 ┆ 024 ┆ 915 │
│ 55  ┆ 3   ┆ 84  ┆ 56  ┆ 41  ┆ 18  ┆ 3   ┆ 1_1 ┆ 1_1 ┆ 1_1 ┆     ┆     ┆     ┆ ly8 ┆     ┆     ┆     ┆     ┆     ┆ 75  ┆ 13  ┆ 97  ┆ 45  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_B ┆ 7_B ┆ 7_B ┆     ┆     ┆     ┆ 2Ar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P1T ┆ P1T ┆ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_E ┆ 1_E ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11_ ┆ 11_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ E07 ┆ E07 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.8 ┆ 0.9 ┆ 202 ┆ 202 ┆ 202 ┆ 299 ┆ 123 ┆ M03 ┆ ACS ┆ 745 ┆ 330 ┆ A01 ┆ ACS ┆ fal ┆ 0.7 ┆ 0.7 ┆ 2.4 ┆ 2.6 │
│ 759 ┆ 907 ┆ 755 ┆ 228 ┆ 727 ┆ 536 ┆ 131 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆     ┆     ┆     ┆ F3_ ┆     ┆     ┆     ┆ F3  ┆ se  ┆ 136 ┆ 284 ┆ 916 ┆ 829 │
│ 3   ┆ 53  ┆ 7   ┆ 59  ┆ 27  ┆ 59  ┆ 93  ┆ 1_1 ┆ 1_1 ┆ 1_1 ┆     ┆     ┆     ┆ Met ┆     ┆     ┆     ┆     ┆     ┆ 02  ┆ 77  ┆ 39  ┆ 27  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_B ┆ 7_B ┆ 7_B ┆     ┆     ┆     ┆ 266 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆ Val ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P1T ┆ P1T ┆ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_M ┆ 2_M ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 03_ ┆ 03_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A01 ┆ A01 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.4 ┆ 0.5 ┆ 0.5 ┆ 0.4 ┆ 0.5 ┆ 0.4 ┆ 0.4 ┆ 202 ┆ 202 ┆ 202 ┆ 117 ┆ 507 ┆ K19 ┆ AGX ┆ 161 ┆ 502 ┆ E07 ┆ AGX ┆ fal ┆ 0.5 ┆ 0.4 ┆ 1.3 ┆ 1.0 │
│ 902 ┆ 100 ┆ 125 ┆ 976 ┆ 438 ┆ 536 ┆ 987 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆ 9   ┆     ┆     ┆ T_A ┆ 9   ┆     ┆     ┆ T   ┆ se  ┆ 786 ┆ 975 ┆ 731 ┆ 099 │
│ 25  ┆ 48  ┆ 24  ┆ 01  ┆ 25  ┆ 49  ┆ 37  ┆ 1_1 ┆ 1_1 ┆ 1_1 ┆     ┆     ┆     ┆ rg1 ┆     ┆     ┆     ┆     ┆     ┆ 28  ┆ 22  ┆ 98  ┆ 6   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_B ┆ 7_B ┆ 7_B ┆     ┆     ┆     ┆ 97G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆ ln  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P1T ┆ P1T ┆ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_K ┆ 3_K ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 19_ ┆ 19_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ E07 ┆ E07 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.6 ┆ 0.7 ┆ 0.6 ┆ 0.5 ┆ 0.6 ┆ 0.5 ┆ 0.5 ┆ 202 ┆ 202 ┆ 202 ┆ 566 ┆ 133 ┆ B06 ┆ DES ┆ 742 ┆ 214 ┆ J21 ┆ DES ┆ fal ┆ 0.5 ┆ 0.6 ┆ 1.3 ┆ 1.6 │
│ 233 ┆ 571 ┆ 595 ┆ 802 ┆ 074 ┆ 639 ┆ 856 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆     ┆     ┆     ┆ _As ┆     ┆     ┆     ┆     ┆ se  ┆ 672 ┆ 167 ┆ 109 ┆ 090 │
│ 57  ┆ 28  ┆ 68  ┆ 32  ┆ 77  ┆ 1   ┆ 93  ┆ 1_1 ┆ 1_1 ┆ 1_1 ┆     ┆     ┆     ┆ p34 ┆     ┆     ┆     ┆     ┆     ┆ 78  ┆ 15  ┆ 54  ┆ 23  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_B ┆ 7_B ┆ 7_B ┆     ┆     ┆     ┆ 3As ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P1T ┆ P1T ┆ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_B ┆ 1_B ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 06_ ┆ 06_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ J21 ┆ J21 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.4 ┆ 0.3 ┆ 0.4 ┆ 0.4 ┆ 0.6 ┆ 0.2 ┆ 0.4 ┆ 202 ┆ 202 ┆ 202 ┆ 658 ┆ 232 ┆ G14 ┆ HBD ┆ 658 ┆ 166 ┆ G10 ┆ HBD ┆ fal ┆ 0.5 ┆ 0.4 ┆ 1.0 ┆ 1.3 │
│ 443 ┆ 862 ┆ 680 ┆ 308 ┆ 506 ┆ 844 ┆ 675 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆     ┆     ┆     ┆ _Le ┆     ┆     ┆     ┆     ┆ se  ┆     ┆ 170 ┆     ┆ 975 │
│ 55  ┆ 96  ┆ 04  ┆ 48  ┆ 02  ┆ 83  ┆ 43  ┆ 1_1 ┆ 1_1 ┆ 1_1 ┆     ┆     ┆     ┆ u89 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 85  ┆     ┆ 9   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_B ┆ 7_B ┆ 7_B ┆     ┆     ┆     ┆ Val ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7A1 ┆ 7A1 ┆ 7A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1_ ┆ R1_ ┆ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P2T ┆ P2T ┆ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_G ┆ 3_G ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14_ ┆ 14_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ G10 ┆ G10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 1.0 ┆ 0.9 ┆ 0.9 ┆ 202 ┆ 202 ┆ 202 ┆ 401 ┆ 187 ┆ L18 ┆ EIF ┆ 260 ┆ 103 ┆ F18 ┆ EIF ┆ fal ┆ 0.3 ┆ 0.3 ┆ 1.5 ┆ 1.8 │
│ 999 ┆ 999 ┆ 999 ┆ 962 ┆     ┆ 946 ┆ 973 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆     ┆     ┆     ┆ 2B4 ┆     ┆     ┆     ┆ 2B4 ┆ se  ┆ 933 ┆ 551 ┆ 423 ┆ 155 │
│ 48  ┆ 07  ┆ 49  ┆ 44  ┆     ┆ 52  ┆ 26  ┆ 1_3 ┆ 1_3 ┆ 1_3 ┆     ┆     ┆     ┆ _Al ┆     ┆     ┆     ┆     ┆     ┆ 43  ┆ 72  ┆ 08  ┆ 34  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_B ┆ 1_B ┆ 1_B ┆     ┆     ┆     ┆ a22 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8A1 ┆ 8A1 ┆ 8A1 ┆     ┆     ┆     ┆ 8Va ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R2_ ┆ R2_ ┆ R2_ ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P1T ┆ P1T ┆ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_L ┆ 2_L ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18_ ┆ 18_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ F18 ┆ F18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.5 ┆ 0.5 ┆ 0.5 ┆ 0.5 ┆ 0.5 ┆ 0.6 ┆ 0.5 ┆ 202 ┆ 202 ┆ 202 ┆ 206 ┆ 50  ┆ G21 ┆ STA ┆ 169 ┆ 43  ┆ O19 ┆ STA ┆ fal ┆ 0.4 ┆ 0.4 ┆ 1.2 ┆ 1.1 │
│ 437 ┆ 381 ┆ 753 ┆ 875 ┆ 348 ┆ 4   ┆ 874 ┆ 4_0 ┆ 4_0 ┆ 4_0 ┆     ┆     ┆     ┆ R_A ┆     ┆     ┆     ┆ R   ┆ se  ┆ 506 ┆ 623 ┆ 189 ┆ 627 │
│ 21  ┆ 25  ┆ 27  ┆ 35  ┆ 84  ┆     ┆ 42  ┆ 2_0 ┆ 2_0 ┆ 2_0 ┆     ┆     ┆     ┆ rg1 ┆     ┆     ┆     ┆     ┆     ┆ 67  ┆ 66  ┆ 35  ┆ 91  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5_B ┆ 5_B ┆ 5_B ┆     ┆     ┆     ┆ 82L ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8A1 ┆ 8A1 ┆ 8A1 ┆     ┆     ┆     ┆ eu  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R2_ ┆ R2_ ┆ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P4T ┆ P4T ┆ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4_G ┆ 4_G ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 21_ ┆ 21_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

## Filter the cells passed QC

In [40]:
pass_qc_prof_dir = "../1_snakemake_pipeline/2025_varchamp_snakemake/snakemake_pipeline/outputs/batch_profiles/{}/profiles_tcdropped_filtered_var_mad_outlier_featselect.parquet"

# Get meta features
b7_alleles = (
    pl.scan_parquet(
        pass_qc_prof_dir.format(batches[0])
    )
    .filter(pl.col("Metadata_gene_allele").is_in(all_alleles))
    .with_columns(
        pl.concat_str(
            [
                "Metadata_Plate",
                "Metadata_Well",
                "Metadata_ImageNumber",
                "Metadata_ObjectNumber",
            ],
            separator="_",
        ).alias("Metadata_CellID")
    )
    .select([
        "Metadata_CellID",
        "Metadata_gene_allele",
        "Metadata_Well",
        "Metadata_Plate",
    ])
)

b8_alleles = (
    pl.scan_parquet(
        pass_qc_prof_dir.format(batches[1])
    )
    .filter(pl.col("Metadata_gene_allele").is_in(all_alleles))
    .with_columns(
        pl.concat_str(
            [
                "Metadata_Plate",
                "Metadata_Well",
                "Metadata_ImageNumber",
                "Metadata_ObjectNumber",
            ],
            separator="_",
        ).alias("Metadata_CellID")
    )
    .select([
        "Metadata_CellID",
        "Metadata_gene_allele",
        "Metadata_Well",
        "Metadata_Plate",
    ])
)

cell_alleles = pl.concat([b7_alleles.collect(), b8_alleles.collect()])

In [41]:
prof_dir = "../1_snakemake_pipeline/2025_varchamp_snakemake/snakemake_pipeline/outputs/batch_profiles/{}/profiles.parquet"

b7_prof = pl.scan_parquet(
    prof_dir.format(batches[0])
).with_columns(
    pl.concat_str(
        [
            "Metadata_Plate",
            "Metadata_Well",
            "Metadata_ImageNumber",
            "Metadata_ObjectNumber",
        ],
        separator="_",
    ).alias("Metadata_CellID")
)
b8_prof = pl.scan_parquet(
    prof_dir.format(batches[1])
).with_columns(
    pl.concat_str(
        [
            "Metadata_Plate",
            "Metadata_Well",
            "Metadata_ImageNumber",
            "Metadata_ObjectNumber",
        ],
        separator="_",
    ).alias("Metadata_CellID")
)

gfp_int = [i for i in b7_prof.collect_schema().names() if "Cells_Intensity" in i]
gfp_int = ["Metadata_CellID"] + [i for i in gfp_int if "GFP" in i]

profiles = pl.concat([
    b7_prof.select(gfp_int).collect(),
    b8_prof.select(gfp_int).collect(),
])

# This method of joining ensures that only cells past filters are included in the abundance analysis
profiles = cell_alleles.join(profiles, on="Metadata_CellID", how="left")

In [42]:
well_profiles = (
    profiles.group_by(["Metadata_Plate", "Metadata_Well", "Metadata_gene_allele"])
    .agg(
        pl.col(col).median().alias(col)
        for col in profiles.columns
        if not col.startswith("Metadata_")
    )
    # .drop("Metadata_CellID")
    .unique()
)

well_profiles

shape: (5_833, 18)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Met ┆ Met ┆ Met ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel │
│ ada ┆ ada ┆ ada ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ │
│ ta_ ┆ ta_ ┆ ta_ ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int │
│ Pla ┆ Wel ┆ gen ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens │
│ te  ┆ l   ┆ e_a ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity │
│ --- ┆ --- ┆ lle ┆ _In ┆ _In ┆ _Lo ┆ _MA ┆ _Ma ┆ _Ma ┆ _Ma ┆ _Me ┆ _Me ┆ _Me ┆ _Mi ┆ _Mi ┆ _St ┆ _St ┆ _Up │
│ str ┆ str ┆ le  ┆ teg ┆ teg ┆ wer ┆ DIn ┆ ssD ┆ xIn ┆ xIn ┆ anI ┆ anI ┆ dia ┆ nIn ┆ nIn ┆ dIn ┆ dIn ┆ per │
│     ┆     ┆ --- ┆ rat ┆ rat ┆ Qua ┆ ten ┆ isp ┆ ten ┆ ten ┆ nte ┆ nte ┆ nIn ┆ ten ┆ ten ┆ ten ┆ ten ┆ Qua │
│     ┆     ┆ str ┆ edI ┆ edI ┆ rti ┆ sit ┆ lac ┆ sit ┆ sit ┆ nsi ┆ nsi ┆ ten ┆ sit ┆ sit ┆ sit ┆ sit ┆ rti │
│     ┆     ┆     ┆ nte ┆ nte ┆ leI ┆ y_G ┆ eme ┆ yEd ┆ y_G ┆ tyE ┆ ty_ ┆ sit ┆ yEd ┆ y_G ┆ yEd ┆ y_G ┆ leI │
│     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ H15 ┆ UNC ┆ 0.6 ┆ 12. ┆ 0.0 ┆ 0.0 ┆ 0.4 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 119 ┆ 672 ┆ 993 ┆ 017 ┆ 001 ┆ 178 ┆ 025 ┆ 034 ┆ 018 ┆ 019 ┆ 018 ┆ 015 ┆ 014 ┆ 001 ┆ 001 ┆ 020 │
│ 2_0 ┆     ┆     ┆ 43  ┆ 305 ┆ 92  ┆ 08  ┆ 19  ┆ 41  ┆ 21  ┆ 11  ┆ 02  ┆ 88  ┆ 26  ┆ 65  ┆ 41  ┆ 75  ┆ 04  │
│ 5_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ F21 ┆ PMP ┆ 9.5 ┆ 266 ┆ 0.0 ┆ 0.0 ┆ 2.7 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 22_ ┆ 328 ┆ .03 ┆ 269 ┆ 042 ┆ 094 ┆ 909 ┆ 912 ┆ 257 ┆ 357 ┆ 312 ┆ 043 ┆ 038 ┆ 149 ┆ 153 ┆ 389 │
│ 1_1 ┆     ┆ Ala ┆ 47  ┆ 348 ┆ 12  ┆ 4   ┆ 26  ┆ 5   ┆ 6   ┆ 75  ┆ 93  ┆ 59  ┆ 21  ┆ 54  ┆ 17  ┆ 95  ┆ 36  │
│ 9_B ┆     ┆ 135 ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ Thr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ D11 ┆ TTP ┆ 6.5 ┆ 248 ┆ 0.0 ┆ 0.0 ┆ 3.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ A_A ┆ 423 ┆ .07 ┆ 278 ┆ 143 ┆ 571 ┆ 619 ┆ 935 ┆ 160 ┆ 478 ┆ 423 ┆ 027 ┆ 026 ┆ 103 ┆ 274 ┆ 584 │
│ 2_0 ┆     ┆ rg1 ┆ 23  ┆ 547 ┆ 7   ┆ 34  ┆ 63  ┆ 06  ┆ 19  ┆ 06  ┆ 51  ┆ 96  ┆ 09  ┆ 14  ┆ 22  ┆ 98  ┆ 38  │
│ 5_B ┆     ┆ 92H ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ is  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ O15 ┆ GCK ┆ 1.2 ┆ 37. ┆ 0.0 ┆ 0.0 ┆ 2.9 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _Va ┆ 283 ┆ 866 ┆ 033 ┆ 010 ┆ 873 ┆ 072 ┆ 105 ┆ 026 ┆ 046 ┆ 046 ┆ 015 ┆ 015 ┆ 011 ┆ 017 ┆ 057 │
│ 2_0 ┆     ┆ l25 ┆ 9   ┆ 19  ┆ 82  ┆ 96  ┆ 57  ┆ 92  ┆ 83  ┆ 84  ┆ 6   ┆ 93  ┆ 99  ┆ 94  ┆ 39  ┆ 28  ┆ 66  │
│ 1_B ┆     ┆ 3Al ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ P01 ┆ COM ┆ 0.7 ┆ 15. ┆ 0.0 ┆ 0.0 ┆ 0.4 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ P_A ┆ 868 ┆ 598 ┆ 016 ┆ 000 ┆ 615 ┆ 020 ┆ 021 ┆ 016 ┆ 016 ┆ 016 ┆ 013 ┆ 012 ┆ 001 ┆ 001 ┆ 017 │
│ 1_3 ┆     ┆ la1 ┆ 15  ┆ 635 ┆ 18  ┆ 78  ┆ 15  ┆ 01  ┆ 97  ┆ 43  ┆ 96  ┆ 92  ┆ 29  ┆ 58  ┆ 13  ┆ 18  ┆ 7   │
│ 1_B ┆     ┆ 71T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ hr  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ A14 ┆ HBD ┆ 0.9 ┆ 20. ┆ 0.0 ┆ 0.0 ┆ 1.9 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _As ┆ 759 ┆ 106 ┆ 021 ┆ 003 ┆ 390 ┆ 041 ┆ 057 ┆ 021 ┆ 026 ┆ 025 ┆ 015 ┆ 015 ┆ 004 ┆ 006 ┆ 029 │
│ 1_1 ┆     ┆ n13 ┆ 27  ┆ 093 ┆ 35  ┆ 44  ┆ 39  ┆ 21  ┆ 44  ┆ 75  ┆ 61  ┆ 36  ┆ 45  ┆ 23  ┆ 46  ┆ 87  ┆ 7   │
│ 7_B ┆     ┆ Lys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ P07 ┆ PKP ┆ 1.1 ┆ 24. ┆ 0.0 ┆ 0.0 ┆ 1.6 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 2_M ┆ 557 ┆ 139 ┆ 032 ┆ 003 ┆ 991 ┆ 098 ┆ 157 ┆ 029 ┆ 039 ┆ 036 ┆ 016 ┆ 016 ┆ 011 ┆ 012 ┆ 040 │
│ 1_1 ┆     ┆ et3 ┆ 04  ┆ 853 ┆ 63  ┆ 63  ┆ 14  ┆ 35  ┆ 42  ┆ 47  ┆ 16  ┆ 78  ┆ 08  ┆ 02  ┆ 8   ┆ 25  ┆ 86  │
│ 8_B ┆     ┆ 65I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ le  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ P19 ┆ KCT ┆ 1.2 ┆ 32. ┆ 0.0 ┆ 0.0 ┆ 3.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ D7_ ┆ 066 ┆ 446 ┆ 035 ┆ 012 ┆ 639 ┆ 080 ┆ 185 ┆ 030 ┆ 051 ┆ 046 ┆ 015 ┆ 015 ┆ 014 ┆ 021 ┆ 060 │
│ 1_1 ┆     ┆ Arg ┆ 69  ┆ 731 ┆ 12  ┆ 05  ┆ 68  ┆ 08  ┆ 44  ┆ 32  ┆ 68  ┆ 85  ┆ 9   ┆ 75  ┆ 39  ┆ 84  ┆ 82  │
│ 7_B ┆     ┆ 184 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ Cys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ P17 ┆ DCX ┆ 1.8 ┆ 73. ┆ 0.0 ┆ 0.0 ┆ 3.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _Il ┆ 690 ┆ 781 ┆ 055 ┆ 023 ┆ 004 ┆ 152 ┆ 256 ┆ 037 ┆ 082 ┆ 077 ┆ 016 ┆ 016 ┆ 023 ┆ 035 ┆ 104 │
│ 1_3 ┆     ┆ e21 ┆ 48  ┆ 299 ┆ 33  ┆ 85  ┆ 46  ┆ 14  ┆ 9   ┆ 66  ┆ 13  ┆ 35  ┆ 3   ┆ 3   ┆ 74  ┆ 64  ┆ 23  │
│ 1_B ┆     ┆ 4Th ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ N22 ┆ SFT ┆ 1.0 ┆ 40. ┆ 0.0 ┆ 0.0 ┆ 4.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ PC  ┆ 949 ┆ 604 ┆ 030 ┆ 011 ┆ 429 ┆ 116 ┆ 810 ┆ 026 ┆ 060 ┆ 039 ┆ 015 ┆ 015 ┆ 013 ┆ 068 ┆ 058 │
│ 2_0 ┆     ┆     ┆ 64  ┆ 654 ┆ 88  ┆ 5   ┆ 71  ┆ 02  ┆ 04  ┆ 24  ┆ 19  ┆ 87  ┆ 59  ┆ 41  ┆ 45  ┆ 57  ┆ 99  │
│ 2_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 202 ┆ F11 ┆ PKP ┆ 2.0 ┆ 56. ┆ 0.0 ┆ 0.0 ┆ 2.5 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 2_L ┆ 751 ┆ 533 ┆ 047 ┆ 012 ┆ 987 ┆ 138 ┆ 351 ┆ 046 ┆ 066 ┆ 057 ┆ 017 ┆ 017 ┆ 024 ┆ 031 ┆ 073 │
│ 2_0 ┆     ┆ eu3 ┆ 82  ┆ 915 ┆ 94  ┆ 26  ┆ 27  ┆ 06  ┆ 74  ┆ 75  ┆ 76  ┆ 63  ┆ 64  ┆ 36  ┆ 81  ┆ 86  ┆ 04  │
│ 2_B ┆     ┆ 60P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ ro  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ G10 ┆ HBD ┆ 1.0 ┆ 11. ┆ 0.0 ┆ 0.0 ┆ 0.8 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆     ┆ 523 ┆ 792 ┆ 021 ┆ 002 ┆ 049 ┆ 035 ┆ 046 ┆ 021 ┆ 024 ┆ 023 ┆ 015 ┆ 015 ┆ 003 ┆ 003 ┆ 025 │
│ 2_0 ┆     ┆     ┆ 16  ┆ 943 ┆ 63  ┆ 08  ┆ 79  ┆ 84  ┆ 17  ┆ 98  ┆ 15  ┆ 96  ┆ 82  ┆ 62  ┆ 65  ┆ 4   ┆ 87  │
│ 1_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ D23 ┆ PNP ┆ 4.3 ┆ 120 ┆ 0.0 ┆ 0.0 ┆ 5.4 ┆ 0.0 ┆ 0.5 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ O   ┆ 849 ┆ .90 ┆ 098 ┆ 041 ┆ 376 ┆ 391 ┆ 917 ┆ 106 ┆ 221 ┆ 146 ┆ 025 ┆ 025 ┆ 063 ┆ 468 ┆ 188 │
│ 2_0 ┆     ┆     ┆ 44  ┆ 837 ┆ 91  ┆ 49  ┆ 53  ┆ 46  ┆ 04  ┆ 25  ┆ 66  ┆ 01  ┆ 33  ┆ 2   ┆ 02  ┆ 38  ┆ 54  │
│ 2_B ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ N19 ┆ KCT ┆ 0.8 ┆ 21. ┆ 0.0 ┆ 0.0 ┆ 1.5 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ D7_ ┆ 388 ┆ 338 ┆ 022 ┆ 004 ┆ 975 ┆ 035 ┆ 091 ┆ 019 ┆ 028 ┆ 027 ┆ 015 ┆ 015 ┆ 002 ┆ 007 ┆ 032 │
│ 2_0 ┆     ┆ Asp ┆ 88  ┆ 255 ┆ 98  ┆ 77  ┆ 35  ┆ 36  ┆ 75  ┆ 92  ┆ 16  ┆ 55  ┆ 21  ┆ 11  ┆ 98  ┆ 9   ┆ 93  │
│ 1_B ┆     ┆ 115 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ Tyr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ M20 ┆ TH_ ┆ 1.5 ┆ 53. ┆ 0.0 ┆ 0.0 ┆ 3.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ Gln ┆ 118 ┆ 116 ┆ 050 ┆ 034 ┆ 953 ┆ 159 ┆ 249 ┆ 039 ┆ 091 ┆ 082 ┆ 016 ┆ 016 ┆ 030 ┆ 047 ┆ 123 │
│ 2_0 ┆     ┆ 381 ┆ 53  ┆ 248 ┆ 91  ┆ 9   ┆ 8   ┆ 06  ┆ 39  ┆ 56  ┆ 67  ┆ 89  ┆ 2   ┆ 2   ┆ 51  ┆ 49  ┆ 06  │
│ 2_B ┆     ┆ Lys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ C21 ┆ AIP ┆ 2.3 ┆ 122 ┆ 0.0 ┆ 0.0 ┆ 4.9 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ L1  ┆ 346 ┆ .42 ┆ 081 ┆ 063 ┆ 458 ┆ 232 ┆ 450 ┆ 054 ┆ 157 ┆ 151 ┆ 016 ┆ 016 ┆ 049 ┆ 085 ┆ 216 │
│ 1_1 ┆     ┆     ┆ 04  ┆ 777 ┆ 39  ┆ 42  ┆ 39  ┆ 3   ┆ 67  ┆ 43  ┆ 03  ┆ 21  ┆ 38  ┆ 32  ┆ 31  ┆ 87  ┆ 24  │
│ 7_B ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ F21 ┆ DCX ┆ 3.9 ┆ 221 ┆ 0.0 ┆ 0.0 ┆ 4.1 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _Me ┆ 628 ┆ .39 ┆ 123 ┆ 096 ┆ 599 ┆ 470 ┆ 327 ┆ 098 ┆ 246 ┆ 214 ┆ 017 ┆ 017 ┆ 078 ┆ 176 ┆ 327 │
│ 1_3 ┆     ┆ t1T ┆ 82  ┆ 281 ┆ 4   ┆ 84  ┆ 07  ┆ 48  ┆ 82  ┆ 9   ┆ 35  ┆ 28  ┆ 63  ┆ 63  ┆ 45  ┆ 5   ┆ 34  │
│ 1_B ┆     ┆ hr  ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ M11 ┆ AGX ┆ 3.2 ┆ 117 ┆ 0.0 ┆ 0.0 ┆ 4.5 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ T_P ┆ 158 ┆ .43 ┆ 091 ┆ 045 ┆ 065 ┆ 330 ┆ 482 ┆ 079 ┆ 154 ┆ 144 ┆ 018 ┆ 017 ┆ 070 ┆ 080 ┆ 194 │
│ 1_1 ┆     ┆ ro1 ┆ 47  ┆ 250 ┆ 63  ┆ 47  ┆ 91  ┆ 85  ┆ 11  ┆ 47  ┆ 49  ┆ 56  ┆ 31  ┆ 89  ┆ 22  ┆ 8   ┆ 17  │
│ 7_B ┆     ┆ 1Hi ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ E03 ┆ MIP ┆ 1.8 ┆ 34. ┆ 0.0 ┆ 0.0 ┆ 2.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _Va ┆ 302 ┆ 360 ┆ 039 ┆ 005 ┆ 475 ┆ 112 ┆ 218 ┆ 044 ┆ 049 ┆ 044 ┆ 019 ┆ 018 ┆ 015 ┆ 018 ┆ 053 │
│ 1_1 ┆     ┆ l10 ┆ 93  ┆ 64  ┆ 17  ┆ 24  ┆ 55  ┆ 39  ┆ 37  ┆ 16  ┆ 98  ┆ 53  ┆     ┆ 19  ┆ 64  ┆ 43  ┆ 55  │
│ 9_B ┆     ┆ 7Il ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ E15 ┆ AGX ┆ 1.3 ┆ 34. ┆ 0.0 ┆ 0.0 ┆ 2.5 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ T_S ┆ 185 ┆ 984 ┆ 035 ┆ 010 ┆ 350 ┆ 072 ┆ 112 ┆ 030 ┆ 050 ┆ 048 ┆ 017 ┆ 016 ┆ 011 ┆ 017 ┆ 060 │
│ 1_3 ┆     ┆ er1 ┆ 03  ┆ 597 ┆ 7   ┆ 77  ┆ 37  ┆ 15  ┆ 88  ┆ 26  ┆ 65  ┆ 13  ┆ 15  ┆ 87  ┆ 24  ┆ 32  ┆ 82  │
│ 1_B ┆     ┆ 87P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ he  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

## Calculate abundance hits

In [43]:
import statsmodels.formula.api as smf
from scipy.stats import chi2
from statsmodels.stats.anova import anova_lm

def lmm(dat, fix_var: str, reference: str, var: str, rand_var: str):
    ## basic test
    model = smf.ols(f"{fix_var} ~ C(Metadata_gene_allele, Treatment(reference='{reference}'))", 
                    data=dat)

    ### Also tried a fixed effect model, no improvement, keep it simple
    # fixed_model = smf.ols(f"{fix_var} ~ C(Metadata_gene_allele, Treatment(reference='{reference}')) + C({rand_var})", 
    #                       data=dat).fit()
    ### Not informative due to the large cell counts
    # anova_results = anova_lm(model, fixed_model)
    # print(anova_results)

    ### No significant difference between adding or removing the variable correction
    # print("Fixed model R²:", fixed_model.rsquared_adj)
    # print("Non-fixed model R²:", model.rsquared_adj)
    
    result = model.fit()
    # Extract the summary table for Logit
    summary_table = result.summary2().tables[1]
    # print(pl.DataFrame(summary_table))

    ### mixed LM: ConvergenceWarning: The MLE may be on the boundary of the parameter space. Disgarded
    # model = smf.mixedlm(
    #     formula=f"{fix_var} ~ C(Metadata_gene_allele, Treatment(reference='{reference}'))", ##  + C({rand_var})
    #     data=dat,
    #     groups=dat[rand_var],
    #     re_formula="1" ## Only preserve random intercept, not slope
    # )
    # result = model.fit() ## method='powell' | maxiter=1000, method="bfgs"
    ### Extract the summary table for Logit
    # summary_table = result.summary().tables[1]

    ### format results
    summary_df = pl.DataFrame(summary_table[1:2])
    summary_df = summary_df.with_columns([
        pl.col(column).cast(pl.Float64).alias(column) for column in summary_df.columns
    ])
    summary_df = summary_df.with_columns(
        pl.lit(reference).alias("Gene"), pl.lit(var).alias("Variant")
    )

    return summary_df

In [44]:
from scipy.stats import shapiro
import re
from scipy.stats import wilcoxon
from scipy.stats import ttest_rel
import pandas as pd


# Convert letter rows to numbers
def well_to_coordinates(well):
    row_letter, col_number = re.match(r"([A-P])(\d{2})", well).groups()
    row_index = ord(row_letter) - ord('A') + 1  # Convert 'A'->1, 'B'->2, ..., 'P'->16
    col_index = int(col_number)  # Convert string column to integer
    return well, row_index, col_index


# Compute distances from edges and find the most centered well
def compute_distance(row, col):
    return min(row - 1, 16 - row, col - 1, 24 - col)  # Distance from nearest edge
    

def paired_ttest(dat, reference: str, var: str):
    ## perform stat test
    dat = dat.dropna().sort_values(["Metadata_Plate","Metadata_gene_allele"])
    t_stat, p_val = ttest_rel(dat[dat["Metadata_gene_allele"]==reference]["Cells_Intensity_MedianIntensity_GFP"].values, 
                              dat[dat["Metadata_gene_allele"]==var]["Cells_Intensity_MedianIntensity_GFP"].values)
    summary_df = pl.DataFrame(
        {
            "t_stat": t_stat,
            "p_val": p_val
        }
    )
    summary_df = summary_df.with_columns(
        pl.lit(reference).alias("Gene"), pl.lit(var).alias("Variant")
    )
    return summary_df


well_abun_stats = []
for allele in tqdm(misloc_alleles):
    temp_class = ind_class.filter(pl.col("allele_0") == allele)
    temp_prof = well_profiles.filter(
        (pl.col("Metadata_Plate").is_in(temp_class.select("Plate").to_series()))
        & (
            pl.col("Metadata_Well").is_in(temp_class.select("well_1"))
            | pl.col("Metadata_Well").is_in(temp_class.select("well_0"))
        )
    )
    reference = allele.split("_")[0]

    temp_prof = temp_prof.to_pandas().dropna().sort_values(["Metadata_Plate","Metadata_gene_allele"])
    var_profiles = temp_prof[temp_prof["Metadata_gene_allele"]==allele]
    ref_profiles = temp_prof[temp_prof["Metadata_gene_allele"]==reference]
    
    # print(temp_prof)
    # diff = temp_prof[temp_prof["Metadata_gene_allele"]==allele]["Cells_Intensity_IntegratedIntensityEdge_GFP"].values - \
    #        temp_prof[temp_prof["Metadata_gene_allele"]==reference]["Cells_Intensity_IntegratedIntensityEdge_GFP"].values

    # try:
    if (ref_profiles.shape[0] > var_profiles.shape[0]):
        ref_al_wells = ref_profiles["Metadata_Well"].unique()
        well_coords = [well_to_coordinates(w) for w in set([ref_well_pl for ref_well_pl in ref_al_wells])]
        # Sort wells by max distance from edges (descending)
        most_centered_well = max(well_coords, key=lambda x: compute_distance(x[1], x[2]))[0]
        ref_profiles = temp_prof[(temp_prof["Metadata_gene_allele"]==reference)&(temp_prof["Metadata_Well"]==most_centered_well)]
        
    if (ref_profiles.shape[0] < var_profiles.shape[0]):
        ref_al_wells = var_profiles["Metadata_Well"].unique()
        well_coords = [well_to_coordinates(w) for w in set([ref_well_pl for ref_well_pl in ref_al_wells])]
        # Sort wells by max distance from edges (descending)
        most_centered_well = max(well_coords, key=lambda x: compute_distance(x[1], x[2]))[0]
        var_profiles = temp_prof[(temp_prof["Metadata_gene_allele"]==allele)&(temp_prof["Metadata_Well"]==most_centered_well)]

    well_abun_stats.append(
        paired_ttest(
            dat=pd.concat([ref_profiles, var_profiles]),
            reference=reference,
            var=allele
        )
    )

well_abun_stats = pl.concat(well_abun_stats, how="vertical")
well_abun_stats = well_abun_stats.rename({"t_stat": "U2OS_t"})
well_abun_stats = well_abun_stats.sort(["Gene", "Variant", "U2OS_t", "p_val"])
well_abun_stats

100%|██████████| 610/610 [00:25<00:00, 23.49it/s]

shape: (610, 4)
┌───────────┬──────────┬─────────┬───────────────────┐
│ U2OS_t    ┆ p_val    ┆ Gene    ┆ Variant           │
│ ---       ┆ ---      ┆ ---     ┆ ---               │
│ f64       ┆ f64      ┆ str     ┆ str               │
╞═══════════╪══════════╪═════════╪═══════════════════╡
│ -1.045202 ┆ 0.372731 ┆ ACACB   ┆ ACACB_Val958Met   │
│ 7.045782  ┆ 0.005876 ┆ ACSF3   ┆ ACSF3_Ala197Thr   │
│ 3.177852  ┆ 0.050177 ┆ ACSF3   ┆ ACSF3_Arg10Trp    │
│ 4.021488  ┆ 0.00505  ┆ ACSF3   ┆ ACSF3_Arg471Trp   │
│ 3.393741  ┆ 0.01154  ┆ ACSF3   ┆ ACSF3_Arg558Trp   │
│ 3.888603  ┆ 0.005986 ┆ ACSF3   ┆ ACSF3_Asp457Asn   │
│ 8.580732  ┆ 0.003327 ┆ ACSF3   ┆ ACSF3_Glu359Lys   │
│ 2.012066  ┆ 0.090894 ┆ ACSF3   ┆ ACSF3_Gly119Asp   │
│ 6.571809  ┆ 0.007167 ┆ ACSF3   ┆ ACSF3_Gly225Arg   │
│ 6.226632  ┆ 0.008352 ┆ ACSF3   ┆ ACSF3_Ile200Met   │
│ …         ┆ …        ┆ …       ┆ …                 │
│ -1.194821 ┆ 0.271064 ┆ UBQLN2  ┆ UBQLN2_Pro509Ser  │
│ -1.038171 ┆ 0.333716 ┆ UBQLN2  ┆ UBQLN2_Pro525Ser  │
│ -4.177501 ┆ 0.00583  ┆ UNC119  ┆ UNC119_Gly22Val   │
│ 3.204131  ┆ 0.01498  ┆ UROD    ┆ UROD_Gly318Arg    │
│ 2.251634  ┆ 0.059056 ┆ WRAP53  ┆ WRAP53_Arg398Trp  │
│ 0.283658  ┆ 0.790749 ┆ WRAP53  ┆ WRAP53_Arg68Gly   │
│ -7.289098 ┆ 0.000164 ┆ XPA     ┆ XPA_Cys108Phe     │
│ 3.294121  ┆ 0.013227 ┆ XRCC2   ┆ XRCC2_Phe270Val   │
│ -5.117635 ┆ 0.002183 ┆ ZMYND10 ┆ ZMYND10_Arg243Cys │
│ 1.684929  ┆ 0.142983 ┆ ZMYND10 ┆ ZMYND10_Arg340Gln │
└───────────┴──────────┴─────────┴───────────────────┘

In [46]:
well_abun_stats.write_csv("../../3_outputs/abundance/abundance_ttest_stats.csv")