# Protein abundance change

This notebook runs the analyses on protein abundance changes between variant and reference alleles using Cell Painting assays

In [ ]:
### imports
import os
import polars as pl
import numpy as np
from tqdm import tqdm
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

## Disable truncation globally
pl.Config.set_tbl_rows(20)  # Show all rows
pl.Config.set_tbl_cols(40)  # Show all columns

%matplotlib inline

## Threshold for training imbalance: 
## filtered out any variant-reference pair where there was a class imbalance of more than 3-fold
thresh = 3

# min_class_num = 2
# ## define control types
# TC = ["EGFP"]
# NC = ["RHEB", "MAPK9", "PRKACB", "SLIRP"]
# PC = ["ALK", "ALK_Arg1275Gln", "PTK2B"]
# cNC = ["Renilla"]
# cPC = ["KRAS", "PTK2B", "GHSR", "ABL1", "BRD4", "OPRM1", "RB1", "ADA", "WT PMP22", "LYN", "TNF", 
#        "CYP2A6", "CSK", "PAK1", "ALDH2", "CHRM3", "KCNQ2", "ALK T1151M", "PRKCE", "LPAR1", "PLP1"]

## XGB classifier metrics

In [2]:
# Paths
metrics_dir = "../1_snakemake_pipeline/2025_varchamp_snakemake/snakemake_pipeline/outputs/analyses/{}/profiles_tcdropped_filtered_var_mad_outlier_featselect"
batches = ["2024_01_23_Batch_7", "2024_02_06_Batch_8"]

metrics_df, metrics_wtvar = pl.DataFrame(), pl.DataFrame()
for batch in batches:
    met_dir = metrics_dir.format(batch)
    metrics_df_batch = pl.read_csv(f"{met_dir}/metrics.csv")
    metrics_wtvar_batch = pl.read_csv(f"{met_dir}/metrics_summary.csv")

    metrics_df = pl.concat([metrics_df, metrics_df_batch])
    metrics_wtvar = pl.concat([metrics_wtvar, metrics_wtvar_batch])

In [5]:
## get the localization metrics
local_wtvar = metrics_wtvar.filter(pl.col("Classifier_type") == "localization")

## get the alleles and their reference genes
local_wtvar = local_wtvar.with_columns(
    pl.when(pl.col("AUROC_mean") > pl.col("AUROC_thresh"))
    .then(1)
    .otherwise(0)
    .alias("mislocalized")
).unique()
misloc_alleles = (
    local_wtvar
    .select("allele_0")
    .to_series()
    .to_list()
)
misloc_wt = (
    local_wtvar
    .with_columns(pl.col("allele_0").str.replace("_.*", "").alias("wt"))
    .select("wt")
    .to_series()
    .unique()
    .to_list()
)
all_alleles = misloc_alleles + misloc_wt

## get individual classifiers pass the training imbalance threshold
ind_class = metrics_df.filter(
    (~pl.col("Metadata_Control"))
    & (pl.col("Training_imbalance") < thresh)
    & (
        (pl.col("Full_Classifier_ID").str.contains("true"))
        & pl.col("allele_0").is_in(misloc_alleles)
    )
)

## CellProfiler Features

### Get the CP features for cells that passed the QC

In [7]:
pass_qc_prof_dir = "../1_snakemake_pipeline/2025_varchamp_snakemake/snakemake_pipeline/outputs/batch_profiles/{}/profiles_tcdropped_filtered_var_mad_outlier_featselect.parquet"

# Get meta features
b7_alleles = (
    pl.scan_parquet(
        pass_qc_prof_dir.format(batches[0])
    )
    .filter(pl.col("Metadata_gene_allele").is_in(all_alleles))
    .with_columns(
        pl.concat_str(
            [
                "Metadata_Plate",
                "Metadata_Well",
                "Metadata_ImageNumber",
                "Metadata_ObjectNumber",
            ],
            separator="_",
        ).alias("Metadata_CellID")
    )
    .select([
        "Metadata_CellID",
        "Metadata_gene_allele",
        "Metadata_Well",
        "Metadata_Plate",
    ])
)

b8_alleles = (
    pl.scan_parquet(
        pass_qc_prof_dir.format(batches[1])
    )
    .filter(pl.col("Metadata_gene_allele").is_in(all_alleles))
    .with_columns(
        pl.concat_str(
            [
                "Metadata_Plate",
                "Metadata_Well",
                "Metadata_ImageNumber",
                "Metadata_ObjectNumber",
            ],
            separator="_",
        ).alias("Metadata_CellID")
    )
    .select([
        "Metadata_CellID",
        "Metadata_gene_allele",
        "Metadata_Well",
        "Metadata_Plate",
    ])
)

cell_alleles = pl.concat([b7_alleles.collect(), b8_alleles.collect()])

### Get the Cells_Intensity CP features per all cells

Merge the Cells_Intensity features to the pass-QC cells

In [8]:
prof_dir = "../1_snakemake_pipeline/2025_varchamp_snakemake/snakemake_pipeline/outputs/batch_profiles/{}/profiles.parquet"

b7_prof = pl.scan_parquet(
    prof_dir.format(batches[0])
).with_columns(
    pl.concat_str(
        [
            "Metadata_Plate",
            "Metadata_Well",
            "Metadata_ImageNumber",
            "Metadata_ObjectNumber",
        ],
        separator="_",
    ).alias("Metadata_CellID")
)
b8_prof = pl.scan_parquet(
    prof_dir.format(batches[1])
).with_columns(
    pl.concat_str(
        [
            "Metadata_Plate",
            "Metadata_Well",
            "Metadata_ImageNumber",
            "Metadata_ObjectNumber",
        ],
        separator="_",
    ).alias("Metadata_CellID")
)

gfp_int = [i for i in b7_prof.collect_schema().names() if "Cells_Intensity" in i]
gfp_int = ["Metadata_CellID"] + [i for i in gfp_int if "GFP" in i]

profiles = pl.concat([
    b7_prof.select(gfp_int).collect(),
    b8_prof.select(gfp_int).collect(),
])

# This method of joining ensures that only cells past filters are included in the abundance analysis
profiles = cell_alleles.join(profiles, on="Metadata_CellID", how="left")

### Aggregate the cells to well profiles

In [21]:
well_profiles = (
    profiles.group_by(["Metadata_Plate", "Metadata_Well", "Metadata_gene_allele"])
    .agg(
        pl.col(col).median().alias(col)
        for col in profiles.columns
        if not col.startswith("Metadata_")
    )
    # .drop("Metadata_CellID")
    .unique()
)

well_profiles

shape: (5_833, 18)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Met ┆ Met ┆ Met ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel ┆ Cel │
│ ada ┆ ada ┆ ada ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ ┆ ls_ │
│ ta_ ┆ ta_ ┆ ta_ ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int ┆ Int │
│ Pla ┆ Wel ┆ gen ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens │
│ te  ┆ l   ┆ e_a ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity ┆ ity │
│ --- ┆ --- ┆ lle ┆ _In ┆ _In ┆ _Lo ┆ _MA ┆ _Ma ┆ _Ma ┆ _Ma ┆ _Me ┆ _Me ┆ _Me ┆ _Mi ┆ _Mi ┆ _St ┆ _St ┆ _Up │
│ str ┆ str ┆ le  ┆ teg ┆ teg ┆ wer ┆ DIn ┆ ssD ┆ xIn ┆ xIn ┆ anI ┆ anI ┆ dia ┆ nIn ┆ nIn ┆ dIn ┆ dIn ┆ per │
│     ┆     ┆ --- ┆ rat ┆ rat ┆ Qua ┆ ten ┆ isp ┆ ten ┆ ten ┆ nte ┆ nte ┆ nIn ┆ ten ┆ ten ┆ ten ┆ ten ┆ Qua │
│     ┆     ┆ str ┆ edI ┆ edI ┆ rti ┆ sit ┆ lac ┆ sit ┆ sit ┆ nsi ┆ nsi ┆ ten ┆ sit ┆ sit ┆ sit ┆ sit ┆ rti │
│     ┆     ┆     ┆ nte ┆ nte ┆ leI ┆ y_G ┆ eme ┆ yEd ┆ y_G ┆ tyE ┆ ty_ ┆ sit ┆ yEd ┆ y_G ┆ yEd ┆ y_G ┆ leI │
│     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ F13 ┆ PLA ┆ 1.0 ┆ 29. ┆ 0.0 ┆ 0.0 ┆ 1.7 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 2G6 ┆ 883 ┆ 757 ┆ 030 ┆ 009 ┆ 781 ┆ 037 ┆ 105 ┆ 022 ┆ 041 ┆ 038 ┆ 015 ┆ 015 ┆ 003 ┆ 015 ┆ 052 │
│ 2_0 ┆     ┆ _Gl ┆ 61  ┆ 551 ┆ 06  ┆ 58  ┆ 41  ┆ 65  ┆ 45  ┆ 09  ┆ 9   ┆ 81  ┆ 75  ┆ 75  ┆ 86  ┆ 39  ┆ 21  │
│ 2_B ┆     ┆ u56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ 7Ly ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ E18 ┆ PDG ┆ 0.8 ┆ 17. ┆ 0.0 ┆ 0.0 ┆ 0.7 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ FRB ┆ 167 ┆ 543 ┆ 021 ┆ 001 ┆ 379 ┆ 025 ┆ 051 ┆ 019 ┆ 023 ┆ 022 ┆ 014 ┆ 014 ┆ 001 ┆ 003 ┆ 024 │
│ 1_1 ┆     ┆ _Le ┆ 13  ┆ 378 ┆ 24  ┆ 6   ┆ 83  ┆ 26  ┆ 46  ┆ 76  ┆ 66  ┆ 46  ┆ 9   ┆ 39  ┆ 94  ┆ 12  ┆ 32  │
│ 8_B ┆     ┆ u65 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ 8Pr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ N23 ┆ KRT ┆ 0.8 ┆ 26. ┆ 0.0 ┆ 0.0 ┆ 3.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 2_G ┆ 223 ┆ 520 ┆ 021 ┆ 007 ┆ 831 ┆ 053 ┆ 443 ┆ 020 ┆ 042 ┆ 029 ┆ 014 ┆ 013 ┆ 005 ┆ 040 ┆ 040 │
│ 1_1 ┆     ┆ ly2 ┆ 82  ┆ 131 ┆ 54  ┆ 26  ┆ 71  ┆ 36  ┆ 38  ┆ 02  ┆ 15  ┆ 17  ┆ 08  ┆ 9   ┆ 29  ┆ 1   ┆ 12  │
│ 7_B ┆     ┆ 19A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ sp  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ P14 ┆ LIG ┆ 0.7 ┆ 13. ┆ 0.0 ┆ 0.0 ┆ 0.3 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 4   ┆ 515 ┆ 316 ┆ 017 ┆ 000 ┆ 443 ┆ 021 ┆ 023 ┆ 017 ┆ 018 ┆ 018 ┆ 014 ┆ 014 ┆ 001 ┆ 001 ┆ 019 │
│ 2_0 ┆     ┆     ┆ 69  ┆ 699 ┆ 47  ┆ 8   ┆ 93  ┆ 6   ┆ 57  ┆ 94  ┆ 26  ┆ 24  ┆ 6   ┆ 08  ┆ 15  ┆ 21  ┆ 04  │
│ 1_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ O21 ┆ MVK ┆ 3.0 ┆ 126 ┆ 0.0 ┆ 0.0 ┆ 4.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _Hi ┆ 668 ┆ .41 ┆ 095 ┆ 052 ┆ 944 ┆ 327 ┆ 492 ┆ 070 ┆ 166 ┆ 146 ┆ 017 ┆ 017 ┆ 063 ┆ 091 ┆ 214 │
│ 1_1 ┆     ┆ s20 ┆ 07  ┆ 302 ┆ 16  ┆ 84  ┆ 1   ┆ 3   ┆ 63  ┆ 71  ┆ 82  ┆ 29  ┆ 76  ┆ 54  ┆ 86  ┆ 7   ┆ 14  │
│ 8_B ┆     ┆ Gln ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ I22 ┆ THA ┆ 0.7 ┆ 16. ┆ 0.0 ┆ 0.0 ┆ 1.9 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ P1_ ┆ 092 ┆ 792 ┆ 018 ┆ 002 ┆ 260 ┆ 024 ┆ 058 ┆ 017 ┆ 022 ┆ 020 ┆ 014 ┆ 013 ┆ 001 ┆ 007 ┆ 023 │
│ 2_0 ┆     ┆ Val ┆ 46  ┆ 42  ┆ 55  ┆ 17  ┆ 55  ┆ 71  ┆ 55  ┆ 89  ┆ 98  ┆ 38  ┆ 12  ┆ 8   ┆ 56  ┆ 44  ┆ 21  │
│ 2_B ┆     ┆ 193 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ Ile ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ D11 ┆ TTP ┆ 2.3 ┆ 97. ┆ 0.0 ┆ 0.0 ┆ 4.4 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ A_A ┆ 772 ┆ 067 ┆ 067 ┆ 043 ┆ 712 ┆ 216 ┆ 428 ┆ 056 ┆ 128 ┆ 117 ┆ 019 ┆ 018 ┆ 040 ┆ 072 ┆ 178 │
│ 1_1 ┆     ┆ rg1 ┆ 01  ┆ 289 ┆ 56  ┆ 83  ┆ 28  ┆ 39  ┆ 46  ┆ 8   ┆ 54  ┆ 05  ┆ 1   ┆ 66  ┆ 47  ┆ 99  ┆ 59  │
│ 9_B ┆     ┆ 92H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ is  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ E18 ┆ CDC ┆ 0.6 ┆ 18. ┆ 0.0 ┆ 0.0 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 73  ┆ 707 ┆ 703 ┆ 017 ┆ 001 ┆ 386 ┆ 021 ┆ 108 ┆ 017 ┆ 027 ┆ 018 ┆ 014 ┆ 013 ┆ 001 ┆ 020 ┆ 020 │
│ 1_1 ┆     ┆     ┆ 41  ┆ 289 ┆ 37  ┆ 21  ┆ 63  ┆ 87  ┆ 59  ┆ 6   ┆ 34  ┆ 45  ┆ 28  ┆ 72  ┆ 23  ┆ 6   ┆ 3   │
│ 7_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ H04 ┆ DES ┆ 0.8 ┆ 41. ┆ 0.0 ┆ 0.0 ┆ 5.1 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _Al ┆ 294 ┆ 964 ┆ 019 ┆ 008 ┆ 520 ┆ 054 ┆ 653 ┆ 019 ┆ 067 ┆ 026 ┆ 013 ┆ 013 ┆ 006 ┆ 157 ┆ 049 │
│ 1_1 ┆     ┆ a23 ┆ 59  ┆ 079 ┆ 87  ┆ 16  ┆ 37  ┆ 8   ┆ 31  ┆ 86  ┆ 16  ┆ 9   ┆ 91  ┆ 66  ┆ 14  ┆ 11  ┆ 5   │
│ 7_B ┆     ┆ 7Th ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ B06 ┆ DES ┆ 1.2 ┆ 100 ┆ 0.0 ┆ 0.0 ┆ 9.7 ┆ 0.0 ┆ 0.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _As ┆ 249 ┆ .43 ┆ 022 ┆ 017 ┆ 458 ┆ 183 ┆ 811 ┆ 026 ┆ 143 ┆ 037 ┆ 014 ┆ 014 ┆ 023 ┆ 310 ┆ 081 │
│ 1_3 ┆     ┆ p34 ┆ 57  ┆ 118 ┆ 26  ┆ 79  ┆ 27  ┆ 22  ┆ 46  ┆ 61  ┆ 96  ┆ 16  ┆ 38  ┆ 14  ┆ 7   ┆ 22  ┆ 7   │
│ 1_B ┆     ┆ 3As ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 202 ┆ G23 ┆ MYO ┆ 1.3 ┆ 30. ┆ 0.0 ┆ 0.0 ┆ 2.4 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ Z2_ ┆ 633 ┆ 958 ┆ 030 ┆ 006 ┆ 200 ┆ 083 ┆ 182 ┆ 030 ┆ 041 ┆ 037 ┆ 017 ┆ 016 ┆ 010 ┆ 016 ┆ 046 │
│ 2_0 ┆     ┆ Gln ┆ 09  ┆ 088 ┆ 68  ┆ 29  ┆ 98  ┆ 9   ┆ 36  ┆ 13  ┆ 16  ┆ 43  ┆ 27  ┆ 99  ┆ 19  ┆ 24  ┆ 56  │
│ 2_B ┆     ┆ 10P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ ro  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ I17 ┆ GCM ┆ 0.6 ┆ 17. ┆ 0.0 ┆ 0.0 ┆ 2.7 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 2   ┆ 625 ┆ 048 ┆ 017 ┆ 001 ┆ 148 ┆ 022 ┆ 077 ┆ 018 ┆ 024 ┆ 018 ┆ 014 ┆ 014 ┆ 001 ┆ 012 ┆ 021 │
│ 1_1 ┆     ┆     ┆ 74  ┆ 455 ┆ 9   ┆ 31  ┆ 64  ┆ 33  ┆ 11  ┆ 01  ┆ 82  ┆ 97  ┆ 58  ┆ 1   ┆ 24  ┆ 81  ┆ 62  │
│ 7_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P2T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ B13 ┆ TUF ┆ 0.7 ┆ 19. ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ M   ┆ 568 ┆ 490 ┆ 020 ┆ 004 ┆ 709 ┆ 040 ┆ 108 ┆ 019 ┆ 028 ┆ 023 ┆ 015 ┆ 014 ┆ 003 ┆ 013 ┆ 032 │
│ 2_0 ┆     ┆     ┆ 95  ┆ 803 ┆ 23  ┆ 24  ┆ 29  ┆ 07  ┆ 35  ┆ 99  ┆ 64  ┆ 52  ┆ 04  ┆ 76  ┆ 42  ┆ 63  ┆ 68  │
│ 2_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ B14 ┆ PYG ┆ 1.0 ┆ 23. ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ L_T ┆ 795 ┆ 140 ┆ 026 ┆ 007 ┆ 250 ┆ 052 ┆ 078 ┆ 025 ┆ 036 ┆ 033 ┆ 016 ┆ 016 ┆ 006 ┆ 012 ┆ 042 │
│ 2_0 ┆     ┆ yr8 ┆ 64  ┆ 072 ┆ 43  ┆ 78  ┆ 84  ┆ 02  ┆ 89  ┆ 65  ┆ 33  ┆ 85  ┆ 09  ┆ 01  ┆ 57  ┆ 14  ┆ 88  │
│ 2_B ┆     ┆ 21H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ is  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ A18 ┆ TH_ ┆ 1.8 ┆ 61. ┆ 0.0 ┆ 0.0 ┆ 3.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ Ala ┆ 909 ┆ 784 ┆ 041 ┆ 025 ┆ 279 ┆ 123 ┆ 210 ┆ 037 ┆ 069 ┆ 062 ┆ 017 ┆ 017 ┆ 022 ┆ 034 ┆ 097 │
│ 2_0 ┆     ┆ 226 ┆ 85  ┆ 91  ┆ 49  ┆     ┆ 66  ┆ 03  ┆ 13  ┆ 46  ┆ 83  ┆ 84  ┆ 24  ┆ 24  ┆ 32  ┆ 96  ┆ 11  │
│ 2_B ┆     ┆ Thr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ K19 ┆ AGX ┆ 1.5 ┆ 19. ┆ 0.0 ┆ 0.0 ┆ 1.6 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ T_A ┆ 075 ┆ 848 ┆ 038 ┆ 010 ┆ 359 ┆ 072 ┆ 122 ┆ 034 ┆ 052 ┆ 050 ┆ 019 ┆ 019 ┆ 010 ┆ 014 ┆ 062 │
│ 1_3 ┆     ┆ rg1 ┆ 89  ┆ 877 ┆ 19  ┆ 94  ┆ 5   ┆ 77  ┆ 06  ┆ 58  ┆ 1   ┆ 44  ┆ 42  ┆ 34  ┆ 33  ┆ 77  ┆ 53  │
│ 1_B ┆     ┆ 97G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ ln  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P1T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ M17 ┆ MVK ┆ 3.8 ┆ 99. ┆ 0.0 ┆ 0.0 ┆ 3.9 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _Va ┆ 012 ┆ 126 ┆ 090 ┆ 048 ┆ 336 ┆ 312 ┆ 428 ┆ 087 ┆ 151 ┆ 136 ┆ 021 ┆ 020 ┆ 061 ┆ 077 ┆ 196 │
│ 1_1 ┆     ┆ l27 ┆ 66  ┆ 219 ┆ 36  ┆ 8   ┆ 56  ┆ 82  ┆ 36  ┆ 66  ┆ 95  ┆ 92  ┆ 73  ┆ 92  ┆ 14  ┆ 17  ┆ 19  │
│ 9_B ┆     ┆ 8Me ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ B08 ┆ ACA ┆ 0.4 ┆ 4.1 ┆ 0.0 ┆ 0.0 ┆ 0.4 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ CB  ┆ 146 ┆ 437 ┆ 018 ┆ 001 ┆ 266 ┆ 021 ┆ 024 ┆ 017 ┆ 019 ┆ 019 ┆ 014 ┆ 014 ┆ 001 ┆ 001 ┆ 020 │
│ 2_0 ┆     ┆     ┆ 82  ┆ 78  ┆ 47  ┆ 08  ┆ 33  ┆ 05  ┆ 75  ┆ 83  ┆ 72  ┆ 7   ┆ 71  ┆ 65  ┆ 19  ┆ 65  ┆ 89  │
│ 2_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P4T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ P01 ┆ PKP ┆ 0.8 ┆ 15. ┆ 0.0 ┆ 0.0 ┆ 0.6 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ 2_T ┆ 573 ┆ 253 ┆ 016 ┆ 000 ┆ 234 ┆ 021 ┆ 024 ┆ 017 ┆ 017 ┆ 017 ┆ 013 ┆ 013 ┆ 001 ┆ 001 ┆ 018 │
│ 1_1 ┆     ┆ hr2 ┆ 73  ┆ 005 ┆ 96  ┆ 85  ┆ 12  ┆ 3   ┆ 32  ┆ 22  ┆ 98  ┆ 84  ┆ 86  ┆ 44  ┆ 17  ┆ 31  ┆ 82  │
│ 8_B ┆     ┆ 42M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7A1 ┆     ┆ et  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ J18 ┆ RP2 ┆ 11. ┆ 244 ┆ 0.0 ┆ 0.0 ┆ 2.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4_0 ┆     ┆ _Ar ┆ 294 ┆ .22 ┆ 199 ┆ 016 ┆ 579 ┆ 674 ┆ 864 ┆ 219 ┆ 231 ┆ 222 ┆ 045 ┆ 043 ┆ 104 ┆ 075 ┆ 255 │
│ 2_0 ┆     ┆ g28 ┆ 788 ┆ 626 ┆ 58  ┆ 3   ┆ 52  ┆ 97  ┆ 58  ┆ 33  ┆ 06  ┆ 46  ┆ 25  ┆ 37  ┆ 42  ┆ 08  ┆ 45  │
│ 2_B ┆     ┆ 2Tr ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8A1 ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ R2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ P3T ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

## Calculate abundance hits

Use paired t-test to call abundance hits

In [23]:
from scipy.stats import shapiro
import re
from scipy.stats import wilcoxon
from scipy.stats import ttest_rel
import pandas as pd


# Convert letter rows to numbers
def well_to_coordinates(well):
    row_letter, col_number = re.match(r"([A-P])(\d{2})", well).groups()
    row_index = ord(row_letter) - ord('A') + 1  # Convert 'A'->1, 'B'->2, ..., 'P'->16
    col_index = int(col_number)  # Convert string column to integer
    return well, row_index, col_index


# Compute distances from edges and find the most centered well
def compute_distance(row, col):
    return min(row - 1, 16 - row, col - 1, 24 - col)  # Distance from nearest edge
    

def paired_ttest(dat, reference: str, var: str):
    ## perform stat test
    dat = dat.dropna().sort_values(["Metadata_Plate","Metadata_gene_allele"])

    # Assuming well_abun_stats is a DataFrame with columns 'reference_abundance' and 'variant_abundance'
    reference_abundance = dat[dat["Metadata_gene_allele"]==reference]["Cells_Intensity_MedianIntensity_GFP"].values
    variant_abundance = dat[dat["Metadata_gene_allele"]==var]["Cells_Intensity_MedianIntensity_GFP"].values
    t_stat, p_val = ttest_rel(variant_abundance, reference_abundance)

    # Calculate Cohen's d
    mean_diff = np.mean(variant_abundance) - np.mean(reference_abundance)
    pooled_std = np.sqrt((np.std(variant_abundance, ddof=1) ** 2 + np.std(reference_abundance, ddof=1) ** 2) / 2)
    cohen_d = mean_diff / pooled_std
    summary_df = pl.DataFrame(
        {
            "t_stat": t_stat,
            "p_val": p_val,
            "cohen_d": cohen_d
        }
    )
    summary_df = summary_df.with_columns(
        pl.lit(reference).alias("Gene"), pl.lit(var).alias("Variant")
    )
    return summary_df



well_abun_stats = []
for allele in tqdm(misloc_alleles):
    temp_class = ind_class.filter(pl.col("allele_0") == allele)
    temp_prof = well_profiles.filter(
        (pl.col("Metadata_Plate").is_in(temp_class.select("Plate").to_series()))
        & (
            pl.col("Metadata_Well").is_in(temp_class.select("well_1"))
            | pl.col("Metadata_Well").is_in(temp_class.select("well_0"))
        )
    )
    reference = allele.split("_")[0]

    temp_prof = temp_prof.to_pandas().dropna().sort_values(["Metadata_Plate","Metadata_gene_allele"])
    var_profiles = temp_prof[temp_prof["Metadata_gene_allele"]==allele]
    ref_profiles = temp_prof[temp_prof["Metadata_gene_allele"]==reference]
    
    # print(temp_prof)
    # diff = temp_prof[temp_prof["Metadata_gene_allele"]==allele]["Cells_Intensity_IntegratedIntensityEdge_GFP"].values - \
    #        temp_prof[temp_prof["Metadata_gene_allele"]==reference]["Cells_Intensity_IntegratedIntensityEdge_GFP"].values

    # try:
    if (ref_profiles.shape[0] > var_profiles.shape[0]):
        ref_al_wells = ref_profiles["Metadata_Well"].unique()
        well_coords = [well_to_coordinates(w) for w in set([ref_well_pl for ref_well_pl in ref_al_wells])]
        # Sort wells by max distance from edges (descending)
        most_centered_well = max(well_coords, key=lambda x: compute_distance(x[1], x[2]))[0]
        ref_profiles = temp_prof[(temp_prof["Metadata_gene_allele"]==reference)&(temp_prof["Metadata_Well"]==most_centered_well)]
        
    if (ref_profiles.shape[0] < var_profiles.shape[0]):
        ref_al_wells = var_profiles["Metadata_Well"].unique()
        well_coords = [well_to_coordinates(w) for w in set([ref_well_pl for ref_well_pl in ref_al_wells])]
        # Sort wells by max distance from edges (descending)
        most_centered_well = max(well_coords, key=lambda x: compute_distance(x[1], x[2]))[0]
        var_profiles = temp_prof[(temp_prof["Metadata_gene_allele"]==allele)&(temp_prof["Metadata_Well"]==most_centered_well)]

    well_abun_stats.append(
        paired_ttest(
            dat=pd.concat([ref_profiles, var_profiles]),
            reference=reference,
            var=allele
        )
    )

well_abun_stats = pl.concat(well_abun_stats, how="vertical")
well_abun_stats = well_abun_stats.rename({"t_stat": "U2OS_t"})
well_abun_stats = well_abun_stats.sort(["Gene", "Variant", "U2OS_t", "p_val", "cohen_d"])
well_abun_stats

100%|██████████| 1126/1126 [00:44<00:00, 25.33it/s]

shape: (1_126, 5)
┌───────────┬──────────┬───────────┬─────────┬───────────────────┐
│ U2OS_t    ┆ p_val    ┆ cohen_d   ┆ Gene    ┆ Variant           │
│ ---       ┆ ---      ┆ ---       ┆ ---     ┆ ---               │
│ f64       ┆ f64      ┆ f64       ┆ str     ┆ str               │
╞═══════════╪══════════╪═══════════╪═════════╪═══════════════════╡
│ 1.045202  ┆ 0.372731 ┆ 0.421038  ┆ ACACB   ┆ ACACB_Val958Met   │
│ -7.045782 ┆ 0.005876 ┆ -2.871654 ┆ ACSF3   ┆ ACSF3_Ala197Thr   │
│ -3.177852 ┆ 0.050177 ┆ -1.535075 ┆ ACSF3   ┆ ACSF3_Arg10Trp    │
│ -4.021488 ┆ 0.00505  ┆ -1.550507 ┆ ACSF3   ┆ ACSF3_Arg471Trp   │
│ -4.021488 ┆ 0.00505  ┆ -1.550507 ┆ ACSF3   ┆ ACSF3_Arg471Trp   │
│ -3.393741 ┆ 0.01154  ┆ -1.503345 ┆ ACSF3   ┆ ACSF3_Arg558Trp   │
│ -3.393741 ┆ 0.01154  ┆ -1.503345 ┆ ACSF3   ┆ ACSF3_Arg558Trp   │
│ -3.888603 ┆ 0.005986 ┆ -1.497214 ┆ ACSF3   ┆ ACSF3_Asp457Asn   │
│ -3.888603 ┆ 0.005986 ┆ -1.497214 ┆ ACSF3   ┆ ACSF3_Asp457Asn   │
│ -8.580732 ┆ 0.003327 ┆ -2.926313 ┆ ACSF3   ┆ ACSF3_Glu359Lys   │
│ …         ┆ …        ┆ …         ┆ …       ┆ …                 │
│ -2.251634 ┆ 0.059056 ┆ -0.67888  ┆ WRAP53  ┆ WRAP53_Arg398Trp  │
│ -0.283658 ┆ 0.790749 ┆ -0.189176 ┆ WRAP53  ┆ WRAP53_Arg68Gly   │
│ 7.289098  ┆ 0.000164 ┆ 2.205804  ┆ XPA     ┆ XPA_Cys108Phe     │
│ 7.289098  ┆ 0.000164 ┆ 2.205804  ┆ XPA     ┆ XPA_Cys108Phe     │
│ -3.294121 ┆ 0.013227 ┆ -0.804944 ┆ XRCC2   ┆ XRCC2_Phe270Val   │
│ -3.294121 ┆ 0.013227 ┆ -0.804944 ┆ XRCC2   ┆ XRCC2_Phe270Val   │
│ 5.117635  ┆ 0.002183 ┆ 1.562477  ┆ ZMYND10 ┆ ZMYND10_Arg243Cys │
│ 5.117635  ┆ 0.002183 ┆ 1.562477  ┆ ZMYND10 ┆ ZMYND10_Arg243Cys │
│ -1.684929 ┆ 0.142983 ┆ -0.920977 ┆ ZMYND10 ┆ ZMYND10_Arg340Gln │
│ -1.684929 ┆ 0.142983 ┆ -0.920977 ┆ ZMYND10 ┆ ZMYND10_Arg340Gln │
└───────────┴──────────┴───────────┴─────────┴───────────────────┘

In [24]:
well_abun_stats.write_csv("../../3_outputs/abundance/abundance_ttest_stats.csv")