# Download and preprocess dbNSFP Variant Files

Convert the variant .gz files to parquet files for faster processing and merge with our ClinVar annotations

In [17]:
import os
import polars as pl
import pandas as pd
# import concurrent.futures

## Get the prediction scores from dbNSFP

Using scripts/data_processing.sh to download data from https://drive.google.com/file/d/1HNoZUswadC1ODavU7AUvm0DZ13jKVFKW/view

In [ ]:
## Test reading in a chr variant file
# chr_num = "22"
# df_chr = pl.read_csv(f'../dbnsfp_data/dbNSFP5.0/dbNSFP5.0a/dbNSFP5.0a_variant.chr{chr_num}.gz', 
#                     separator='\t',
#                     n_threads=16,
#                     infer_schema_length=100000,
#                     ignore_errors=True,
#                     truncate_ragged_lines=True, 
#                     # n_rows=5,
#                     low_memory=False)
# df_chr_par = pl.scan_parquet(f"../dbnsfp_data/dbNSFP5.0/dbNSFP5.0a/dbNSFP5.0a_variant.chr{chr_num}.parquet")
# df_chr_par = df_chr_par.filter(pl.col("clinvar_id")!='.')

## Convert the chr variant files to parquet

__For easier accessing and processing__

In [6]:
# def convert_to_parquet(chr_num):
#     file_path = f"../1_inputs/raw_data/dbNSFP5.0a/dbNSFP5.0a_variant.chr{chr_num}.gz"
#     df = pl.read_csv(file_path, 
#                      separator='\t',
#                      n_threads=16,
#                      infer_schema_length=1000000,
#                      ignore_errors=True,
#                      truncate_ragged_lines=True,
#                      low_memory=False)
#     df = df.with_columns(
#         pl.col("aaref").replace(aa_single_to_three).alias("aaref_3"),
#         pl.col("aaalt").replace(aa_single_to_three).alias("aaalt_3"),
#     )
#     parquet_path = f"../1_inputs/raw_data/dbNSFP5.0a/dbNSFP5.0a_variant.chr{chr_num}.parquet"
#     df.write_parquet(parquet_path)
#     return parquet_path

# chr_num_list = [chr_file.split('.')[-2].split('chr')[-1] for chr_file in os.listdir('../1_inputs/raw_data/dbNSFP5.0a') if "chr" in chr_file and chr_file.endswith(".gz")]

# # Use ThreadPoolExecutor for parallel processing
# with concurrent.futures.ThreadPoolExecutor() as executor:
#     futures = [executor.submit(convert_to_parquet, chr_num) for chr_num in chr_num_list]
    
#     # Collect the results
#     parquet_files = [future.result() for future in concurrent.futures.as_completed(futures)]

# print("Conversion to Parquet completed.")

## Get the original ClinVar Annotations

Merging the most up-to-date clinvar annotations to dbNSFP for consistency

In [4]:
processed_clinvar_parq = "../../1_allele_collection/3_outputs/processed_data/clinvar/clinvar_processed.parquet"
clinvar = pl.scan_parquet(processed_clinvar_parq)

In [13]:
clinvar.select(pl.col("Type")).unique().collect().to_numpy()

array([['Microsatellite'],
       ['single nucleotide variant'],
       ['Insertion'],
       ['Variation'],
       ['copy number loss'],
       ['Indel'],
       ['Deletion'],
       ['Complex'],
       ['copy number gain'],
       ['Translocation'],
       ['Duplication'],
       ['Inversion']], dtype=object)

In [14]:
clinvar.collect().shape

(3390885, 47)

In [10]:
clinvar_snv = clinvar.filter(pl.col("Type")=='single nucleotide variant') ##.select(pl.col("Type")).unique().collect().to_numpy()
clinvar_snv.collect().shape

(3105660, 47)

In [15]:
clinvar_snv.collect()

shape: (3_105_660, 47)
┌───────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ #AlleleID ┆ Type       ┆ Name       ┆ GeneID ┆ … ┆ SPDI      ┆ RefSeq_mR ┆ StarStatu ┆ clinvar_c │
│ ---       ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---       ┆ NA        ┆ s         ┆ lnsig_cle │
│ i64       ┆ str        ┆ str        ┆ i64    ┆   ┆ str       ┆ ---       ┆ ---       ┆ an        │
│           ┆            ┆            ┆        ┆   ┆           ┆ str       ┆ i32       ┆ ---       │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ cat       │
╞═══════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 15043     ┆ single     ┆ NM_014630. ┆ 9640   ┆ … ┆ NC_000015 ┆ NM_014630 ┆ null      ┆ 4_VUS     │
│           ┆ nucleotide ┆ 3(ZNF592): ┆        ┆   ┆ .10:84799 ┆ .3        ┆           ┆           │
│           ┆ variant    ┆ c.3136G>A  ┆        ┆   ┆ 209:G:A   ┆           ┆           ┆           │
│           ┆            ┆ …          ┆        ┆   ┆           ┆           ┆           ┆           │
│ 15044     ┆ single     ┆ NM_017547. ┆ 55572  ┆ … ┆ NC_000011 ┆ NM_017547 ┆ 2         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(FOXRED1) ┆        ┆   ┆ .10:12627 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ :c.694C>T  ┆        ┆   ┆ 5389:C:T  ┆           ┆           ┆           │
│           ┆            ┆ …          ┆        ┆   ┆           ┆           ┆           ┆           │
│ 15045     ┆ single     ┆ NM_017547. ┆ 55572  ┆ … ┆ NC_000011 ┆ NM_017547 ┆ 1         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(FOXRED1) ┆        ┆   ┆ .10:12627 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ :c.1289A>G ┆        ┆   ┆ 7517:A:G  ┆           ┆           ┆           │
│           ┆            ┆ …          ┆        ┆   ┆           ┆           ┆           ┆           │
│ 15046     ┆ single     ┆ NM_025152. ┆ 80224  ┆ … ┆ NC_000014 ┆ NM_025152 ┆ 1         ┆ 3_Conflic │
│           ┆ nucleotide ┆ 3(NUBPL):c ┆        ┆   ┆ .9:315621 ┆ .3        ┆           ┆ ting      │
│           ┆ variant    ┆ .166G>A    ┆        ┆   ┆ 25:G:A    ┆           ┆           ┆           │
│           ┆            ┆ (p…        ┆        ┆   ┆           ┆           ┆           ┆           │
│ 15048     ┆ single     ┆ NM_000410. ┆ 3077   ┆ … ┆ NC_000006 ┆ NM_000410 ┆ 2         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(HFE):c.8 ┆        ┆   ┆ .12:26092 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ 45G>A      ┆        ┆   ┆ 913:G:A   ┆           ┆           ┆           │
│           ┆            ┆ (p.C…      ┆        ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …          ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3883408   ┆ single     ┆ NM_004615. ┆ 7102   ┆ … ┆ NC_000023 ┆ NM_004615 ┆ 1         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(TSPAN7): ┆        ┆   ┆ .11:38671 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ c.271-1G>T ┆        ┆   ┆ 375:G:T   ┆           ┆           ┆           │
│ 3883411   ┆ single     ┆ NM_000161. ┆ 2643   ┆ … ┆ NC_000014 ┆ NM_000161 ┆ 1         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 3(GCH1):c. ┆        ┆   ┆ .9:548441 ┆ .3        ┆           ┆ nic       │
│           ┆ variant    ┆ 667A>G     ┆        ┆   ┆ 03:T:C    ┆           ┆           ┆           │
│           ┆            ┆ (p.…       ┆        ┆   ┆           ┆           ┆           ┆           │
│ 3883412   ┆ single     ┆ NM_014714. ┆ 9742   ┆ … ┆ NC_000016 ┆ NM_014714 ┆ 1         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(IFT140): ┆        ┆   ┆ .10:15267 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ c.2471T>C  ┆        ┆   ┆ 25:A:G    ┆           ┆           ┆           │
│           ┆            ┆ …          ┆        ┆   ┆           ┆           ┆           ┆           │
│ 3883413   ┆ single     ┆ NM_000404. ┆ 2720   ┆ … ┆ NC_000003 ┆ NM_000404 ┆ null      ┆ 5_Others  │
│           ┆ nucleotide ┆ 4(GLB1):c. ┆        ┆   ┆ .12:33051 ┆ .4        ┆           ┆           │
│           ┆ variant    ┆ 890T>G     ┆        ┆   ┆ 907:A:C   ┆           ┆           ┆           │
│           ┆            ┆ (p.…       ┆        ┆   ┆           ┆           ┆           ┆           │
│ 3883417   ┆ single     ┆ NM_000039. ┆ 335    ┆ … ┆ NC_000011 ┆ NM_000039 ┆ null      ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 3(APOA1):c ┆        ┆   ┆ .10:11683 ┆ .3        ┆           ┆ nic       │
│           ┆ variant    ┆ .130G>T    ┆        ┆   ┆ 7071:C:A  ┆           ┆           ┆           │
│           ┆            ┆ (p…        ┆        ┆   ┆           ┆           ┆           ┆           │
└───────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [22]:
clinvar_snv.filter(pl.col("VariationID")==2333487).collect()

shape: (1, 47)
┌───────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ #AlleleID ┆ Type       ┆ Name       ┆ GeneID ┆ … ┆ SPDI      ┆ RefSeq_mR ┆ StarStatu ┆ clinvar_c │
│ ---       ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---       ┆ NA        ┆ s         ┆ lnsig_cle │
│ i64       ┆ str        ┆ str        ┆ i64    ┆   ┆ str       ┆ ---       ┆ ---       ┆ an        │
│           ┆            ┆            ┆        ┆   ┆           ┆ str       ┆ i32       ┆ ---       │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ cat       │
╞═══════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2324965   ┆ single     ┆ NM_199261. ┆ 7179   ┆ … ┆ NC_000021 ┆ NM_199261 ┆ 1         ┆ 4_VUS     │
│           ┆ nucleotide ┆ 4(TPTE):c. ┆        ┆   ┆ .9:105411 ┆ .4        ┆           ┆           │
│           ┆ variant    ┆ 37G>C      ┆        ┆   ┆ 37:G:C    ┆           ┆           ┆           │
│           ┆            ┆ (p.V…      ┆        ┆   ┆           ┆           ┆           ┆           │
└───────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
chr_num_list = [chr_file.split('.')[-2].split('chr')[-1] for chr_file in os.listdir('./raw_inputs/dbNSFP5.0a/') if "chr" in chr_file and chr_file.endswith(".gz")]
clin_var_dfs = []
for chr_num in chr_num_list:
    df_chr_par = pl.scan_parquet(f"./raw_inputs/dbNSFP5.0a/dbNSFP5.0a_variant.chr{chr_num}.parquet")
    df_chr_par_clinvar = df_chr_par.filter(pl.col("clinvar_id")!='.')
    clinvar_per_chr = clinvar_snv.filter(pl.col("Chromosome")==chr_num)#.collect()
    clinvar_per_chr = clinvar_per_chr.with_columns(pl.col("VariationID").cast(pl.String).alias("clinvar_id"))
    df_chr_par_clinvar = df_chr_par_clinvar.join(clinvar_per_chr, on="clinvar_id", how="left")
    df_chr_par_clinvar = df_chr_par_clinvar.collect()
    clin_var_dfs.append(df_chr_par_clinvar)

StringCacheMismatchError: cannot compare categoricals coming from different sources, consider setting a global StringCache.

Help: if you're using Python, this may look something like:

    with pl.StringCache():
        # Initialize Categoricals.
        df1 = pl.DataFrame({'a': ['1', '2']}, schema={'a': pl.Categorical})
        df2 = pl.DataFrame({'a': ['1', '3']}, schema={'a': pl.Categorical})
    # Your operations go here.
    pl.concat([df1, df2])

Alternatively, if the performance cost is acceptable, you could just set:

    import polars as pl
    pl.enable_string_cache()

on startup.

In [ ]:
df_clinvar = pl.concat(clin_var_dfs, how="vertical_relaxed")

# parquet_path = f"../dbnsfp_data/dbNSFP5.0/dbNSFP5.0a/dbNSFP5.0a_variant.clin_var_annot.parquet"
# df_clinvar.write_parquet(parquet_path)

StringCacheMismatchError: cannot compare categoricals coming from different sources, consider setting a global StringCache.

Help: if you're using Python, this may look something like:

    with pl.StringCache():
        # Initialize Categoricals.
        df1 = pl.DataFrame({'a': ['1', '2']}, schema={'a': pl.Categorical})
        df2 = pl.DataFrame({'a': ['1', '3']}, schema={'a': pl.Categorical})
    # Your operations go here.
    pl.concat([df1, df2])

Alternatively, if the performance cost is acceptable, you could just set:

    import polars as pl
    pl.enable_string_cache()

on startup.