# Download and Preprocess dbNSFP Variant Files

Convert the variant .gz files to parquet files for faster processing and merge with our ClinVar annotations

In [1]:
import os
import polars as pl
import pandas as pd

## 1. dbNSFP

### 1.1 Get the prediction scores from 

Using ../1_inputs/download_data.sh to download data from https://drive.google.com/file/d/1HNoZUswadC1ODavU7AUvm0DZ13jKVFKW/view

### 1.2 Convert the chr variant files to parquet

__For easier accessing and processing__

In [ ]:
# def convert_to_parquet(chr_num):
#     file_path = f"../1_inputs/raw_inputs/dbNSFP5.0a/dbNSFP5.0a_variant.chr{chr_num}.gz"
#     df = pl.read_csv(file_path, 
#                      separator='\t',
#                      n_threads=16,
#                      infer_schema_length=1000000,
#                      ignore_errors=True,
#                      truncate_ragged_lines=True,
#                      low_memory=False)
#     df = df.with_columns(
#         pl.col("aaref").replace(aa_single_to_three).alias("aaref_3"),
#         pl.col("aaalt").replace(aa_single_to_three).alias("aaalt_3"),
#     )
#     parquet_path = f"../1_inputs/raw_inputs/dbNSFP5.0a/dbNSFP5.0a_variant.chr{chr_num}.parquet"
#     df.write_parquet(parquet_path)
#     return parquet_path

# chr_num_list = [chr_file.split('.')[-2].split('chr')[-1] for chr_file in os.listdir('../1_inputs/raw_inputs/dbNSFP5.0a') if "chr" in chr_file and chr_file.endswith(".gz")]
# # Use ThreadPoolExecutor for parallel processing
# with concurrent.futures.ThreadPoolExecutor() as executor:
#     futures = [executor.submit(convert_to_parquet, chr_num) for chr_num in chr_num_list]
#     # Collect the results
#     parquet_files = [future.result() for future in concurrent.futures.as_completed(futures)]

# print("Conversion to Parquet completed.")

### 1.3 Merge with ClinVar

Merging the most up-to-date clinvar annotations (ClinVar variants released on 2024-03-01 and the data is accessed on March 13, 2025) to dbNSFP dataset for consistency.

#### Get the original ClinVar Annotations

Please refer to ```../../1_allele_collection/1_inputs/download_clinvar_gnomad.ipynb``` for more details about ClinVar annotations.

In [2]:
processed_clinvar_parq = "../../1_allele_collection/3_outputs/processed_data/clinvar/clinvar_processed.parquet"
clinvar = pl.scan_parquet(processed_clinvar_parq)

In [4]:
clinvar.select(pl.col("Type")).unique().collect().to_numpy()

array([['Duplication'],
       ['copy number gain'],
       ['Microsatellite'],
       ['Translocation'],
       ['Insertion'],
       ['Deletion'],
       ['Indel'],
       ['Inversion'],
       ['Complex'],
       ['single nucleotide variant'],
       ['copy number loss'],
       ['Variation']], dtype=object)

In [5]:
clinvar.collect().shape

(3390885, 47)

In [3]:
clinvar_snv = clinvar.filter(pl.col("Type")=='single nucleotide variant') ##.select(pl.col("Type")).unique().collect().to_numpy()
clinvar_snv.collect().shape

(3105660, 47)

In [4]:
clinvar_snv.collect()

shape: (3_105_660, 47)
┌───────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ #AlleleID ┆ Type       ┆ Name       ┆ GeneID ┆ … ┆ SPDI      ┆ RefSeq_mR ┆ StarStatu ┆ clinvar_c │
│ ---       ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---       ┆ NA        ┆ s         ┆ lnsig_cle │
│ i64       ┆ str        ┆ str        ┆ i64    ┆   ┆ str       ┆ ---       ┆ ---       ┆ an        │
│           ┆            ┆            ┆        ┆   ┆           ┆ str       ┆ i32       ┆ ---       │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ cat       │
╞═══════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 15043     ┆ single     ┆ NM_014630. ┆ 9640   ┆ … ┆ NC_000015 ┆ NM_014630 ┆ null      ┆ 4_VUS     │
│           ┆ nucleotide ┆ 3(ZNF592): ┆        ┆   ┆ .10:84799 ┆ .3        ┆           ┆           │
│           ┆ variant    ┆ c.3136G>A  ┆        ┆   ┆ 209:G:A   ┆           ┆           ┆           │
│           ┆            ┆ …          ┆        ┆   ┆           ┆           ┆           ┆           │
│ 15044     ┆ single     ┆ NM_017547. ┆ 55572  ┆ … ┆ NC_000011 ┆ NM_017547 ┆ 2         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(FOXRED1) ┆        ┆   ┆ .10:12627 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ :c.694C>T  ┆        ┆   ┆ 5389:C:T  ┆           ┆           ┆           │
│           ┆            ┆ …          ┆        ┆   ┆           ┆           ┆           ┆           │
│ 15045     ┆ single     ┆ NM_017547. ┆ 55572  ┆ … ┆ NC_000011 ┆ NM_017547 ┆ 1         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(FOXRED1) ┆        ┆   ┆ .10:12627 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ :c.1289A>G ┆        ┆   ┆ 7517:A:G  ┆           ┆           ┆           │
│           ┆            ┆ …          ┆        ┆   ┆           ┆           ┆           ┆           │
│ 15046     ┆ single     ┆ NM_025152. ┆ 80224  ┆ … ┆ NC_000014 ┆ NM_025152 ┆ 1         ┆ 3_Conflic │
│           ┆ nucleotide ┆ 3(NUBPL):c ┆        ┆   ┆ .9:315621 ┆ .3        ┆           ┆ ting      │
│           ┆ variant    ┆ .166G>A    ┆        ┆   ┆ 25:G:A    ┆           ┆           ┆           │
│           ┆            ┆ (p…        ┆        ┆   ┆           ┆           ┆           ┆           │
│ 15048     ┆ single     ┆ NM_000410. ┆ 3077   ┆ … ┆ NC_000006 ┆ NM_000410 ┆ 2         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(HFE):c.8 ┆        ┆   ┆ .12:26092 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ 45G>A      ┆        ┆   ┆ 913:G:A   ┆           ┆           ┆           │
│           ┆            ┆ (p.C…      ┆        ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …          ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3883408   ┆ single     ┆ NM_004615. ┆ 7102   ┆ … ┆ NC_000023 ┆ NM_004615 ┆ 1         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(TSPAN7): ┆        ┆   ┆ .11:38671 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ c.271-1G>T ┆        ┆   ┆ 375:G:T   ┆           ┆           ┆           │
│ 3883411   ┆ single     ┆ NM_000161. ┆ 2643   ┆ … ┆ NC_000014 ┆ NM_000161 ┆ 1         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 3(GCH1):c. ┆        ┆   ┆ .9:548441 ┆ .3        ┆           ┆ nic       │
│           ┆ variant    ┆ 667A>G     ┆        ┆   ┆ 03:T:C    ┆           ┆           ┆           │
│           ┆            ┆ (p.…       ┆        ┆   ┆           ┆           ┆           ┆           │
│ 3883412   ┆ single     ┆ NM_014714. ┆ 9742   ┆ … ┆ NC_000016 ┆ NM_014714 ┆ 1         ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 4(IFT140): ┆        ┆   ┆ .10:15267 ┆ .4        ┆           ┆ nic       │
│           ┆ variant    ┆ c.2471T>C  ┆        ┆   ┆ 25:A:G    ┆           ┆           ┆           │
│           ┆            ┆ …          ┆        ┆   ┆           ┆           ┆           ┆           │
│ 3883413   ┆ single     ┆ NM_000404. ┆ 2720   ┆ … ┆ NC_000003 ┆ NM_000404 ┆ null      ┆ 5_Others  │
│           ┆ nucleotide ┆ 4(GLB1):c. ┆        ┆   ┆ .12:33051 ┆ .4        ┆           ┆           │
│           ┆ variant    ┆ 890T>G     ┆        ┆   ┆ 907:A:C   ┆           ┆           ┆           │
│           ┆            ┆ (p.…       ┆        ┆   ┆           ┆           ┆           ┆           │
│ 3883417   ┆ single     ┆ NM_000039. ┆ 335    ┆ … ┆ NC_000011 ┆ NM_000039 ┆ null      ┆ 1_Pathoge │
│           ┆ nucleotide ┆ 3(APOA1):c ┆        ┆   ┆ .10:11683 ┆ .3        ┆           ┆ nic       │
│           ┆ variant    ┆ .130G>T    ┆        ┆   ┆ 7071:C:A  ┆           ┆           ┆           │
│           ┆            ┆ (p…        ┆        ┆   ┆           ┆           ┆           ┆           │
└───────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [22]:
clinvar_snv.filter(pl.col("VariationID")==2333487).collect()

shape: (1, 47)
┌───────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ #AlleleID ┆ Type       ┆ Name       ┆ GeneID ┆ … ┆ SPDI      ┆ RefSeq_mR ┆ StarStatu ┆ clinvar_c │
│ ---       ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---       ┆ NA        ┆ s         ┆ lnsig_cle │
│ i64       ┆ str        ┆ str        ┆ i64    ┆   ┆ str       ┆ ---       ┆ ---       ┆ an        │
│           ┆            ┆            ┆        ┆   ┆           ┆ str       ┆ i32       ┆ ---       │
│           ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆ cat       │
╞═══════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2324965   ┆ single     ┆ NM_199261. ┆ 7179   ┆ … ┆ NC_000021 ┆ NM_199261 ┆ 1         ┆ 4_VUS     │
│           ┆ nucleotide ┆ 4(TPTE):c. ┆        ┆   ┆ .9:105411 ┆ .4        ┆           ┆           │
│           ┆ variant    ┆ 37G>C      ┆        ┆   ┆ 37:G:C    ┆           ┆           ┆           │
│           ┆            ┆ (p.V…      ┆        ┆   ┆           ┆           ┆           ┆           │
└───────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
clinvar_snv_collect = clinvar_snv.collect()
clinvar_snv_collect["VariationID"].unique()

shape: (3_104_976,)
Series: 'VariationID' [i64]
[
	4
	5
	6
	9
	10
	…
	3767244
	3767247
	3767248
	3767249
	3767253
]

#### Merge dbNSFP and ClinVar

dbNSFP and ClinVar datasets were merged together using ```VariantionID``` (ClinVar) and ```clinvar_id``` (dbNSFP), which are the unique identifier for each variant.

In [ ]:
%%time

# with pl.StringCache():
#     chr_num_list = [chr_file.split('.')[-2].split('chr')[-1] for chr_file in os.listdir('./raw_inputs/dbNSFP5.0a/') if "chr" in chr_file and chr_file.endswith(".gz")]
#     clin_var_dfs = []
#     for chr_num in chr_num_list:
#         df_chr_par = pl.scan_parquet(f"./raw_inputs/dbNSFP5.0a/dbNSFP5.0a_variant.chr{chr_num}.parquet")
#         df_chr_par_clinvar = df_chr_par.filter(pl.col("clinvar_id")!='.')
#         clinvar_per_chr = clinvar_snv.filter(pl.col("Chromosome")==chr_num)#.collect()
#         clinvar_per_chr = clinvar_per_chr.with_columns(pl.col("VariationID").cast(pl.String).alias("clinvar_id"))
#         df_chr_par_clinvar = df_chr_par_clinvar.join(clinvar_per_chr, on="clinvar_id", how="left")
#         df_chr_par_clinvar = df_chr_par_clinvar.collect()
#         clin_var_dfs.append(df_chr_par_clinvar)

#     df_clinvar = pl.concat(clin_var_dfs, how="vertical_relaxed") ## 
#     parquet_path = f"../3_outputs/processed_data/dbnsfp/dbNSFP5.0a_variant.clin_var_re-annot.parquet"
#     df_clinvar.write_parquet(parquet_path)

CPU times: user 45min 17s, sys: 36min 5s, total: 1h 21min 23s
Wall time: 1min 22s

## 2. Deduplicate the variants

### 2.1 Explode variants

Many variants exist on multiple isoforms and are all aggregated together, and we need to split them apart for easier analyses.

In [12]:
df_clinvar = pl.scan_parquet("../3_outputs/processed_data/dbnsfp/dbNSFP5.0a_variant.clin_var_re-annot.parquet")
# For testing purposes, limit to a small subset:
df_clin_subset = df_clinvar.limit(10)
# Collect the subset into an eager DataFrame for inspection
df_clin_subset = df_clin_subset.collect()

# Automatically detect columns with semicolon-separated patterns.
# We only check columns of Utf8 (string) type.
pattern_cols = [
    col for col in df_clinvar.collect_schema() 
    if df_clin_subset[col].dtype == pl.Utf8 and df_clin_subset[col].str.contains(";").any()
]
print("Columns containing ';':", pattern_cols)

df_clinvar_exploded = df_clinvar.with_columns(
    [pl.col(col).str.split(";").alias(col) for col in pattern_cols]
).explode(pattern_cols)

# df_clinvar_exploded.collect()

Columns containing ';': ['aapos', 'genename', 'Ensembl_geneid', 'Ensembl_transcriptid', 'Ensembl_proteinid', 'Uniprot_acc', 'Uniprot_entry', 'HGVSc_snpEff', 'HGVSp_snpEff', 'HGVSc_VEP', 'HGVSp_VEP', 'APPRIS', 'GENCODE_basic', 'TSL', 'VEP_canonical', 'MANE', 'cds_strand', 'refcodon', 'codonpos', 'codon_degeneracy', 'SIFT_score', 'SIFT_pred', 'SIFT4G_score', 'SIFT4G_pred', 'Polyphen2_HDIV_score', 'Polyphen2_HDIV_pred', 'Polyphen2_HVAR_score', 'Polyphen2_HVAR_pred', 'MutationTaster_score', 'MutationTaster_pred', 'MutationTaster_model', 'MutationTaster_trees_benign', 'MutationTaster_trees_deleterious', 'MutationAssessor_score', 'MutationAssessor_pred', 'PROVEAN_score', 'PROVEAN_pred', 'VEST4_score', 'MetaRNN_score', 'MetaRNN_pred', 'REVEL_score', 'MutPred_score', 'MutPred_protID', 'MutPred_AAchange', 'MutPred_Top5features', 'MVP_score', 'gMVP_score', 'MPC_score', 'DEOGEN2_score', 'DEOGEN2_pred', 'LIST-S2_score', 'LIST-S2_pred', 'VARITY_R_score', 'VARITY_ER_score', 'VARITY_R_LOO_score', 'VARITY_ER_LOO_score', 'ESM1b_score', 'ESM1b_pred', 'AlphaMissense_score', 'AlphaMissense_pred', 'PHACTboost_score', 'Aloft_Fraction_transcripts_affected', 'Aloft_prob_Tolerant', 'Aloft_prob_Recessive', 'Aloft_prob_Dominant', 'Aloft_pred', 'Aloft_Confidence', 'Interpro_domain']

shape: (7_475_238, 429)
┌──────┬──────────────┬─────┬─────┬───┬───────────────┬───────────────┬────────────┬───────────────┐
│ #chr ┆ pos(1-based) ┆ ref ┆ alt ┆ … ┆ SPDI          ┆ RefSeq_mRNA   ┆ StarStatus ┆ clinvar_clnsi │
│ ---  ┆ ---          ┆ --- ┆ --- ┆   ┆ ---           ┆ ---           ┆ ---        ┆ g_clean       │
│ str  ┆ i64          ┆ str ┆ str ┆   ┆ str           ┆ str           ┆ i32        ┆ ---           │
│      ┆              ┆     ┆     ┆   ┆               ┆               ┆            ┆ cat           │
╞══════╪══════════════╪═════╪═════╪═══╪═══════════════╪═══════════════╪════════════╪═══════════════╡
│ 21   ┆ 10541137     ┆ G   ┆ C   ┆ … ┆ NC_000021.9:1 ┆ NM_199261.4   ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 0541137:G:C   ┆               ┆            ┆               │
│ 21   ┆ 10541137     ┆ G   ┆ C   ┆ … ┆ NC_000021.9:1 ┆ NM_199261.4   ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 0541137:G:C   ┆               ┆            ┆               │
│ 21   ┆ 10541137     ┆ G   ┆ C   ┆ … ┆ NC_000021.9:1 ┆ NM_199261.4   ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 0541137:G:C   ┆               ┆            ┆               │
│ 21   ┆ 10541137     ┆ G   ┆ C   ┆ … ┆ NC_000021.9:1 ┆ NM_199261.4   ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 0541137:G:C   ┆               ┆            ┆               │
│ 21   ┆ 10552695     ┆ C   ┆ G   ┆ … ┆ NC_000021.9:1 ┆ NM_199261.4   ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 0552695:C:G   ┆               ┆            ┆               │
│ …    ┆ …            ┆ …   ┆ …   ┆ … ┆ …             ┆ …             ┆ …          ┆ …             │
│ 4    ┆ 190027191    ┆ T   ┆ G   ┆ … ┆ NC_000004.12: ┆ NM_001286820. ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 190027191:T:G ┆ 2             ┆            ┆               │
│ 4    ┆ 190027191    ┆ T   ┆ G   ┆ … ┆ NC_000004.12: ┆ NM_001286820. ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 190027191:T:G ┆ 2             ┆            ┆               │
│ 4    ┆ 190174726    ┆ T   ┆ A   ┆ … ┆ NC_000004.12: ┆ NM_001306068. ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 190174726:T:A ┆ 3             ┆            ┆               │
│ 4    ┆ 190174726    ┆ T   ┆ A   ┆ … ┆ NC_000004.12: ┆ NM_001306068. ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 190174726:T:A ┆ 3             ┆            ┆               │
│ 4    ┆ 190174726    ┆ T   ┆ A   ┆ … ┆ NC_000004.12: ┆ NM_001306068. ┆ 1          ┆ 4_VUS         │
│      ┆              ┆     ┆     ┆   ┆ 190174726:T:A ┆ 3             ┆            ┆               │
└──────┴──────────────┴─────┴─────┴───┴───────────────┴───────────────┴────────────┴───────────────┘

### 2.2 De-duplicate them 

__By prioritizing the uniprot_id with a .pdb structure inferred by AF2__

In [ ]:
def deduplicate_by_uniprot_lazy(ldf, preferred_uniprot_acc):
    # Create window specs for our operations
    window_spec = pl.col("clinvar_id")
    
    with pl.StringCache():
        # Add useful columns for filtering in a single pass:
        # 1. Count occurrences of each clinvar_id
        # 2. Check if Uniprot_acc is preferred
        # 3. Check if Uniprot_acc has no dash
        # 4. Create row number within each group to use for selection
        enhanced_ldf = ldf.with_columns([
            pl.col("clinvar_id").count().over(window_spec).alias("group_count"),
            pl.col("Uniprot_acc").is_in(preferred_uniprot_acc).alias("is_preferred"),
            (~pl.col("Uniprot_acc").str.contains("-")).alias("no_dash"),
            pl.col("Uniprot_acc").rank("dense").over(window_spec).alias("row_rank")
        ])
        
        # For non-duplicated entries - keep all
        non_duplicated = enhanced_ldf.filter(pl.col("group_count") == 1)
        
        # For duplicated entries, we'll create a priority column and then use that for selection
        duplicated = enhanced_ldf.filter(pl.col("group_count") > 1)

        # Create a priority column (1=preferred, 2=no dash, 3=other)
        prioritized = duplicated.with_columns([
            pl.when(pl.col("is_preferred"))
            .then(pl.lit(1))
            .when(pl.col("no_dash"))
            .then(pl.lit(2))
            .otherwise(pl.lit(3))
            .alias("priority")
        ])

        # Sort by priority and take the first record for each ID
        deduped = (
            prioritized
            .sort(["clinvar_id", "priority", "row_rank"])
            .group_by("clinvar_id")
            .agg(
                pl.all().exclude(["group_count", "is_preferred", "no_dash", "row_rank", "priority"]).first()
            )
        )

    deduped_df = pl.concat([non_duplicated.drop(["group_count", "is_preferred", "no_dash", "row_rank"]).select(pl.col(deduped.collect_schema().names())),
    deduped], how="vertical_relaxed")
    
    # Combine all results
    return deduped_df

uniprot_ids = [f.split('-')[1] for f in os.listdir("../1_inputs/raw_inputs/alphafold/UP000005640_9606_HUMAN_v4") if f.endswith("pdb.gz")]
## Let's prioritize the variants with PDB structures
df_clinvar_dedup_struct = deduplicate_by_uniprot_lazy(df_clinvar_exploded, uniprot_ids)

In [ ]:
# with pl.StringCache():
#     df_clinvar_dedup_struct.collect().write_parquet(f"../3_outputs/processed_data/dbnsfp/dbNSFP5.0a_variant.clin_var_re-annot_pdb_variants.parquet")

In [27]:
df_clinvar_dedup_struct = pl.scan_parquet("../3_outputs/processed_data/dbnsfp/dbNSFP5.0a_variant.clin_var_re-annot_pdb_variants.parquet")
df_clinvar_dedup_struct.collect()

shape: (1_649_580, 429)
┌────────────┬──────┬─────────────┬─────┬───┬─────────────┬─────────────┬────────────┬─────────────┐
│ clinvar_id ┆ #chr ┆ pos(1-based ┆ ref ┆ … ┆ SPDI        ┆ RefSeq_mRNA ┆ StarStatus ┆ clinvar_cln │
│ ---        ┆ ---  ┆ )           ┆ --- ┆   ┆ ---         ┆ ---         ┆ ---        ┆ sig_clean   │
│ str        ┆ str  ┆ ---         ┆ str ┆   ┆ str         ┆ str         ┆ i32        ┆ ---         │
│            ┆      ┆ i64         ┆     ┆   ┆             ┆             ┆            ┆ cat         │
╞════════════╪══════╪═════════════╪═════╪═══╪═════════════╪═════════════╪════════════╪═════════════╡
│ 2361281    ┆ 21   ┆ 13628442    ┆ G   ┆ … ┆ NC_000021.9 ┆ NM_174981.6 ┆ 1          ┆ 4_VUS       │
│            ┆      ┆             ┆     ┆   ┆ :13628442:G ┆             ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ :T          ┆             ┆            ┆             │
│ 2599176    ┆ 21   ┆ 13630941    ┆ G   ┆ … ┆ NC_000021.9 ┆ NM_174981.6 ┆ 1          ┆ 4_VUS       │
│            ┆      ┆             ┆     ┆   ┆ :13630941:G ┆             ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ :T          ┆             ┆            ┆             │
│ 2486768    ┆ 21   ┆ 13630977    ┆ G   ┆ … ┆ NC_000021.9 ┆ NM_174981.6 ┆ 1          ┆ 2_Benign    │
│            ┆      ┆             ┆     ┆   ┆ :13630977:G ┆             ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ :A          ┆             ┆            ┆             │
│ 2277922    ┆ 21   ┆ 13631057    ┆ A   ┆ … ┆ NC_000021.9 ┆ NM_174981.6 ┆ 1          ┆ 4_VUS       │
│            ┆      ┆             ┆     ┆   ┆ :13631057:A ┆             ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ :C          ┆             ┆            ┆             │
│ 3308991    ┆ 21   ┆ 13639588    ┆ A   ┆ … ┆ NC_000021.9 ┆ NM_174981.6 ┆ 1          ┆ 4_VUS       │
│            ┆      ┆             ┆     ┆   ┆ :13639588:A ┆             ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ :T          ┆             ┆            ┆             │
│ …          ┆ …    ┆ …           ┆ …   ┆ … ┆ …           ┆ …           ┆ …          ┆ …           │
│ 999991     ┆ 9    ┆ 35089109    ┆ G   ┆ … ┆ NC_000009.1 ┆ NM_032634.4 ┆ 1          ┆ 4_VUS       │
│            ┆      ┆             ┆     ┆   ┆ 2:35089109: ┆             ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ G:T         ┆             ┆            ┆             │
│ 999992     ┆ 3    ┆ 50379584    ┆ C   ┆ … ┆ NC_000003.1 ┆ NM_006030.4 ┆ 1          ┆ 4_VUS       │
│            ┆      ┆             ┆     ┆   ┆ 2:50379584: ┆             ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ C:T         ┆             ┆            ┆             │
│ 999993     ┆ 10   ┆ 101023538   ┆ C   ┆ … ┆ NC_000010.1 ┆ NM_00119526 ┆ 1          ┆ 4_VUS       │
│            ┆      ┆             ┆     ┆   ┆ 1:101023538 ┆ 3.2         ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ :C:T        ┆             ┆            ┆             │
│ 999994     ┆ 5    ┆ 55941246    ┆ T   ┆ … ┆ NC_000005.1 ┆ NM_002184.4 ┆ 1          ┆ 4_VUS       │
│            ┆      ┆             ┆     ┆   ┆ 0:55941246: ┆             ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ T:C         ┆             ┆            ┆             │
│ 999997     ┆ 9    ┆ 95461875    ┆ T   ┆ … ┆ NC_000009.1 ┆ NM_000264.5 ┆ 2          ┆ 4_VUS       │
│            ┆      ┆             ┆     ┆   ┆ 2:95461875: ┆             ┆            ┆             │
│            ┆      ┆             ┆     ┆   ┆ T:G         ┆             ┆            ┆             │
└────────────┴──────┴─────────────┴─────┴───┴─────────────┴─────────────┴────────────┴─────────────┘

#### De-duplicate them by simply keeping the first occurrence of gene_id and AA change

Not a very good idea. Deprecated.

In [1]:
# df_clinvar_dedup_var = df_clinvar_exploded.collect().unique(subset=["Ensembl_geneid", "HGVSp_snpEff"], keep="first")
# # df_clinvar_dedup_var
# df_clinvar_dedup_var.write_parquet(f"../3_outputs/processed_data/dbnsfp/dbNSFP5.0a_variant.clin_var_re-annot_dedup_variants.parquet")